### ISSUE TITLE
Windows Server

### ISSUE THREAD

**Issue by Alf71** [matecat/MateCat#1]
Hi,

Is it possible to install this in a Web Server like ZPANEL using WINDOWS?

**Comment by matecat** [comment]
Sorry, Matecat is created to run on unix servers.

You can alternatively run an unix server under a windows virtual machine.
You will find more info here:
[http://www.matecat.com/installation-guide/](http://www.matecat.com/installation-guide/)

**Comment by Alf71** [comment]
His sign in in Google the only way to manage when using a own server or virtual box?
