### ISSUE TITLE
Tilde MT integration

### ISSUE THREAD

**Issue by rihardsk** [matecat/MateCat#10]
I'm opening a new issue to use for communication on Tilde MT integration.

Here is a preview of basic Tilde MT integration [tilde-nlp/MateCat/commits/lets-mt-integration](https://github.com/tilde-nlp/MateCat/commits/lets-mt-integration). This basically just follows the stuff that was already there for MicrosoftHub and Moses engines.

The above code works but the user has to enter three different ID's (Client ID, System ID, Terms ID) to add our engine. So we would like to display some basic config options after the user enters the Client ID so that the System ID and Terms ID can be selected from a list. Here is a preview on how this might look [tilde-nlp/MateCat/commits/letsmt-advanced-integration](https://github.com/tilde-nlp/MateCat/commits/letsmt-advanced-integration).

I add the possibility to specify another template to be displayed after the user presses _Confirm_ in the initial view. The template is then filled with data that are returned by the engine (in place of the id of the newly added engine that would be returned in the usual scenario).

The stuff that is not yet implemented is some custom JavaScript that would be attached to the System selection dropdown onchange event (in the newly added engine config view). This is necessary to be able to return the available term collection ID's after the user selects a system from the dropdown. When the user clicks an element in the dropdown an AJAX call would be made to fetch the relevant term list and fill out the term dropdown.

This is the basic idea. Does this seem reasonable?

**Comment by matecat** [comment]
Seems reasonable for us, it's a good work.

Obviously all UI wrong behaviours must be fixed and the error checks must be implemented for all the service requests. 

Some CSS improvements are also needed.

In the first phase when the user insert it's client ID the button ```Confirm``` should be named ```Continue```

Great

**Comment by antoniofarina** [comment]
@Ostico confirmed that this issue can be closed.
We want really thank you for your cooperation.
