### ISSUE TITLE
Matecat in Nginx

### ISSUE THREAD

**Issue by bretanac93** [matecat/MateCat#1012]
Hey Guys, my issue is as mentioned in the subject, can you provide a nginx configuration file for matecat as the one you provide for Apache?, thanks.

**Comment by Ostico** [comment]
Hi @bretanac93 ,
Nginx is not supported at moment.

**Comment by bretanac93** [comment]
Ok, thanks a lot.

**Comment by Ostico** [comment]
There is an old configuration file for Nginx, but after we decided to break the support. 

If you want you can start from this:
https://github.com/matecat/MateCat/tree/develop/support_scripts/nginx-php-fpm
