### ISSUE TITLE
SQL Errors on Data Analysis

### ISSUE THREAD

**Issue by bretanac93** [matecat/MateCat#1016]
Hey guys, I already made a deployment of the Matecat System in Docker, and the UI and login works like a charm, but when I try to translate a document of a project, returns this error:
`Failed to create Job. ( SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'completed' at row 1 )`

![screen shot 2017-10-24 at 10 51 58](https://user-images.githubusercontent.com/3768876/31933429-65ea7832-b8a9-11e7-816c-a9cf08e691c4.png)
Attached is the error so you can check it smoother, this is the only error I have left (for now ;) )
Thanks in advanced.
Cheers.

**Comment by Ostico** [comment]
Hi @bretanac93 ,
please refer to this:

https://github.com/matecat/MateCat/issues/974

**Comment by bretanac93** [comment]
No worries, already solved a few days ago, thanks.
