### ISSUE TITLE
Yandex accounts

### ISSUE THREAD

**Issue by Lilimopps** [matecat/MateCat#1062]
Hello,

Is it possible to implement Yandex OAuth (https://tech.yandex.com/oauth/ )? We have a lot of users there and it's would be great to let them login easily.
Thanks!

**Comment by Ostico** [comment]
Hi @Lilimopps ,

we are working to generalize the OAuth system to make it generic and to make possible to integrate other systems, it is almost finished but at momenti i can't say an ETA for that.
