### ISSUE TITLE
Yandex.Translate and TM

### ISSUE THREAD

**Issue by Lilimopps** [matecat/MateCat#1063]
We’ve found that if the Yandex.Translate engine is enabled in the project settings, the TM doesn’t apply matches.
Could you please check on your side?

**Comment by alessandrocattelan** [comment]
In order to check on our side, we would need to activate the Yandex.Translate engine. Can you please provide us with an API key? Please, send it to support@matecat.com.

**Comment by Lilimopps** [comment]
Please find it here: https://tech.yandex.com/translate/
