### ISSUE TITLE
Export XLIFF - download one xliff file containing all files in project

### ISSUE THREAD

**Issue by krishnevsky** [matecat/MateCat#1079]
Enhancement request: When we have a project created from a folder with multiple files, the "Export XLIFF" command downloads a folder with multiple xliff files. We would like to get a single xliff file containing all the files in the project.

**Comment by Ostico** [comment]
Hi @krishnevsky ,
this will impact on the product compatibility with other cattools and is not in our roadmap. 
Thank you anyway for your suggestion, it is really appreciated.
