### ISSUE TITLE
TM Resources Management API level

### ISSUE THREAD

**Issue by bretanac93** [matecat/MateCat#1084]
It would be nice to have a way to manage the TMX (Import, Export, Activate/Deactivate, Erase) at API REST level, because doesn't make a lot of sense to manage glossaries at API level without having endpoints to retrieve this data. I know this should be a protected resource, and that's why should be nice to have a way to authenticate REST and stateless, let's say JWT, to retrieve user specific data like these private TMX.

**Comment by Ostico** [comment]
Hi @bretanac93 ,
your request is reasonable, we will implement of course the API for the TM management, but unfortunately it is not a close point in the roadmap.
