### ISSUE TITLE
How can I control the users of my own MateCat?

### ISSUE THREAD

**Issue by Heeyoung-Ahn** [matecat/MateCat#1120]
Thank you for your kindness and effort to make good system.

I have some question to use the MateCat.
1. I want to control the users of MateCat. How can I do this?
   I can't find the admin page in my own MateCat.
2. I have seen the plan of relesaing MyMemory as open source.(#465) Is it on progress?
3. Are the source files stored on your Server as well as on my own server?

**Comment by Heeyoung-Ahn** [comment]
More Questions.
1. Is TMX encrypted when it is stored on your server? Or is it stored without encryption?
2. Can your company's server administrator see our TMX technically?
Thanks~

**Comment by Ostico** [comment]
Hi @Heeyoung-Ahn 
1) There is no interface to admin the users in MateCat
2) Is in progress but the ETA is not defined
3) Can you explain better your request?

Regarding More questions:
1. TMX are not encrypted.
2. Yes some administrator with the right privileges can see the TMX.

**Comment by Heeyoung-Ahn** [comment]
Thank you for answer.
I understand the answer well and I look forward to MyMemory bundle.
