### ISSUE TITLE
if we install MateCat-tagProjectionEnIt build, can it be used with MMT?

### ISSUE THREAD

**Issue by mindaugasDEV** [matecat/MateCat#113]
Hello,

We would like to start using MateCAT with MMT in production as soon as possible (as MateCAT itself works fine, we only need MT).
1) can we just download MateCat-tagProjectionEnIt build and install so that we could work with MMT? I noticed that MMT.php is a very fresh file.
2) can MMT be used in production? I know you are still developing MMT, but I tested with your demo data and translations are being generated fine. Can we used it in production, together with our own installation of Matecat?

If answers are negative, then when you plan to integrate MMT and Matecat so that is can be used in production.
(if Github should not be used for questions like this, only real issues, then let me know, I will use email))

Thanks,
Mindaugas

**Comment by Ostico** [comment]
Hi @mindaugasDEV ,

MMT and TagProjection are currently in development and they can NOT be used in production. 
This feature is NOT tested. 
Moreover there are no public endpoints to MMT and the API interface itself could change at any time.

On MateCat this branch is not fully updated with the changes from master.
We are planning to release it of course, but when it will be completed and tested and when we'll find good results. I think in the second half of this year.
