### ISSUE TITLE
how shall we protect our MateCAT installation from DDOS attacks?

### ISSUE THREAD

**Issue by mindaugasDEV** [matecat/MateCat#114]
Hello,

I am sure that you took care to make PHP code secure, however, www.matecat.com is open to public.
How do you protect it from outside threats (as attack would paralyze all Translated.net).

Do you use Cloudfare services, or just a good hardware firewall?

Thanks,
Mindaugas

**Comment by Ostico** [comment]
Hi @mindaugasDEV ,
MateCat is not tied with Translated and use external services like MyMemory with which also it is no tied.
