### ISSUE TITLE
matecat.sql truncated

### ISSUE THREAD

**Issue by ozancaglayan** [matecat/MateCat#1148]
It seems that the matecat.sql file is down to ~110 lines from over 1K lines with a recent commit. Was this intentional?

**Comment by Ostico** [comment]
You're right, we will re-submit as soon as possible the complete file.
Anyway, previous versions are good and you can use them.
You can use this also:
https://github.com/matecat/MateCat/blob/paypal/lib/Model/matecat.sql

**Comment by ozancaglayan** [comment]
Can we use this to create mysql db correctly for the current master then? I was using an sql dump that you've attached to a bug report in May 2017 and applying migrations with phinx since the file was truncated.
Thanks.

**Comment by Ostico** [comment]
Just Fixed, the master repository is up to date now.
