### ISSUE TITLE
Wrong tag numbers inserted by keyboard shortcut

### ISSUE THREAD

**Issue by krishnevsky** [matecat/MateCat#1154]
We sometimes have large projects with lots of tags where the tag numbering gets carried over between segments. In these cases, sometimes the wrong numbers are available using the keyboard shortcut. The only solution is to add the wrong tag, then delete it (after this the correct tags are available to re-insert), or copy-paste the tags, or refresh the page and try again.
In rare cases, the keyboard shortcut doesn't even trigger anything until I refresh the page.
In some projects, it means we spend a lot of time fixing tag errors.  Unfortunately, I can't reproduce the issue reliably, but here is a video of this issue and the file containing the source shown in the video.
[Архив.zip](https://github.com/matecat/MateCat/files/1775371/default.zip)

**Comment by Ostico** [comment]
Hi @krishnevsky 
we are working to rewrite completely the tag management source code, these issues i think will be fixed in the next release, anyway the ETA is not defined at moment.

**Comment by Ostico** [comment]
Hi @krishnevsky , we updated the tag management code, can you tell us if this behaviour is fixed?

**Comment by krishnevsky** [comment]
Sorry for slow reply (vacation times). I haven't seen this behavior in the new version, and it looks like it is fixed. Thank you!
