### ISSUE TITLE
Configuration keys in the environment

### ISSUE THREAD

**Issue by bretanac93** [matecat/MateCat#1155]
Hi @Ostico I think it would be a good idea to add support for the configurations keys (currently working on `.ini` files only)  to load they values from environment variables or `.env` files, I think this would be important for scalability and better configuration handling, of course, keeping the old system in .ini files, I have this already implemented, so, if you want I can make a PR and add this feature to matecat code, what do you think?

**Comment by Ostico** [comment]
We already solved this issue by setting this on the virtual host configurations:
```
SetEnvIf Host ^myCustomInstance\. ENV=myCustomInstance
```

in the config.ini you can set an environment configuration:
```
[myCustomInstance]
CLI_HTTP_HOST = "http://myCustomInstance.matecat.com" ; Set the hostname for batch processes ( they do not know the global variable $_SERVER )
DB_SERVER = "localhost"
....
```

**Comment by bretanac93** [comment]
Super, thanks.
