### ISSUE TITLE
Displaying engine error messages during translation

### ISSUE THREAD

**Issue by rihardsk** [matecat/MateCat#12]
Error messages that are returned by an MT engine during translation aren't shown to the user.

This is a problem in the case of the Tilde MT engine. If a Tilde translation system has not been used for a while it enters a stand-by mode. It gets brought up again after a new translation request is made but waking up a system might take up to 10 minutes. This is a very common scenario so there really should be a way to let the user know why he isn't getting any translations from his MT engine. He might not be getting a translation due to a system still waking up or a system could have been turned off or deleted without the user knowing (by some other user). So there should be a way to let the user know whether he should just continue working while the system gets brought up or should he not expect a translation without some further actions (e.g. going to the Tilde MT site to check on the system).

Are there any plans to implement a mechanism to show error messages or some king of notifications during translation?

**Comment by matecat** [comment]
Hi, sorry, at moment we have no plans to implement error reposting directly from MT engines.

Regarding you warmup time, you have the same issue of Iconic.
They implemented an API method call to start their engines at the time of engine creation.

By the way, in their engine creation form we added this disclaimer:
```
Warning: IPTranslator has a startup time of some minutes. Make sure your engine is up before analyzing a document.
```
If you have the same problem, the same thing will be made for yout MT Engine

**Comment by rihardsk** [comment]
Waking up an engine at creation time is a good idea but there doesn't seem to be a good way to do this when choosing a previously created engine. Also the user cannot be sure whether there aren't any other problems with the engine.

This is why we would prefer to implement some kind of error message displaying functionality. Here are some mockups of how this might look:

![engine-errors-1](https://cloud.githubusercontent.com/assets/1666746/8904789/1feb68b0-346b-11e5-843e-104e088a2564.PNG)
![engine-errors-2](https://cloud.githubusercontent.com/assets/1666746/8904810/3a04e136-346b-11e5-9a59-8c85b1af3337.PNG)

The messages would appear after the translation suggestions and would be hidden by default.

Would something like this get accepted in upstream?
