### ISSUE TITLE
For additional download options

### ISSUE THREAD

**Issue by Heeyoung-Ahn** [matecat/MateCat#1204]
Hi.

Once the translation is complete, we can download only the Target language.
But sometimes we need to download both the Source language and the Target language as a single file.

Could you make an option to get the source language when we download the translated file?

Thanks.

**Comment by Ostico** [comment]
Hi @Heeyoung-Ahn 

you can download the original file by clicking the Original button in the dropdown menu.

**Comment by Heeyoung-Ahn** [comment]
Hi @Ostico 

I am saying that I want to download both the Source language and the Target language as a single file.

sample.
[source language]              [target language]
안녕하세요                         Hi

But at present I can't download like this..
So could you make an option to get download the source language together with the target language when I download the target language file after finish translate?

This is my question.^^
Please forgive my lack of English.

Thanks.
