### ISSUE TITLE
XLS Filetype is not working

### ISSUE THREAD

**Issue by bretanac93** [matecat/MateCat#1235]
Hi people, I'm currently stuck with the Additional filters, I already managed to set up a Windows server with Microsoft Office 2016 + Licenses, Visual Studio for compiling the Additional Filters C# Application and is working properly for doc and ppt documents, the mess comes with xls, when I upload a xls document, it gets forwarded to the additional filters server, here are screenshots for better understanding:

When I upload the file I receive "Bad Request" from Additional Filters:
![screenshot from 2018-05-14 16-34-07](https://user-images.githubusercontent.com/3768876/40003923-d2682e7a-5794-11e8-80cf-faec139eaecc.png)

And this is the stdout from the Windows Server VM:

![screenshot from 2018-05-14 16-34-12](https://user-images.githubusercontent.com/3768876/40004025-16aba616-5795-11e8-8246-ff7ec9de82f9.png)

**Comment by Ostico** [comment]
@giusilvano can help you in a better way in this particular case.

**Comment by bretanac93** [comment]
@Ostico thanks for your response, shall I repost this on the `Additional Filters` repository, after I posted it here I realized it was placed in the wrong repo.

**Comment by Ostico** [comment]
Yes @bretanac93 , thank you i close this.
