### ISSUE TITLE
Error: SyntaxError: Unexpected token s in JSON at position 0

### ISSUE THREAD

**Issue by burglarhobbit** [matecat/MateCat#1238]
I have setup the advance installation with great difficulty as the manual installation is still outdated as mentioned in #1118.
When I click on upload file and choose the sample file, I get this error from the apache2 error logs stored in /var/log/apache2/matecat.error.log which points to [this line](https://github.com/matecat/MateCat/blob/develop/lib/Utils/fileupload/upload.class.php#L40) in the source code: 
```
[Wed May 16 22:47:08.139802 2018] [:error] [pid 29981] [client ::1:57476] PHP Notice:  Undefined index: upload_session in /home/matecat/cattool/lib/Utils/fileupload/upload.class.php on line 40, referer: http://localhost/
```
I have also tried to track from the console tab outputs in the dev-console in Google Chrome to observe where the error originates from:
```
Failed to load resource: the server responded with a status of 401 (Unauthorized)
libs_upload.js?build=2.2.0f:3002
FIRE fileuploadchange libs_upload.js?build=2.2.0f:2180 
FILE:  
        File(174961)
	error:SyntaxError:
                SyntaxError: Unexpected token s in JSON at position 0
                at parse (<anonymous>)
                at Ut (http://localhost/public/js/build/libs_upload.js?build=2.2.0f:2:73768)
                at k (http://localhost/public/js/build/libs_upload.js?build=2.2.0f:2:77335)
                at XMLHttpRequest.<anonymous> (http://localhost/public/js/build/libs_upload.js?build=2.2.0f:2:79907)(http://localhost/public/js/build/libs_upload.js?build=2.2.0f:2:73768) at k (http://localhost/public/js/build/libs_upload.js?build=2.2.0f:2:77335) at XMLHttpRequest.<anonymous> (http://localhost/public/js/build/libs_upload.js?build=2.2.0f:2:79907)
	lastModified:1526353268000
	lastModifiedDate:Tue May 15 2018 08:31:08 GMT+0530 (IST) {}
	name:"File 2.xliff"
	size:174961
	type:"application/x-xliff"
	webkitRelativePath:""
	_super:undefined
	_superApply:undefined
	__proto__:File
```
which points to the `init` function in the `libs_upload.js` file from the `public/js/build` folder which had this condition in it:
```
if (this.json) {
	try {
		console.log( cookie );
		cookie = JSON.parse(cookie);

	} catch (e) {}
}
```

All the breadcrumbs points to some cookie issue in uploading the file, as I'm now stuck and need assistance on this error. Any help would be appreciated.

**Comment by Ostico** [comment]
First of all check the right permissions on the subdirectories of the storage directory.
They must be writable by the web server, check with which user Apache runs ( usually is www-data on default debian/ubuntu environments );

**Comment by burglarhobbit** [comment]
@Ostico 

Here is the output of ls -la /home/matecat/cattool/storage
```
total 36
drwxrwxrwx  8 www-data bhavya 4096 May 12 19:50 .
drwxrwxrwx 17 bhavya   bhavya 4096 May 16 22:42 ..
drwxrwxrwx  2 www-data bhavya 4096 May 12 19:50 conversion_errors
drwxrwxrwx  7 www-data bhavya 4096 May 14 21:38 files_storage
-rwxrwxrwx  1 www-data bhavya  125 May 12 19:50 .htaccess
-rwxrwxrwx  1 www-data bhavya    0 May 12 19:50 .keep
drwxrwxrwx  2 www-data bhavya 4096 May 15 21:12 log_archive
drwxrwxrwx  2 www-data bhavya 4096 May 12 19:50 reference_files
drwxrwxrwx  2 www-data bhavya 4096 May 12 19:50 tmp_download
drwxrwxrwx  3 www-data bhavya 4096 May 16 23:06 upload
```
and apache is running as `www-data` from the command  `ps aux | egrep '(apache|httpd)'`
``
root      1756  0.1  1.5 4644900 60716 ?       Sl   May15   3:00 /usr/bin/java -Xms64M -Xmx1G -Djava.util.logging.config.file=logging.properties -Djava.security.auth.login.config=/opt/apache-activemq-5.15.3//conf/login.config -Dcom.sun.management.jmxremote -Djava.awt.headless=true -Djava.io.tmpdir=/opt/apache-activemq-5.15.3//tmp -Dactivemq.classpath=/opt/apache-activemq-5.15.3//conf:/opt/apache-activemq-5.15.3//../lib/: -Dactivemq.home=/opt/apache-activemq-5.15.3/ -Dactivemq.base=/opt/apache-activemq-5.15.3/ -Dactivemq.conf=/opt/apache-activemq-5.15.3//conf -Dactivemq.data=/opt/apache-activemq-5.15.3//data -jar /opt/apache-activemq-5.15.3//bin/activemq.jar start
bhavya   14109  0.0  0.0  14228   948 pts/25   S+   13:34   0:00 grep -E (apache|httpd)
root     29894  0.0  0.2 387348  8540 ?        Ss   May16   0:00 /usr/sbin/apache2 -k start
www-data 29981  0.0  0.3 391860 13588 ?        S    May16   0:00 /usr/sbin/apache2 -k start
www-data 29982  0.0  0.1 388984  6700 ?        S    May16   0:00 /usr/sbin/apache2 -k start
www-data 29983  0.0  0.3 391824 15116 ?        S    May16   0:00 /usr/sbin/apache2 -k start
www-data 29984  0.0  0.0 387940  2968 ?        S    May16   0:00 /usr/sbin/apache2 -k start
www-data 29985  0.0  0.2 389764  9744 ?        S    May16   0:00 /usr/sbin/apache2 -k start
www-data 30032  0.0  0.3 389992 12028 ?        S    May16   0:00 /usr/sbin/apache2 -k start
www-data 30109  0.0  0.2 391860 11124 ?        S    May16   0:00 /usr/sbin/apache2 -k start
www-data 30121  0.0  0.0 387916  3528 ?        S    May16   0:00 /usr/sbin/apache2 -k start
www-data 30122  0.0  0.0 387940  3424 ?        S    May16   0:00 /usr/sbin/apache2 -k start
www-data 30207  0.0  0.0 387404  3496 ?        S    May16   0:00 /usr/sbin/apache2 -k start
``

**Comment by Ostico** [comment]
Hi @burglarhobbit ,
i read again you message error, you get a 401 when trying to load a JS resource. I'm wrong?
Call this url directly from your browser:
http://localhost/public/js/build/libs_upload.js

If this fails, could be related to some wrong apache configuration. JS resources are not behind to any kind of authorization request.

**Comment by burglarhobbit** [comment]
@Ostico It has been solved.

The solution is to use the release versions (2.0.1 in my case, but I think the latest one would work as well) instead of just cloning the "develop" branch. I highly recommend to update the advanced manual instructions as it suggests cloning the repository and the file naming of the oauth file has been changed.

**Comment by Ostico** [comment]
Yes, unfortunately, the instructions are not under git, so no pull request can be made, but please paste the commands here i will notify who must update them.

**Comment by burglarhobbit** [comment]
Here they are:

```
sudo adduser --disabled-password --gecos "" matecat
sudo passwd matecat # set password as matecat
sudo -u matecat -s # change user in terminal
cd /home/matecat
sudo apt-get update && sudo apt-get upgrade
sudo apt-get install php
sudo apt-get install php-pear php7.0-dev php7.0-zip php7.0-curl php7.0-gd php7.0-mysql php7.0-mcrypt php7.0-xml libapache2-mod-php7.0
sudo apt-get install screen php7.0-mbstring # mbstring package missing as it later gives error
sudo a2enmod rewrite filter deflate headers expires mod_version proxy_http.load
sudo apache2ctl restart

# requirements for mysql installation from source
sudo apt-get install libncurses-dev

# mysql setup (only if mysql is not installed before. refer the link below)
# refer: https://askubuntu.com/questions/763240/is-it-possible-to-install-mysql-5-5-or-5-6-on-ubuntu-16-04
# add /usr/local/bin to $PATH if mysql command doesn't work
sudo groupadd mysql
sudo useradd -r -g mysql mysql
# Beginning of source-build specific instructions
mkdir -p /usr/local/mysql # create if doesn't exist
cd /usr/local
tar -xzvf /home/matecat/mysql-5.5.50-linux2.6-x86_64.tar.gz # this file should be in /home/matecat folder
sudo mv mysql-5.5.50-linux2.6-x86_64 mysql
cd mysql
sudo chown -R mysql:mysql *
sudo apt-get install libaio1
sudo scripts/mysql_install_db --user=mysql
cd ..
sudo chown -R root .
cd mysql
sudo chown -R mysql data
sudo cp support-files/my-medium.cnf /etc/my.cnf 
echo "Starting MySQL..."
sudo bin/mysqld_safe --user=mysql &
sudo cp support-files/mysql.server /etc/init.d/mysql.server

sudo bin/mysqladmin -u root password '12345'
sudo /etc/init.d/mysql.server start

sudo ln -s /usr/local/mysql/bin/mysql /usr/local/bin/mysql
mysql -u root -p

############################
# install active mq
cd
wget http://apache.mirrors.lucidnetworks.net/activemq/5.15.3/apache-activemq-5.15.3-bin.tar.gz
tar xzf apache-activemq-5.15.3-bin.tar.gz
sudo mv apache-activemq-5.15.3 /opt
sudo ln -sf /opt/apache-activemq-5.15.3/ /opt/activemq
sudo adduser -system activemq
sudo sed -i 's#activemq:/bin/false#activemq:/bin/bash#g' /etc/passwd
sudo chown -R activemq: /opt/apache-activemq-5.15.3/
sudo ln -sf /opt/activemq/bin/activemq /etc/init.d/
sudo sed -i 's#exit 0##g' /etc/rc.local
sudo sh -c 'echo "/bin/sh /usr/bin/activemq start" >> /etc/rc.local'

sudo /etc/init.d/activemq create /etc/default/activemq
sudo chown root:nogroup /etc/default/activemq
sudo chmod 600 /etc/default/activemq

sudo sed -i 's/Context createConnector='false'/Context createConnector='true'/g' /etc/default/activemq/conf/activemq.xml
sudo ln -s /etc/init.d/activemq /usr/bin/activemq
sudo activemq start

sudo apt-get install redis-server
sudo sed -i 's/bind 127.0.0.1/bind 0.0.0.0/g' /etc/redis/redis.conf
sudo service redis-server restart

##########################
## install node.js

curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
#And use the Node.js package manager to install Grunt

npm install grunt
sudo npm install -g grunt-cli
# Finally make sure Node.js will start at startup
sudo -i
echo "screen -d -m -S 'node' node \/home\/matecat\/cattool\/nodejs\/server.js" >> /etc/rc.local
echo "short_open_tag = On" >> /etc/php/7.0/cli/php.ini
echo "memory_limit = 1024M" >> /etc/php/7.0/cli/php.ini
exit

sudo apache2ctl restart

su - matecat
git clone https://github.com/matecat/MateCat.git cattool

cd ~/cattool/lib/Model
mysql -u root -p < matecat.sql

cd ~/cattool/INSTALL
cp matecat-vhost.conf.sample matecat-vhost.conf
sed -i "s/@@@path@@@/\/home\/matecat\/cattool/g" matecat-vhost.conf

sudo mv /home/matecat/cattool/INSTALL/matecat-vhost.conf /etc/apache2/sites-available
sudo a2ensite matecat-vhost.conf
sudo apache2ctl restart

cd ~/cattool
sudo su
php -r "readfile('https://getcomposer.org/installer');" | php
php composer.phar --no-dev install
exit

########
cd ~/cattool/inc
cp config.ini.sample config.ini
cp task_manager_config.ini.sample task_manager_config.ini
sed -i "s/\/home\/matecat\/storage/\/home\/matecat\/cattool\/storage/g" config.ini

#######
# compile javascript code
cd ~/cattool/support_scripts/grunt
npm install
grunt deploy

#######
# configure node.js
cd ~/cattool/nodejs
cp config.ini.sample config.ini
npm install

#######
# turn on the Analysis daemon
cd ~/cattool/daemons
echo '25' > .num_processes
/bin/bash /home/matecat/cattool/daemons/restartAnalysis.sh
sudo chown -R www-data /home/matecat/cattool/storage/

screen -d -m -S 'node' node /home/matecat/cattool/nodejs/server.js

#######
# google login
# edit the file with these parameters
cp ~/cattool/inc/oauth_config.ini.sample ~/cattool/inc/oauth_config.ini

### set the oauth confi file
[OAUTH_CONFIG]
OAUTH_CLIENT_ID       = xxxxx
OAUTH_CLIENT_SECRET   = yyyyy
OAUTH_CLIENT_APP_NAME = Matecat
OAUTH_BROWSER_API_KEY = zzzzz

chmod 400  ~/cattool/inc/oauth_config.ini
sudo chown www-data:www-data ~/cattool/inc/oauth_config.ini

gedit inc/config.ini
	replace localhost with 127.0.0.1 
	check ENV = "production"
	change dbuser, dbpass = root, 12345 (or whatever you have set in the database)

# if screen doesn't work if login as different user from terminal, run: script /dev/null

chmod +r+r+r /home/matecat/cattool/inc/login_secret.dat
# gave write permission to middle-id as orignal setting was 755 and it gave permission denied error in php
sudo chmod 775 -R storage/files_storage/fastAnalysis/
sudo chmod 775 -R storage/files_storage/queueProjects/
```

**Comment by Ostico** [comment]
Thank you @burglarhobbit

**Comment by philippehenri** [comment]
Hello,
i have also tried to install matecat with great difficulties (on Ubuntu 16.05 mysql 5.6, apache 2.4 all setup and running in a docker container) - from instructions of advanced setup and a few fixes

now when i try to load http://localhost, i get the main screen but a 401 error on the call to /api/app/user (just after the include of prum.min.js)

looking at the code this seems to happen in LoginValidator.php which returns an empty user (although i didnt do any login):

       $user = $this->controller->getUser();

        if( empty( $user ) ){
             throw new AuthenticationError( "Invalid Login.", 401 );
        }

Could someone help me finding what is wrong here?

thanks
philippe
