### ISSUE TITLE
Running matecat on a LAN instead of localhost

### ISSUE THREAD

**Issue by burglarhobbit** [matecat/MateCat#1264]
I have setup matecat from the advanced installation guide. What can I do to run matecat on a LAN network instead of just accessing it through a localhost system? I tried changing the ip in config.ini to 0.0.0.0 but it still works only through localhost.

**Comment by Ostico** [comment]
The config.ini is not responsible of the url served by your web server. You have to properly configure apache.

**Comment by burglarhobbit** [comment]
@Ostico Can you suggest a virtual host configuration that can work for this? Or is it some apache internal configuration that's responsible for this?

**Comment by Ostico** [comment]
If you followed the advanced setup, Apache is already set to serve on on all the IP configured on your server on the port 80.
```
 <VirtualHost *:80>
        ServerName localhost
```
But is declared to respond to the localhost server name. Remove such directive and restart apache.

**Comment by Ostico** [comment]
Are you sure you are going with the browser on the right LAN IP ( that of your MateCat installation )? It should work. 

To know exactly the IP of the server on which MateCat is running, go on such server and on the shell console type:
```
ip route get 8.8.8.8 | awk '{print $NF; exit}'
```

**Comment by burglarhobbit** [comment]
Fixed. Disable any .conf enabled sites running on the same port. In my case, it was the default conf site I had to disable.

**Comment by Ostico** [comment]
:+1:
