### ISSUE TITLE
MateCat Multiple Instance Setup

### ISSUE THREAD

**Issue by uhallac** [matecat/MateCat#1276]
In Hardware Requirements section of the installation guide (https://www.matecat.com/installation-guide/), I can see it's possible to set up multiple instances of MateCat by adding a load balancer. Are there any documentations explaining the details for this setup? 

Web servers are using local file systems by default. So are you supposed to use a network location as the storage folders for all web servers?

**Comment by Ostico** [comment]
Hi @uhallac ,
sorry, there is no documentation to explain this task. If your company needs expertise to do that you can contact the MateCat support, we will try to find an agreement.

Regarding the storage, yes, for the simplest implementation, it is supposed to do that with network storage.

**Comment by bretanac93** [comment]
@uhallac I managed to implement a similar solution, everything shared goes into `storage` folder, and for production the documentation advices to use an NFS server, if you implement such, then you can run more than one instance, but I would advice you to create another service for the analyzer separated from the apache web server, with that should be more than enough to put it to run.
Cheers.

**Comment by Ostico** [comment]
Closing
