### ISSUE TITLE
spaces in translator's interface

### ISSUE THREAD

**Issue by Lilimopps** [matecat/MateCat#1310]
Hi Team,

There are some difficulties with spaces now. We need to see spaces and nonbreaking spaces, check if there are double spaces or spaces at the beginning/ending of segment (if needed).

In other tools it usually highlights as dots and circles, or with colours. And you can turn it on and off.

Do you plan to add visualization for spaces/nonbreaking spaces? It would be really helpful.
Is there any check for double spaces in default MateCat QA?

**Comment by Ostico** [comment]
Hi @Lilimopps 
at moment this feature/enhancement is not on our roadmap, anyway, you can enable Lexiqa to get more integrity checks on the translations.

Thanks
