### ISSUE TITLE
Add information to the API about segments with tag issues

### ISSUE THREAD

**Issue by giemsky** [matecat/MateCat#1322]
Hi,

Currently it's impossible to know from API perspective about segments having tag issue. There is no job status for this nor such segments are included in job stats. Would it be possible to at least add how many segments got tag mismatch errors in job stats?

Thank you

**Comment by Ostico** [comment]
Maybe a dedicated API would be better

**Comment by riccio82** [comment]
With this API you can get all the translation issues: https://www.matecat.com/api/docs#/Job/get_api_v2_jobs__id_job___password__translation_issues
