### ISSUE TITLE
Matecat not working after following the official guide :-(

### ISSUE THREAD

**Issue by psykodaddy** [matecat/MateCat#1332]
Hello guys.

We run a small family business and I tried to set up matecat on a HP ProLiant 360 G5.

First thing I have to say, I'm not a Linux Pro, I'm more a script kiddie used to play around with Linux some times before. So sorry for any "dumb" questions or comments :-D

I used Debian 9.5.0

I followed the official guide (https://www.matecat.com/advanced-manual-setup/), although I know it's quite outdated. Attached is this guide in PDF version with my changes to the process in RED.
[UPDATE_AUG-2018Advanced manual setup – Matecat.pdf](https://github.com/matecat/MateCat/files/2342755/UPDATE_AUG-2018Advanced.manual.setup.Matecat.pdf)

After all the stuff I tried to start matecat in chrome and firefox with localhost, but all I get is a blank tab with just the favicon correctly. Nothing else. (The server is reachable via network, that's my small achievement here)

And yes, I ran composer in /home/matecat/cattool/ ;-)

Here are my logs in a zip attached:
[log_archive.zip](https://github.com/matecat/MateCat/files/2342756/log_archive.zip)

I obtained a filter key from Mashape and inserted it...I didn't set up the Google API or client or whatelse. I would like to do that after all the stuff is running correctly.

Can someone please help! I spent nights and days with googling around and trying so far my know-how brought me.

Is there something I missed or did wrong?

Thanks for your help and time, guys!

-p-

**Comment by psykodaddy** [comment]
Hi again,

I managed it on my own 👍  YAY

I used Debian wheezy (7.11) instead of stretch (9.5) and followed the official guide like edited attached:

[UPDATE_AUG-2018_DEBIAN-7.11_Advanced manual setup – Matecat.pdf](https://github.com/matecat/MateCat/files/2343856/UPDATE_AUG-2018_DEBIAN-7.11_Advanced.manual.setup.Matecat.pdf)

Now it works just fine!

**Comment by psykodaddy** [comment]
BTW: I think it was some php and composer stuff that wasn't able to work properly on Debian 9.5...

**Comment by Ostico** [comment]
Thank you @psykodaddy , happy to see that all worked now.

From you logs it seems that you not installed ( composer dependency issues with php 5.6.37 ? ) the google client library: `Class 'Google_Client' not found`.

**Comment by mohammedayub44** [comment]
@psykodaddy  @Ostico 
I get the same thing on localhost, blank page with a favicon. I have followed the same advanced manual and running it on Ubuntu 16.04. 
how do I troubleshoot what is going wrong ? Any help appreciated. 

Thanks !
