### ISSUE TITLE
More performance in counting words

### ISSUE THREAD

**Issue by psykodaddy** [matecat/MateCat#1334]
Hello again @Ostico  :-)

Now as my server is running great, I would like tot weak the performance in counting the words. The official matecat site jumps in steps of 30-50 segments when adding a new project and counting the words.

My own server jumps just 10-20 segments...

I gave num.processes 1200 workers and the php.ini 10240MB memory_limit

It's still quite slow... (I have 32GB RAM available)

What can I do here, please?

Thanks and Best

**Comment by giemsky** [comment]
Have you tried increasing number of analysis executors in the following file?
`https://github.com/matecat/MateCat/blob/develop/inc/task_manager_config.ini`

**Comment by psykodaddy** [comment]
Hi @giemsky 

Thanks for the hint! I just pushed the num_processes by now :-)

What are they responsible for exactly? I thought they are for counting and so on...

I edited my inc/task_manager_config.ini and will try soon if it tweaked the counting process.

Thanks a lot!

**Comment by giemsky** [comment]
These are workers responsible for documents analysis. The greater the number the more concurrent workers you are going to have, which makes analysis faster.

**Comment by psykodaddy** [comment]
Thanks. And what is the value in num_processes doing? I just know that one process uses around 13M RAM :-D

**Comment by giemsky** [comment]
What setting exactly are you talking about and in which file?

**Comment by giemsky** [comment]
Sorry, never experimented with this setting (got default value = `25`).

**Comment by psykodaddy** [comment]
I have this file, and it's even mentioned in the official guide...maybe it's just out of date?
