### ISSUE TITLE
Changing multiple segments statuses in different files does not work

### ISSUE THREAD

**Issue by kocesma** [matecat/MateCat#1337]
Precondition:
Matecat project includes several (dita) files. The segments have "Translated" status. Revise mode is activated.

Steps:
1. Filter all segments which have "Translated" status
2. Select all the filtered segments in different files
3. Mark the segments as approved

Actual result:
The segments do not change their statuses as they relate to different files

Expected result:
The segments change their statuses to Approved

**Comment by kocesma** [comment]
Will provide a link to a project when reproduces again

**Comment by Lilimopps** [comment]
I have more issues:
- can't select more segments with filter if more than 1000 segments;
- can't select segments with Shift if there are few files in project.

**Comment by Ostico** [comment]
Hi @kocesma , @Lilimopps 
try to un-comment and/or set to an higher value than the default:

```
; How many GET/POST/COOKIE input variables may be accepted
; max_input_vars = 1000
```

in php.ini and let me know if this helps.

**Comment by Lilimopps** [comment]
@Ostico It doesn't help. We changed it to 5000, and now just get empty response. No result still. Any ideas?

**Comment by riccio82** [comment]
Fixed
