### ISSUE TITLE
API multiple file upload error 

### ISSUE THREAD

**Issue by giemsky** [matecat/MateCat#1338]
I'm getting error when trying to create project with multiple files.

Request:
```
curl -F "project_name=test" -F "source_lang=pl-PL" -F "target_lang=en-GB" \
-F "files[]=@3_fr.html" -F "files[]=@37_fr.html" https://www.matecat.com/api/v1/new
```

Matecat response:
```
{"status":"FAIL","message":"Upload::_uploadFile -> Unknown Error: Array"}
```

What's the proper way tu create project with multiple files?

**Comment by giemsky** [comment]
Well, I figured it out myself looking at PHP code. The proper way to send files using API is naming each file parameter differently. 

E.g.
```
curl -F "project_name=test" -F "source_lang=pl-PL" -F "target_lang=en-GB" \
-F "file1=@3_fr.html" -F "file2=@37_fr.html" https://www.matecat.com/api/v1/new
```

This way the method is working, but API documentation is misleading.
https://www.matecat.com/api/docs#/Project/post_api_v1_new
```
files *file(formData) | The file(s) to be uploaded.
```

**Comment by Ostico** [comment]
Hi @giemsky ,

thank you for the issue, it will be fixed in the next release. Both methods will work.
