### ISSUE TITLE
Matecat showing version 2.4.1b

### ISSUE THREAD

**Issue by psykodaddy** [matecat/MateCat#1365]
Me again :-)

Today I found a file showing that my matecat is version 2.4.1b

I thought the latest release is 2.3.0

![version](https://user-images.githubusercontent.com/42899011/46345714-df86da00-c645-11e8-8230-51c4430f5793.png)

**Comment by Ostico** [comment]
Hi @psykodaddy , you're correct, such file is the MateCat version. We do not publish a release tag for every version we upgrade unless we are sure that is a stable version and the new features are stable also.
