### ISSUE TITLE
net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)

### ISSUE THREAD

**Issue by philippehenri** [matecat/MateCat#1402]
Hello

On a local MC, I get plenty of messages in google chrome console (very x seconds, even when the user is doing nothing):

sse/channel/comments?jid=17&pw=315576f17131:1 GET …/sse/channel/comments?jid=17&pw=315576f17131 net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)

Can someone help me to solve this problem?

thanks
ph

**Comment by riccio82** [comment]
Hi @philippehenri ,

that is the SSE channel for comments, to make it work you have to start the node server located in nodejs folder.

Happy New Year!

**Comment by philippehenri** [comment]
thanks for your reply.

I am not using SSL. I tried to disable Avast on the client (i do not have avast on server), same problem :-(

In fact i note that this happens everytime i receive a 'ack' from the server, i get both these lines every x second (in chrome console):

/sse/channel/comments?jid=20&pw=483d9b7d9a3e:1 GET …/sse/channel/comments?jid=20&pw=483d9b7d9a3e net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)
EventSource failed loading: GET “…/sse/channel/comments?jid=20&pw=483d9b7d9a3e".

and this message (that i display on console from app.js) EVENT RECEIVED :"{\"_type\":\"ack\",\"clientId\":\"6a5f880c1505\"}"

I note also that i receive each time a different clientid (normal?)

any more idea?
thanks

**Comment by riccio82** [comment]
The different clientid is normal.

If you try to use matecat.com from the same client you connect to your MC, do the comments and contributions work? Have you tried using another client?

**Comment by Lalo19** [comment]
NULL fields in database. I have read that could be for many reason, in my case that was a problem with null fields in queries. I filled the NULL fields in my database and the error has gone. If is the same problem, you have to implement exceptions for null values.

**Comment by philippehenri** [comment]
@Lalo19  NULL fields? for SSE channels? Can you please elaborate and let me know which fields in which tables ? or better: where in the code did you encounter exceptions related to this problem? thanks

**Comment by Lalo19** [comment]
@philippehenri  Not specifically with SSE channels. As I mentioned before it could be something else. In my case, when I had this problem, it was when I developed a web API in C #, and I discovered that it only appeared when I had null data in my database. I filled the null data fields in my database, and the problem disappeared. The problem can be from code or from server configurations, coding error or handling of null variables from the server to browsers. In most forums they mentioned things like problems with antivirus, but in my case it was with the handling of variables. That is why I also saw it important to mention it as an experience, and possible reason. Just try

**Comment by abesalomi** [comment]
Hi @philippehenri,

 I had the same issue and I had nginx proxy and server storage, where nginx is started, was full.

**Comment by philippehenri** [comment]
Hi @abesalomi 
thanks. I am not sure to understand how you fixed it? (i am using apache)
thanks

**Comment by EvellynF** [comment]
> Campos NULL no banco de dados. Eu li que poderia ser por vários motivos, no meu caso, houve um problema com campos nulos nas consultas. Preenchi os campos NULL no meu banco de dados e o erro desapareceu. Se for o mesmo problema, você precisará implementar exceções no código

Muito obrigada, cara! no meu caso foi exatamente isso.
