### ISSUE TITLE
Disappearing TM ?

### ISSUE THREAD

**Issue by philippehenri** [matecat/MateCat#1410]
Hello,

There seems to be a case where MC “loses” a TM:

1/ create a project “testproject” without being logged. Add a new TM (let’s say “testtm”). Launch Analysis, then when offered to login: do the login, lets say “testuser”.

go to settings panel: the TM appears as “***************45c5d” for example. (why ‘***’ as I am logged? anyway, it is there).

2/ now remain logged and create a NEW project. Go to settings. all TMs of “testuser” are there except “testtm” ??

note: "testtm" is only there if I open the “testproject” 

Is this normal?

thanks
Ph

**Comment by Ostico** [comment]
Hi @philippehenri , your correct, this is an implementation we have to do, you can claim the project just created as anonymous user but you can not do the same with the TM.

**Comment by philippehenri** [comment]
ok noted. thanks
