### ISSUE TITLE
API Endpoint for XLIFF-to-target

### ISSUE THREAD

**Issue by KaiReichart** [matecat/MateCat#1420]
Hi, is there an API endpoint availiable for the [XLIFF-to-target](https://www.matecat.com/utils/xliff-to-target) tool? 
I wasn´t able to find Information on that in the API Docs...

**Comment by Ostico** [comment]
Sorry, no endpoint is available for that.

**Comment by laurensV** [comment]
Any plans to add this endpoint? Would be really useful!

**Comment by KaiReichart** [comment]
I found a workaround for this:
Use the Matecat Filters Project [https://github.com/matecat/MateCat-Filters](https://github.com/matecat/MateCat-Filters)
Docker Image: [https://hub.docker.com/r/kaireichart/matecat-filters](https://hub.docker.com/r/kaireichart/matecat-filters)

You'll have to self-host it but it doesn't use too many resources

It seems like the Project has been closed from now on, but i haven't had any Problems with it yet.

**Comment by Ostico** [comment]
Hi @KaiReichart the endpoint is now available at:
https://www.matecat.com/utils/xliff-to-target
