### ISSUE TITLE
Importing 2 TMX at the same time -> system freezes on matecat.com

### ISSUE THREAD

**Issue by philippehenri** [matecat/MateCat#1432]
Hello

is it normal /are you aware that the systems freezes when importing 2 TMX at the same time (on matecat.com)?

see attached screen capture where nothing happens...

ph

![image](https://user-images.githubusercontent.com/33929447/53679114-707ee180-3cc8-11e9-833f-5b30e5e154a3.png)

**Comment by riccio82** [comment]
Fixed
