### ISSUE TITLE
Broken VM download links

### ISSUE THREAD

**Issue by lorenzoranucci** [matecat/MateCat#1442]
[matecat_latest.ova](https://www.matecat.com/vm/matecat_latest.ova) placed in the [Installation guide](https://www.matecat.com/installation-guide/#downloadvm) returns a 404 error.

Same problem with [matecat_latest.vdi](http://www.matecat.com/vm/matecat_latest.vdi).

**Comment by nonsequitir** [comment]
Any update on these VMs?

**Comment by netsatan** [comment]
Hi,
Any news? :)

**Comment by razorcell** [comment]
Still broken !

**Comment by mohammedayub44** [comment]
I think its still broken.

**Comment by tsanev016** [comment]
Hi, any mirros for this link? Im still searching for it....
Thank you so much!

**Comment by samnaz** [comment]
Hi,
Any news? :)

**Comment by cidrugHug8** [comment]
still broken...

**Comment by mohammedgomaa** [comment]
still broken...

**Comment by Wierzciu** [comment]
still bronken : \

**Comment by credo99** [comment]
Of course....still broken and no answer also on the site contact form...

**Comment by riccio82** [comment]
Installation guide: https://site.matecat.com/installation-guide
No more Virtual Machine.
