### ISSUE TITLE
Request for integration of DeepL

### ISSUE THREAD

**Issue by psykodaddy** [matecat/MateCat#1472]
Hello again :-)

I love to work with matecat more and more for all the years!

I'm a german translator and there's a new break through in the industry.

Can you integrate the MT engine DeepL, please?

https://www.deepl.com/docs-api.html

Thanks a lot for your effort!

Best,

Sami

**Comment by Ostico** [comment]
We will try to schedule, but this is not a priority for us at moment.

**Comment by earendil1** [comment]
Hi @Ostico are there any updates on this? We are an international team of translators who work on a non-profit project. Deepl would be a real plus for our translating jobs.

**Comment by mrmaly** [comment]
Please reconsider.

**Comment by riccio82** [comment]
We are working on it

**Comment by eslksw** [comment]
It appears to be available in the most recent MateCat ([cf.](https://guides.matecat.com/machine-translation-engines)), so I guess this issue can be closed.
