### ISSUE TITLE
Ops.. we got an error. No text to translate in the file

### ISSUE THREAD

**Issue by MartynasSyn** [matecat/MateCat#1497]
Hello,

Am getting this error message "Ops.. we got an error. No text to translate in the file" when pressing Analyze button. Tried with different file types. (.txt, .pdf, .docx) always the same error.

I believe that the problem is somewhere on the daemons server (am using separate servers for WEB tier and Daemons) but i can't figure out what is wrong. Can anyone suggest me where to look the problem?

Error message from /var/log/apache2/matecat.error.log
 [:error] [pid 2923] [client 10.0.x.xx:37618] PHP Warning:  session_start(): Cannot send session cache limiter - headers already sent (output started at /home/matecat/cattool/lib/Controller/AbstractControllers/ajaxController.php:58) in /home/matecat/cattool/inc/Bootstrap.php on line 259, referer: https://syncat.synergium.eu/analyze/filenamedocx/91-1ec2eaf53d3b

Matecat version 2.7.5a

**Comment by Ostico** [comment]
I think you have to export in NFS the ` storage/files_storage ` directory and share it between nodes and daemon server.

**Comment by MartynasSyn** [comment]
In booth nodes (WEB and Daemon servers) in cattool/inc/config.ini file i provided the same path : STORAGE_DIR = "/media/SynCat/SynCat3"  

And both nodes and daemon servers have a mount to a network share folder (using CIFS) so all three servers can access the same network share.

**Comment by Ostico** [comment]
Check the writes permission on upload directory located in <basedir>/storage/upload
those are located on single web nodes and not shared on network, they must be writable by the web servers.

Check also the cache directory shared on CIFS ( in your case /media/SynCat/SynCat3/storage/files_storage/cache ) it must be writable by web nodes.

**Comment by MartynasSyn** [comment]
All is good now, Thank you!
