### ISSUE TITLE
php tag on PHP 5.6

### ISSUE THREAD

**Issue by astbss** [matecat/MateCat#15]
Hi
Just installed MateCat on Debian 8.1
PHP 5.6.12-0+deb8u1 (cli)

I checked it out from git
There following 4 files are missing the starting <?php  using the old <?
This is not working anymore on PHP 5.6

lib/Utils/CatUtils.php
lib/Utils/MyMemory.copyrighted.php
lib/Utils/Engines/Results/MyMemory/TMS.php
lib/Utils/Engines/Results/MyMemory/Matches.php

Thanks for an amusing software

Are Casilla

**Comment by matecat** [comment]
Hi @astbss ,

thank you for contribution, we will improve this in the next version.

By the way, if you look at the virual host configuration sample https://github.com/matecat/MateCat/blob/master/INSTALL/matecat-vhost.conf.sample#L33 
the flad short_open_tag i set On.

Surely you forgotten this configuration.

**Comment by astbss** [comment]
Thanks 
I only get the issue when running CLI Analysis
screen -d -m -S fast php fastAnalysis.php
screen -d -m -S tm php tmAnalysisThread.php

Analysis refuses to run. Not sure if there is similar setting for cli

Just for info the following grep show all the files with this issue. 
grep -r '^<?$' *

lib/View/APIDoc.php:<?
lib/Utils/Engines/Results/MT.php:<?
lib/Utils/Engines/Results/ErrorMatches.php:<?
lib/Utils/Langs/Languages.php:<?
lib/Utils/Langs/LanguageDomains.php:<?
lib/Utils/manage.class.php:<?
lib/Utils/xliff.parser.1.3.class.php:<?
lib/Utils/XliffSAXTranslationReplacer.php:<?
lib/Utils/mime2extension.inc.php:<?
lib/Model/FilesStorage.php:<?
lib/Controller/getWarningController.php:<?
lib/Controller/formLoginController.php:<?

**Comment by antoniofarina** [comment]
You can enable short_open_tag in /etc/php5/cli/php.ini also.

**Comment by matecat** [comment]
Thank you, for other developer/users, i report here the installation guide link as reminder:

http://www.matecat.com/advanced-manual-setup/#tpc
