### ISSUE TITLE
No translation suggests from public TM

### ISSUE THREAD

**Issue by MartynasSyn** [matecat/MateCat#1500]
Hello,

I do not get any translation matches when opening a job. The circle is just spinning round and nothing happens. The error message i get when i jump to another segment is:

[Tue May 21 06:34:14.655592 2019] [:error] [pid 21853] [client 10.0.1.55:13068] PHP Warning:  session_start(): Cannot send session cookie - headers already sent by (output started at /home/matecat/cattool/lib/Controller/AbstractControllers/ajaxController.php:58) in /home/matecat/cattool/inc/Bootstrap.php on line 259, referer: https://testcat.synergium.eu/translate/addcardtxt/en-US-fr-FR/91-ab80f433b7d7

**Comment by MartynasSyn** [comment]
Can anyone explain me what should be provided here in /home/matecat/cattool/inc/config.ini file?  SSE_BASED_URL = "" if i leave it with default value "locahost/sse" im getting this error when jumping into next segment.
 GET https://localhost/sse/channel/updates?jid=99&pw=79294d926998 net::ERR_CONNECTION_REFUSED

**Comment by Ostico** [comment]
You have to start node server.js located in 
https://github.com/matecat/MateCat/blob/develop/nodejs/server.js

**Comment by MartynasSyn** [comment]
this is the error message i get after executing node server.js command:

debug: Listening on http://localhost:7788/
debug: ** client error, restarting connection in 10 seconds Error: connect timed out
    at Client.Socket._createError (/home/matecat/cattool/nodejs/node_modules/stompit/lib/Socket.js:251:13)
    at Client.Socket.createTransportError (/home/matecat/cattool/nodejs/node_modules/stompit/lib/Socket.js:267:20)
    at Timeout.<anonymous> (/home/matecat/cattool/nodejs/node_modules/stompit/lib/connect.js:65:29)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)

If i change "host = activemq-0.svc.production.matecat.cloud" to "host = my daemons servername" then it don't give any error message.

**Comment by MartynasSyn** [comment]
Ok i have managed to make it work. My bad was that i used wrong address in SSE_BASED_URL = ""

I also had to change host = activemq-0.svc.production.matecat.cloud to host = "daemon server FQDM" because i user tiered matecat installation.

Thank you Ostico for your support.
