### ISSUE TITLE
blank page

### ISSUE THREAD

**Issue by kumaramit23** [matecat/MateCat#1503]
Hello,

I have setup matecat on one vps but I am facing isse of blank page after installation.

Can you please help me to solve this.

**Comment by Ostico** [comment]
Please, provide more info and logs

**Comment by kumaramit23** [comment]
Can I get your OVA image download link to load at my end ?
Best Regards
Amit makkar
PH : +917374060606
 
               
Web: www.sayonetechnologies.com

Specialized in: AWS | Tech Support | Server anagement | Migrations | Email Solutions

So many times, it happens too fast.. You change your passion for glory. Don't lose your grip on the dreams of the past.. 
You must fight just to keep them alive "This e-mail (and any attachments), is confidential and may be privileged. 
It may be used only by intended recipients. Unauthorized access, disclosure or copying of its contents or any action taken in reliance on it is unlawful. 
Unintended recipients must notify the sender immediately & delete it from their system without making any copies or disclosing it to a third person."
Please consider your environmental responsibility before printing this e-mail

**Comment by 951722070** [comment]
请问这个问题需要怎么解决呢，同样遇到了这个问题。只显示了log，感谢

**Comment by kumaramit23** [comment]
I am trying to install mate cat on my vps. After all steps completion it is showing blank page.
Best Regards
Amit makkar
PH : +917374060606
 
               
Web: www.sayonetechnologies.com

Specialized in: AWS | Tech Support | Server anagement | Migrations | Email Solutions

So many times, it happens too fast.. You change your passion for glory. Don't lose your grip on the dreams of the past.. 
You must fight just to keep them alive "This e-mail (and any attachments), is confidential and may be privileged. 
It may be used only by intended recipients. Unauthorized access, disclosure or copying of its contents or any action taken in reliance on it is unlawful. 
Unintended recipients must notify the sender immediately & delete it from their system without making any copies or disclosing it to a third person."
Please consider your environmental responsibility before printing this e-mail

**Comment by cidrugHug8** [comment]
try it on chrome?
