### ISSUE TITLE
Fastanalysis and Tmanalysis

### ISSUE THREAD

**Issue by MartynasSyn** [matecat/MateCat#1505]
Hello,

I have installed and configured a supervisor for TmAnalysis.php and Fastanalysis.php

**nano /etc/supervisor/conf.d/fastanalysis.conf**
[program:fast_analysis]
command=/usr/bin/php /home/matecat/cattool/lib/Utils/Analysis/FastAnalysis.php ../../../inc/task_manager_config.ini
directory=/home/matecat/cattool/lib/Utils/Analysis
autostart=true
autorestart=true
startretries=10
stderr_logfile=/var/log/fastanalysis.err.log
stdout_logfile=/var/log/fastanalysis.out.log
user=root

**nano /etc/supervisor/conf.d/tmanalysis.conf**
[program:tm_analysis]
command=/usr/bin/php /home/matecat/cattool/lib/Utils/Analysis/TmAnalysis.php ../../../inc/task_manager_config.ini
directory=/home/matecat/cattool/lib/Utils/Analysis/
autostart=true
autorestart=true
startretries=10
stderr_logfile=/var/log/tm_analysis.err.log
stdout_logfile=/var/log/tm_analysis.out.log
user=root

All looks good and both (lets call it services) are running. 

The problem is that i have to restart them everytime (using this command **/bin/bash /home/matecat/cattool/daemons/restartAnalysis.sh**) when i want to do something in matecat, for example i upload a file and press **Analyze**, nothing happens until i restart these services, analisis also do not finishes until i restart them, translation suggestions also do not work if i won't restart them. In conclusion: i have to restart these services every few minutes to make the matecat to work. What am i doing wrong here?

**Comment by Ostico** [comment]
Hi @MartynasSyn ,
did you already check the logs to see if there are some errors?
