### ISSUE TITLE
在执行matecat.sql时出现错误， matecat.sql没有创建表结构的语句

### ISSUE THREAD

**Issue by 951722070** [matecat/MateCat#1510]
非常感谢 matecat 项目.
matecat非常好.
有个问题希望咨询下， 万分感谢！！
在使用matecat安装matecat.sql时出现了错误:数据库表结构没有执行的sql语句,需要怎么解决呢？
source matecat.sql; 
error 1146 （42502）Table ‘matecat。engines’donesno't exist
error 1146 （42502）Table ‘matecat。engines’donesno't exist

**Comment by Ostico** [comment]
Sorry, this was an issue with our build system.

It is fixed now. Update MateCat sources and try again, reopen the issue if it is not fixed.
