### ISSUE TITLE
daemons: not a directory

### ISSUE THREAD

**Issue by LiuSandy** [matecat/MateCat#1516]
when I entry
`
cd ~/cattool/daemons
`
And then prompt me
`-su: cd: /home/matecat/cattool/daemons: not a directory`
Ubuntu version
`Linux version 4.4.0-21-generic (buildd@lgw01-21) (gcc version 5.3.1 20160413 (Ubuntu 5.3.1-14ubuntu2) ) #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016`
What should I do

**Comment by Ostico** [comment]
Hi @LiuSandy , do you cloned the repository? Git should create the symlink for this directory:

https://github.com/matecat/MateCat/blob/develop/daemons

Anyway, to fix, you can make the symlink manually.

**Comment by Ostico** [comment]
Plz reopen if this do not fix your issue.

**Comment by LiuSandy** [comment]
`cd ~/cattool/daemons` I actually saw it in the documentation，So I don‘t know how to do
