### ISSUE TITLE
Job TMX contains invalid TMX inner tags in <seg> element.

### ISSUE THREAD

**Issue by pepc** [matecat/MateCat#1526]
When a Matecat segment has tags, the TMX file exported with UI function **EXPORT JOB TMX** contains inner `<g>` elements in `<seg>` elements.

The `<g>` elements are not allowed in the TMX standard  (https://www.gala-global.org/tmx-14b#seg) in `<seg>` elements.

The `<g>` elements belong to XLIFF. Probably should be be mapped to corresponding tags in TMX ( `<bpt>`, `<ept>`, `<it>`, `<ph>`, and `<hi>`) or, alternatively, escape them with entities (i.e. `&lt.g&gt.`).

**Comment by Ostico** [comment]
Old. The issue is fixed.
