### ISSUE TITLE
Blank Page showing up after installaiton 

### ISSUE THREAD

**Issue by mohammedayub44** [matecat/MateCat#1528]
Hi,

I followed the advanced Manul Setup Page for spinning up a custom instance of Matecat. After performing all the steps and I get a blank page with the favicon. I'm replicating this on Ubuntu 16.04 on an amazon ec2 instance. 

More details: 
The output from the two screen sessions is as follows - 
![image](https://user-images.githubusercontent.com/7122670/61308433-3e28d900-a7be-11e9-92f0-f57748b0ba50.png)

Everytime I refresh the localhost on broswer I see this in the TM - 
![image](https://user-images.githubusercontent.com/7122670/61308485-5ef12e80-a7be-11e9-8409-13b6eda65bdd.png)

Node - i think this is running fine.
![image](https://user-images.githubusercontent.com/7122670/61308639-a8da1480-a7be-11e9-83be-d72f101084e4.png)

looping some folks here 
@Ostico @riccio82 

Any help appreciated. 
Thanks!

**Comment by cidrugHug8** [comment]
try it on chrome?

**Comment by Ostico** [comment]
Hi @mohammedayub44 from your first screenshot seems that a service is not running.

It is called fastAnalysis.

Check the logs: `fastAnalysis.log` and/or `fatal_errors.txt`

**Comment by Ostico** [comment]
Closed for inactivity.
