### ISSUE TITLE
Rename Ndebele to Ndebele South in supported_langs.json

### ISSUE THREAD

**Issue by twbtech** [matecat/MateCat#1557]
There are Northern and Southern variants of Ndebele, and the language code used in MateCat matches the southern variant. At TWB we prefer now to distinguish language variants having the same name by adding the variant "factor" at the end so that the variants appear next to each other in alphabetically ordered lists (à la "Chinese Traditional" and "Chinese Simplified"), hence "Ndebele South" rather than "Southern Ndebele"

**Comment by mauretto78** [comment]
@twbtech we renamed Ndebele to Ndebele South as you suggested, and added Northern Ndebele.

I close the issue, thanks for your suggestion.
