### ISSUE TITLE
Aws error? 

### ISSUE THREAD

**Issue by cristianursena** [matecat/MateCat#1573]
Hi. We succeded to get the new matecat up but now we have an error and i dont know how to fix it.

Client error: `GET http://169.254.169.254/latest/meta-data/iam/security-credentials/` resulted in a `404 Not Found` response: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> <html xml (truncated...)

We set the file system as FS in the config.ini as this error is related to aws i guess. Thank you

**Comment by Ostico** [comment]
Welcome, yes you're right. Let us know if you have more issues.

**Comment by cristianursena** [comment]
ok. I set that in Config.ini and i still get that error which is strange.

**Comment by Ostico** [comment]
Can you check in the logs please, we need more info.

**Comment by cristianursena** [comment]
LOG. txt
=============
{"log":{"token_hash":"uooibl7ok6ldk","context":{"ip":"46.97.196.101","class":"ProjectManager","function":"__construct","line":182},"time":1570531214,"date":"2019-10-08T12:40:14+02:00","content":[]}}
{"log":{"token_hash":"uooibl7ok6ldk","context":{"ip":"46.97.196.101","line":12},"time":1570531291,"date":"2019-10-08T12:41:31+02:00","content":"ajaxUtils::clearNotCompletedUploads : DirectoryIterator::__construct(\/home\/matecat\/cattool
{"log":{"token_hash":"uooibl7ok6ldk","context":{"ip":"46.97.196.101","class":"ProjectManager","function":"__construct","line":182},"time":1570531311,"date":"2019-10-08T12:41:51+02:00","content":[]}}
{"log":{"token_hash":"5d9c680c786c5","context":{"ip":"46.97.196.101","class":"controller","function":"readLoginInfo","line":194},"time":1570531340,"date":"2019-10-08T12:42:20+02:00","content":"User not logged."}}
{"log":{"token_hash":"rgr8dl161aj7u","context":{"ip":"46.97.196.101","class":"controller","function":"readLoginInfo","line":194},"time":1570531340,"date":"2019-10-08T12:42:20+02:00","content":"User not logged."}}
{"log":{"token_hash":"rgr8dl161aj7u","context":{"ip":"46.97.196.101","class":"newProjectController","function":"setOrGetGuid","line":168},"time":1570531340,"date":"2019-10-08T12:42:20+02:00","content":"{0B691E43-37C2-1991-DB2E-A775644819
{"log":{"token_hash":"rgr8dl161aj7u","context":{"ip":"46.97.196.101","class":"controller","function":"readLoginInfo","line":194},"time":1570531340,"date":"2019-10-08T12:42:20+02:00","content":"User not logged."}}
{"log":{"token_hash":"rgr8dl161aj7u","context":{"ip":"46.97.196.101","class":"controller","function":"readLoginInfo","line":194},"time":1570531353,"date":"2019-10-08T12:42:33+02:00","content":"User not logged."}}
{"log":{"token_hash":"rgr8dl161aj7u","context":{"ip":"46.97.196.101","class":"controller","function":"readLoginInfo","line":194},"time":1570531353,"date":"2019-10-08T12:42:33+02:00","content":"User not logged."}}
{"log":{"token_hash":"rgr8dl161aj7u","context":{"ip":"46.97.196.101","class":"controller","function":"readLoginInfo","line":194},"time":1570531354,"date":"2019-10-08T12:42:34+02:00","content":"User not logged."}}
{"log":{"token_hash":"rgr8dl161aj7u","context":{"ip":"46.97.196.101","class":"ProjectManager","function":"__construct","line":182},"time":1570531354,"date":"2019-10-08T12:42:34+02:00","content":[]}}
{"log":{"token_hash":"rgr8dl161aj7u","context":{"ip":"46.97.196.101","class":"controller","function":"readLoginInfo","line":194},"time":1570531354,"date":"2019-10-08T12:42:34+02:00","content":"User not logged."}}

Nothing in fatal.... 0

**Comment by Ostico** [comment]
This issue should be solved, can you confirm?
