### ISSUE TITLE
"Invalid Upload token" when uploading file

### ISSUE THREAD

**Issue by birduser** [matecat/MateCat#1575]
Hey there, I have a fresh install of Matecat, site is reachable but uploading a File results in "Invalid Upload Token" as seen in the screenshot. I've checked the error logs but couldn't get to the root of the issue. 
I've installed Matecat on a Debian 9 VM with Sury's php 5.6 packages, apache 2.x and the default jre/jdk. Is anyone having similar issues or knows where my error is coming from? For the installation I followed the advanced manual setup (which isn't 100% up to date imo) and have been getting this error as soon as I completed the installation. 
Screenshots:
![Dev_log](https://user-images.githubusercontent.com/35183090/66381635-fe871d00-e9b9-11e9-93a9-82638b06a1d6.jpg)
![Invalid_Upload_Token](https://user-images.githubusercontent.com/35183090/66381637-fe871d00-e9b9-11e9-8004-c1e1a7d24bb6.jpg)
![matecat_error_log](https://user-images.githubusercontent.com/35183090/66381638-fe871d00-e9b9-11e9-93ad-bb5c42f25897.jpg)

**Comment by cristianursena** [comment]
Hey. You have to setup the domain under cookie line [production] in the inc/config.ini .

**Comment by Ostico** [comment]
Hi @birduser ,
check your browser cookie settings, they must be enabled.
Moreover, check the permission on this file:` /home/matecat/cattool/inc/login_secret.dat  ` it must be readable by your web server.
Check the permissions on ` /home/matecat/cattool/storage/* ` all the directory should be writable by your web server.
Check if you active MQ instance is running, from your log it seems to be unreachable.

**Comment by Ostico** [comment]
Yes, @cristianursena your suggestion is also valid: 

> Hey. You have to setup the domain under cookie line [production] in the inc/config.ini .

**Comment by birduser** [comment]
Hey both thanks for your replies.
I have checked my browser cookie settings, they're enabled and I also set an explicit allowance for my site aswell.
I've checked permissions for both paths and they seem to be right. 

You where right activemq instance was not running, after starting it I still got the "Invalid upload token" error when uploading a file. It did get rid of the PHP Warning and the fatal error as seen in the error log screenshot. 
The PHP Notices are still there calling for an undefined index: upload_session (which is the name of the cookie afaik). 

My COOKIE_DOMAIN variable is set to http://lang.my-domain.com, does it require just the domain name?

**Comment by cristianursena** [comment]
Just the domain name

**Comment by birduser** [comment]
Thanks for explicitly mentioning the Production environment for the config.ini, that seems to have been my mistake combined with the inactive activemq service. 
Thank you guys!

**Comment by zarkerus** [comment]
@Winteriver I got the same problem today, can you tell me how did you solve this problem
My config.ini
```
ENV = "production"
CHECK_FS = no
[production]
CLI_HTTP_HOST = "https://my_real_domain.com"
COOKIE_DOMAIN = "my_real_domain.com"
ENABLE_MULTI_DOMAIN_API = no
DB_SERVER = "localhost"
DB_DATABASE = "matecat"
DB_USER = "matecat"
DB_PASS = "matecat01"
REDIS_SERVERS = "tcp://localhost:6379"
QUEUE_BROKER_ADDRESS = "tcp://localhost:61613"
QUEUE_DQF_ADDRESS = "tcp://localhost:61613"
QUEUE_JMX_ADDRESS = "http://localhost:8161"
QUEUE_CREDENTIALS = "admin:admin"
SSE_BASE_URL      = "my_real_domain.com/sse"
STORAGE_DIR = "/home/matecat/cattool/storage"
SMTP_HOST = 'localhost'
SMTP_PORT = '25'
SMTP_SENDER = 'no-reply@matecat.loc'
SMTP_HOSTNAME = 'localhost'
; Filters Configuration
FILTERS_ADDRESS = 'xxx'
FILTERS_MASHAPE_KEY = 'xxx'
; THIS SHOULD BE YOUR LEXIQA LICENSE, Request your license key at
; @see http://www.lexiqa.net
LXQ_LICENSE = false
LXQ_PARTNERID = false
FILE_STORAGE_METHOD = 'fs'
```
Permissions:
`/home/matecat/cattool/inc/login_secret.dat` 
```
-r--r--r-- 1 root    root      512 May 25 11:55 login_secret.dat
```

`/home/matecat/cattool/storage/*`
```
drwxrwxr-x   8 www-data matecat    4096 May 22 11:31 storage

> cd storage/
> ls -l
drwxrwxr-x  2 www-data matecat 4096 May 22 11:31 conversion_errors
drwxrwxr-x  7 www-data matecat 4096 May 25 12:33 files_storage
drwxrwxr-x  2 www-data matecat 4096 May 25 15:15 log_archive
drwxrwxr-x  2 www-data matecat 4096 May 22 11:31 reference_files
drwxrwxr-x  2 www-data matecat 4096 May 22 11:31 tmp_download
drwxrwxr-x 56 www-data matecat 4096 May 25 15:26 upload

> files_storage/
> ls -l
drwxrwxr-x 2 www-data matecat  4096 May 22 11:31 cache
drwxrwxr-x 2 www-data www-data 4096 May 25 12:33 fastAnalysis
drwxrwxr-x 2 www-data matecat  4096 May 22 11:31 files
drwxr-xr-x 2 www-data www-data 4096 May 25 12:33 originalZip
drwxrwxr-x 2 www-data www-data 4096 May 25 12:33 queueProjects

```

**Comment by Ostico** [comment]
Hi @zarkerus ,
your configurations seems ok.

Do you have cookie enabled? Your domain must be over SSL to work properly because of strict restrictions made by new browsers.

**Comment by zarkerus** [comment]
> cookie enabled

My site is serving over ssl - self signed certificate, https://cssdvn.com/, cookie enabled by default, but upload_session cookies is missing. 
```
PHP Stack trace:, referer: https://cssdvn.com/
PHP   1. {main}() /home/matecat/cattool/lib/Utils/fileupload/index.php:0, referer: https://cssdvn.com/
PHP   2. UploadHandler->post() /home/matecat/cattool/lib/Utils/fileupload/index.php:47, referer: https://cssdvn.com/
```
