### ISSUE TITLE
When upload new file to analyze we get this error

### ISSUE THREAD

**Issue by cristianursena** [matecat/MateCat#1576]
Internal Error: Failed to create/copy the file on disk from cache.

**Comment by Ostico** [comment]
This should help you:

Check the permissions on /home/matecat/cattool/storage/* all the directories should be writable by your web server.

**Comment by cristianursena** [comment]
storage is chown and chmod 
-R 777 www-data:www-data

**Comment by Ostico** [comment]
Any news?

**Comment by Ostico** [comment]
Closed for inactivity.
