### ISSUE TITLE
Rohingya TM not working

### ISSUE THREAD

**Issue by twbtech** [matecat/MateCat#1581]
Translations in Rohingya (rhg-MM) and Rohingyalish (rhl-MM) apparently aren't stored in MyMemory, and while it is possible to export the job TMX, the exported MyMemory TMs are empty for these locales, and trying to import the job TMX throws an Invalid TMX error. 
This problem may of course apply to other locales to.

**Comment by Ostico** [comment]
Hi @twbtech ,

The issue should be fixed now. 

Thank you.

**Comment by MLocria** [comment]
Hi @Ostico ,

Thanks for the follow-up. This is Manuel, from TWB. It's a pleasure to meet you.

I just tested this with a TMX or a glossary with Rohingya segments (the TMX was exported out of another project in MateCat) through MateCat's interface and couldn't upload them. Just to be safe, I also tested it in https://www.matecat.com/ and I got the same error (see screenshot attached)

Please, let me know if there's anything I can do on this side to help solve this.

Best.
![Screenshot from 2019-10-31 09-45-51](https://user-images.githubusercontent.com/51888982/67947824-449f5d00-fbc3-11e9-80e4-f58fee6b21c9.png)
