### ISSUE TITLE
Error: Server error, try again when adding files

### ISSUE THREAD

**Issue by olefimov** [matecat/MateCat#1589]
Hi,

Does anybody know what can be a reason for the above error when adding a file?
The file got uploaded (I can find it in the /Storage/Upload/{} folder.
Once the upload progress bar completed, Importing progress bar blinks for 1 second and the error is shown: "Error: Server error, try again" 

**matecat.error.log last line:**
PHP Notice:  Undefined offset: 0 in /home/matecat/cattool/lib/Utils/fileupload/upload.class.php on line 520,

fatal_errors.txt in /storage/log_archive
{"log":{"token_hash":"ellocf18k7d99","context":{"ip":"x.x.x.x","line":null},"time":1574612514,"date":"2019-11-24T17:21:54+01:00","content":{"error":"Client error: `GET http:\/\/y.y.y.y\/latest\/meta-data\/iam\/security-credentials\/` resulted in a `404 Not Found` response:\nnot found\n","trace":

Kind regards,
Oleg

**Comment by olefimov** [comment]
I've got through this step.
Now if I add the file it finishes downloading and importing progress starts. It stops when 2/3 of the progress bar completed, pauses for a couple of seconds and shows the error "Received status code 504".
php_errors.txt contains the following errors:
[26-Nov-2019 10:45:54 Europe/Rome] PHP Notice:  Undefined index: id in /home/matecat/cattool/lib/Utils/Filters.php on line 226
[26-Nov-2019 10:45:54 Europe/Rome] PHP Notice:  Undefined index: password in /home/matecat/cattool/lib/Utils/Filters.php on line 227
[26-Nov-2019 10:45:54 Europe/Rome] PHP Notice:  Undefined index: owner in /home/matecat/cattool/lib/Utils/Filters.php on line 228

Looks like something gets wrong during file conversation.
Any ideas?

**Comment by Ostico** [comment]
Hi @olefimov 
is this an issue refferred to https://github.com/matecat/MateCat/issues/1599 or a different one?

**Comment by vinayaksharmagh** [comment]
I am also facing the same issue. Please help

**Comment by vinayaksharmagh** [comment]
Is it possibly because of Filters setting in conf.ini?
In my case filter settings are
; Filters Configuration
FILTERS_ADDRESS = 'xxx'
FILTERS_MASHAPE_KEY = 'xxx'

**Comment by Ostico** [comment]
Filters must be enabled and valid. 
Otherwise you can disable them, but you will can use only xliff files.
Otherwise you have to use rapid api by opening an account and setting configurations or install your own filters locally.

**Comment by vinayaksharmagh** [comment]
Ok that clears it up. Thanks!
