### ISSUE TITLE
File not found. Failed to save XLIFF conversion on disk.

### ISSUE THREAD

**Issue by zyc945** [matecat/MateCat#1598]
try to run matecat on my server. when i  upload a string file and click the analyze button, it show "File not found. Failed to save XLIFF conversion on disk."

what should I do to fix this error.
/home/matecat/cattool/storage is already chmod to 777. no error found in log_archive/.

**Comment by 2i18ns** [comment]
I solve this problem by switch off the s3 version control, 
so this issue closed.

**Comment by zyc945** [comment]
I solve this issue by switch off the s3 version control.

so I closed this issue.
