### ISSUE TITLE
Not Authorized error in 2-3 seconds after pressing Analyze button

### ISSUE THREAD

**Issue by olefimov** [matecat/MateCat#1599]
"Not Authorized" red background error message shows up in 2-3 minutes after Analyze button is pressed.
Could someone please advise where to look fro a root cause?

**Comment by dark-viking** [comment]
Having the same issue. But I've encountered it just recently.

**Comment by xtotdam** [comment]
Same here, right after trying to upload a .txt file

**Comment by dark-viking** [comment]
Reply from their support: "There is an open bug that's affecting files with a Cyrillic filenames. A viable workaround is create a brand new docx document, then copy paste the content of this file therein and upload it."
Tried this solution - it worked.
Can you guys also try it?

**Comment by xtotdam** [comment]
Thank you, it worked, I tried it right now.
Yesterday I was trying to upload a file with cyrillic filename as well, though I think that after that I tried to upload '42.txt' and it was rejected.
I may be wrong though

**Comment by Ostico** [comment]
Hi all,

the issue should be fixed.
