### ISSUE TITLE
Copy source to target all new segments doesn't work

### ISSUE THREAD

**Issue by amorimferreira** [matecat/MateCat#1619]
Hey, guys!

I've been trying to copy all source segments to target but after loading for a while it just triggers an error warning and goes back to default. Any idea?

![image](https://user-images.githubusercontent.com/36452265/72270138-98dfa800-361c-11ea-871d-d0ab9d5147ec.png)

![image](https://user-images.githubusercontent.com/36452265/72270045-78afe900-361c-11ea-85d4-8ab6d70a32b7.png)

**Comment by Ostico** [comment]
Hi @amorimferreira ,

thank you for your report. We found a big performance issue which do not allow to perform the operation when the project is big.
We will fix this behaviour in next releases.

**Comment by amorimferreira** [comment]
Hey, @Ostico 

Thank you!

**Comment by Ostico** [comment]
@amorimferreira this issue should be fixed now with the lastest releases.
