### ISSUE TITLE
MyMemory Connection issue

### ISSUE THREAD

**Issue by edit-farkas** [matecat/MateCat#1626]
We have installed MateCat based on advanced installation manual. We succeed opening a job, at which point we are receiving the attached error related to the translation lookup and receiving a fatal error too (see both attached). May this be bug? Or is there more to configure? 
![Translation_Matches_error_2020-01-22](https://user-images.githubusercontent.com/60193672/72924286-f24c8300-3d50-11ea-8aa4-eda332419ed3.png)
[Matecat_fata_error_21_Jan_20.txt](https://github.com/matecat/MateCat/files/4099322/Matecat_fata_error_21_Jan_20.txt)

We would like to use the MyMemory lookup. Please advice.

**Comment by Ostico** [comment]
Hi @edit-farkas ,

from which i can understand from your exception, you have not configured properly the file ` ./inc/task_manager_config.ini `

**Comment by Ostico** [comment]
Closed for inactivity.
