### ISSUE TITLE
Uncaught StompException

### ISSUE THREAD

**Issue by cidrugHug8** [matecat/MateCat#1634]
Hi there.

I manually installed MateCat and got 500 error on chrome.
The log on apache2 is as follows:

[Thu Feb 06 11:27:18.483711 2020] [php7:error] [pid 1355] [client xxx.xxx.xxx.xxx:51127] PHP Fatal error:  Uncaught StompException: Could not connect to localhost:61613 (10/10) in /home/matecat/cattool/lib/Utils/Stomp.php:169\nStack trace:\n#0 /home/matecat/cattool/lib/Utils/Stomp.php(194): Stomp->_makeConnection()\n#1 /home/matecat/cattool/lib/Utils/AMQHandler.php(111): Stomp->connect()\n#2 /home/matecat/cattool/lib/Utils/WorkerClient.php(69): AMQHandler->send('mail_queue', Object(TaskRunner\\Commons\\QueueElement), Array)\n#3 /home/matecat/cattool/lib/Utils/Utils.php(343): WorkerClient::enqueue('MAIL', '\\\\AsyncTasks\\\\Wor...', Array, Array)\n#4 /home/matecat/cattool/inc/Bootstrap.php(274): Utils::sendErrMailReport('#0  Bootstrap::...')\n#5 [internal function]: Bootstrap::shutdownFunctionHandler()\n#6 {main}\n  thrown in /home/matecat/cattool/lib/Utils/Stomp.php on line 169

```
root@matecat-server:/etc/default/activemq/conf# netstat -an | grep 61613 | grep LISTEN
tcp6       0      0 :::61613                :::*                    LISTEN     
```
Could you give me some advice?

**Comment by cidrugHug8** [comment]
no support?

**Comment by Ostico** [comment]
In  my opinion, the configuration is not correct.
Check in ./inc/config.ini

**Comment by cidrugHug8** [comment]
Thanks for your reply.
I configured postfix on ubuntu 18.04.
The error disappeared, but the blank screen is still showing...
