### ISSUE TITLE
where is conversion_enabled?

### ISSUE THREAD

**Issue by cidrugHug8** [matecat/MateCat#1638]
Hi there,

I found the following message in /home/matecat/cattool/storage/log_archive/fatal_errors.txt

> {"log":{"token_hash":"5e43b7c791fef","context":{"ip":"xxx.xxx.xxx.xx","line":null},"time":1581496263,"date":"2020-02-12T09:31:03+01:00","content":{"error":"Unable to find variable 'conversion_enabled' in current scope","trace":[{"file":"\/home\/matecat\/cattool\/inc\/PHPTAL\/PHPTAL.php(841) : eval()'d code","line":38,"function":"__get","class":"PHPTAL_Context","type":"->","args":["conversion_enabled"]},{"file":"\/home\/matecat\/cattool\/inc\/PHPTAL\/PHPTAL.php","line":667,"function":"tpl_5e3bd3d7_upload__vfdz2zfVNnYDrGSzzm6OwQ","args":[{},{"repeat":{},"_xmlDeclaration":null,"_docType":"<!DOCTYPE html>","basepath":"\/","hostpath":"http:\/\/localhost","build_number":"2.9.8","use_compiled_assets":false,"supportedBrowser":-2,"platform":"linux","enabledBrowsers":["applewebkit","chrome","safari"],"maxFileSize":62914560,"maxTMXFileSize":314572800,"dqf_enabled":false,"analysis_enabled":true,"footer_js":[],"config_js":[],"css_resources":[]}]},{"file":"\/home\/matecat\/cattool\/lib\/Controller\/AbstractControllers\/viewController.php","line":141,"function":"execute","class":"PHPTAL","type":"->","args":[]},{"file":"\/home\/matecat\/cattool\/index.php","line":17,"function":"finalize","class":"viewController","type":"->","args":[]}]}}}

Should I set conversion_enabled? Where?

Thank you.

**Comment by Ostico** [comment]
@cidrugHug8 have you removed the ` FILTERS_ADDRESS ` directive in your ` config.ini `?

**Comment by cidrugHug8** [comment]
@Ostico hmm, although FILTERS_ADDRESS was removed then matecat doesn't start.
Ubuntu 18.04 is supported?

**Comment by Ostico** [comment]
@cidrugHug8 yes of course ubuntu 18 is supported, which version of php do you installed, at moment  5.4 < PHP < 5.6 is supported. Anyway, you solved the issue?

**Comment by LukasSaz** [comment]
I'm facing the same issue with php `5.6.14`. Log's also outputted same error but for different variable `pageTitle`:

> {"log":{"token_hash":"5e988b6f43d8e","context":{"ip":"172.19.0.1","line":null},"time":1587055471,"date":"2020-04-16T18:44:31+02:00","content":{"error":"Unable to find variable 'pageTitle' in current scope","trace":[{"file":"\/tmp\/tpl_5e92ce5e_index__OHwrg5B0ABHxBZVq26aDTA.php","line":18,"function":"__get","class":"PHPTAL_Context","type":"->","args":["pageTitle"]},{"file":"\/var\/www\/html\/inc\/PHPTAL\/PHPTAL.php","line":667,"function":"tpl_5e92ce5e_index__OHwrg5B0ABHxBZVq26aDTA","args":[{},{"repeat":{},"_xmlDeclaration":null,"_docType":"<!DOCTYPE html>","basepath":"\/","hostpath":"http:\/\/localhost","build_number":"2.14.18","use_compiled_assets":false,"supportedBrowser":1,"platform":"linux","enabledBrowsers":["applewebkit","chrome","safari"],"maxFileSize":62914560,"maxTMXFileSize":314572800,"dqf_enabled":false,"analysis_enabled":true,"footer_js":[],"config_js":[],"css_resources":[]}]},{"file":"\/var\/www\/html\/lib\/Controller\/AbstractControllers\/viewController.php","line":141,"function":"execute","class":"PHPTAL","type":"->","args":[]},{"file":"\/var\/www\/html\/index.php","line":17,"function":"finalize","class":"viewController","type":"->","args":[]}]}}}

**Comment by KamilChlodek** [comment]
I have the same problem as @LukasSaz and @cidrugHug8 . Have you guys found a solution to this problem? Does anyone know how to resolve this?

**Comment by Ostico** [comment]
Hi all, we found that this issue could be related to the (non-)existence of a file in the **`./inc/`** ( config ) folder.
Please be sure that this file exists:
**`oauth_config.ini`**

**Comment by KamilChlodek** [comment]
> Hi all, we found that this issue could be related to the (non-)existence of a file in the **`./inc/`** ( config ) folder.
> Please be sure that this file exists:
> **`oauth_config.ini`**

Thanks, that did the trick.

**Comment by Ostico** [comment]
Perfect. Thank you.
