### ISSUE TITLE
MateCat quality report API endpoint seems to have bugs

### ISSUE THREAD

**Issue by dsorato** [matecat/MateCat#1640]
Hello,
I need to download the quality report information though the MateCat API for my application. However it is not working, apparently for projects that are not revised yet. I have 3 distinct projects, two revised and one not revised. The API retrieves the QA report data nicely for the two projects already revised but for the other one although the translations are there, the response looks like this:
{"quality-report":{"chunk":{"files":[],"avg_time_to_edit":24.86,"avg_edit_distance":0,"review":{"percentage":0,"is_pass":true,"score":"0.00","reviewer_name":""}},"job":{"source":"en-US","target":"ru-RU"},"project":{"metadata":{"features":"translation_versions,review_extended,second_pass_review","lexiqa":"1","speech2text":"0","tag_projection":"0"},"id":"2732933","created_at":"2020-02-17T12:06:27+01:00"}}}

Could you check what is happening? Or include back a way of downloading the editing log?

Kind regards,
Danielly

**Comment by riccio82** [comment]
Thanks @dsorato for the report, we'll try to fix it as soon as possible.

**Comment by Ostico** [comment]
Should be fixed.
