### ISSUE TITLE
Blank Page error 500

### ISSUE THREAD

**Issue by virusbear** [matecat/MateCat#1672]
In the course of the last days, I finally managed to get an installation running using the advanced setup manual. Now the only thing that is left is to get the front end running. 
The API seems to work fine and I can call every available endpoint (getting 401 because I have not yet logged in). 
My problem with the frontend is that it only shows the matecat favicon with a blank page. Looking at the dev tools of Firefox a 500 Internal server error is returned by matecat. 
Analyzing the logs did not bring me very far. 

The matecat.log file in /var/log/apache2 only shows a request from localhost which returned a 500. No further information. 
matecat.error.log shows a StomException. But this one was resolved by simply restarting the activemq service.

Attached are all the logs I could find to search for the problem.
[apache2 logs.zip](https://github.com/matecat/MateCat/files/4407454/apache2.logs.zip)
[log_archive.zip](https://github.com/matecat/MateCat/files/4407455/log_archive.zip)

EDIT:
===

There is also this file:
![image](https://user-images.githubusercontent.com/23473248/78000570-c93e0500-7334-11ea-8dac-bb53036710b5.png)
which seems to be created by matecat but without the correct permissions to be able to read it. 
It seems to be read in Bootstrap.php on line 129 as the following entry in the php_errors.txt shows:

`[31-Mar-2020 08:41:48 Europe/Rome] PHP Warning:  file_get_contents(/home/matecat/cattool/inc/login_secret.dat): failed to open stream: Permission denied in /home/matecat/cattool/inc/Bootstrap.php on line 129`

**Comment by Ostico** [comment]
Thank you we are planning to update the manual setup.
