### ISSUE TITLE
Wrong (LTR) alignment in an Arabic PPTX file

### ISSUE THREAD

**Issue by mzeidhassan** [matecat/MateCat#1685]
Hi MateCat team,

I am translating a Covid19-related PPTX file using MateCat online. Unfortunately, the target Arabic PPTX file is not aligned correctly to match the -right-to-left nature of Arabic. Although on your website, it says:

"Full support for right to left languages
MateCat now fully supports right to left (RTL) languages both as source and target languages.

We’ve been testing and verifying hundreds of files translated into Arabic, Hebrew, Persian and we find the results encouraging: files can be successfully translated with no layout issues."

Are you aware of this? Do you have a workaround to get this fixed?

Here is a screen shot of how it looks like at my end (note, I was just testing, so translation quality is not good):
![image](https://user-images.githubusercontent.com/7589948/79004250-9c96a400-7b11-11ea-823f-607f85f7bafe.png)

Thanks in advance for your support.

Kind regards,
Mohamed

**Comment by Ostico** [comment]
Thank you, this seems a bug. It is related to the conversion filters.

**Comment by mzeidhassan** [comment]
Thanks @Ostico for your reply. I hope you will be able to get this one fixed soon. By the way, I filed a bug for Okapi team as well.

https://bitbucket.org/okapiframework/okapi/issues/927/pptx-and-rtl
