### ISSUE TITLE
Wrong grunt version

### ISSUE THREAD

**Issue by LukasSaz** [matecat/MateCat#1690]
Hi guys,
Grunt has released a new minor version `1.3.0` and the `package.json` specifies `"grunt": "^1.0.4",` which means the new version will be installed.  This produces following error:
```
/var/www/html/support_scripts/grunt/node_modules/grunt/node_modules/mkdirp/lib/opts-arg.js:7
    opts = { mode: 0o777, fs, ...opts }

SyntaxError: Unexpected token ...
```
Grunt should be updated to only include patch versions: `"grunt": "~1.0.4",`

**Comment by Ostico** [comment]
Thank you, we will investigate.

**Comment by riccio82** [comment]
Hi @LukasSaz,

Can you better specify the error you have and the version you installed?

I'm currently using this version of grunt:
```
grunt v1.1.0  
```
This is the last version and should work also for you (https://github.com/gruntjs/grunt/releases).

This `"grunt": "~1.0.4"` means [“Compatible with version” ](https://docs.npmjs.com/files/package.json#dependencies)

**Comment by LukasSaz** [comment]
Hi @riccio82, sorry my mistake. I was talking about `grunt v.1.1.0` .  Sadly I can no longer reproduce this issue as I've switched set ups. Though still beware `"grunt": "~1.0.4"`  installs the latest version.

**Comment by riccio82** [comment]
Ok, I hope you've solved it. If you need help, feel free to write.

> Though still beware "grunt": "~1.0.4" installs the latest version.

Yes I know, for this we have` "grunt": "**^**1.0.4"` in the packege.json
