### ISSUE TITLE
Auto-Propagation does not work properly on currently displayed items, causes usability problems

### ISSUE THREAD

**Issue by felixvd** [matecat/MateCat#17]
I am revising a job with many identical segments grouped together, which causes some irritating and inconvenient behavior that costs a lot of time. One of the main issues is the fact that auto-propagating does not seem to affect the segments currently on screen. 

For example, if I make a change to the first group of 6 identical segments and press Cmd+Enter, the Auto-Propagation dialogue pops up, but confirming it will not change the status of the other 5 segments that are visible then. Not only that, but it will also continue on to the second of the six segments and effectively prompt for the same work that has been done on the previous segment, which is at best a waste of time, at worst a source of errors.

If I approve the first in a line of identical segments, the rest will not be automatically approved or skipped, and Cmd+Enter prompts for a response to each of them. Only segments loaded from the server at the end of the current pre-loaded segments are marked as approved. When clicking on the progress bar to skip to the next new segment, the already-approved-but-not segments are usually selected 1 or 2 times before it is registered that they are not new. This might be the same or a related issue, or due to something else.

Either way, all this makes working on this kind of job extremely time-intensive and sluggish, and can trip up users if they are not careful. It would be great if this was fixed.

**Comment by antoniofarina** [comment]
This is a known bug that affect the revise page and that we have fixed in the development stage.
It will be  pushed in the next release (end of this week).
In the meanwhile, you can accept the autopropagation and then refresh the page

**Comment by felixvd** [comment]
Great to hear.

Come to think of it, refreshing the page can make you lose changes that have not been transmitted to the server yet. Maybe it's worth asking for confirmation to leave the page unless there is nothing to be sent in the queue?

**Comment by felixvd** [comment]
I have noticed that at least on beta.matecat.com this works a lot better now, but the segments are only updated upon response from the server. Identical segments often follow one another, however, and the second identical segments is still opened. Could "Auto-Propagate" also search locally for the next segment that is not identical, to avoid this behavior?

**Comment by felixvd** [comment]
I took a video to showcase what I described in the comment above. The connection was exceptionally good so the wait time was low, but these segments should definitely be skipped over by the client locally.

https://www.youtube.com/watch?v=XXy4bFks0BQ
