### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by kumaramit23** [matecat/MateCat#1733]
Hello Team,

I have installed matecat 5 times. but at the end i stuck at blank page. can you please help in that

**Comment by Ostico** [comment]
Hi we are working in a new manual install documentation since the existent is old.
Can you check this?

https://github.com/matecat/MateCat/issues/1672

**Comment by kumaramit23** [comment]
Thanks for your support, when we can get that ??

**Comment by Ostico** [comment]
It should be crated automatically by MateCat at first start, but if the owner/group are `matecat:matecat` and the web server ( Apache ) run as `www-data:www-data` it is not readable. try to change it's ownership to  `www-data:www-data`

**Comment by kumaramit23** [comment]
I have applied same permission. but still its same.

**Comment by Ostico** [comment]
Hi @kumaramit23 this user had the same issue:
https://github.com/matecat/MateCat/issues/1736

**Comment by Ostico** [comment]
Closed for inactivity.
