### ISSUE TITLE
Localhost unable to handle request

### ISSUE THREAD

**Issue by harsh-oodles** [matecat/MateCat#1736]
Hi There, 

I have tried installing the setup more than 10 times using the Advance Manual setup guide. I see that it's old and you are working on updating it. 

I have sorted out most of the issues regarding the permissions and PHP packages. Still, I am unable to see the setup loading successfully. I checked for the error logs of my server and under storage/log_archive. Everything is fine and not showing any error or warning logs. 

I read one of your comments and I checked the fast fastAnalysis.log file and I am getting this error

`{"log":{"token_hash":"5edd1f0a2149a","context":{"ip":"127.0.1.1","class":"Analysis\\Workers\\FastAnalysis","function":"main","line":139},"time":1591550036,"date":"2020-06-07T19:13:56+02:00","content":"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'j.only_private_tm' in 'field list' - Error again. Try to reconnect in next cycle."}}`

These are the screens running currently on my system

```
	21726.tm	 (Sunday 07 June 2020 09:04:56  IST)	(Detached)
	21723.fast	(Sunday 07 June 2020 09:04:56  IST)	(Detached)
	1085.node	(Sunday 07 June 2020 10:21:09  IST)	(Detached)

```

Please @Ostico let me know what I am doing wrong here. I see it is related to SQL but not sure what is wrong here.

**Comment by Ostico** [comment]
HI @harsh-oodles , yes it seems something related with the database schema.
Since the field you mention is one of the oldest ones i suppose that your mysql database in not in place.

Try to setup mysql database again from this schema:
https://github.com/matecat/MateCat/blob/develop/INSTALL/matecat.sql

**Comment by harsh-oodles** [comment]
After updating the database I am getting this

`Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'matecat.j.id_tms' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by`

I have disabled the `only_full_group_by mod` from the sql.

Also, I am getting this in fatal_error.txt file 

`Unable to find variable 'conversion_enabled' in current scope`

Please let me know what I am missing. Should I start from scratch again.

**Comment by Ostico** [comment]
Hi @harsh-oodles ,

can you check if there is a file called  `oauth_config.ini`in the ./inc directory of MateCat?

If there is not please run this command:
`cp oauth_config.ini.sample oauth_config.ini`

**Comment by harsh-oodles** [comment]
Yes, the file was not there, I ran the command and it worked like a charm. Now the blank page is removed and I can see the Matecat Translation Panel. Thank you so much.

I tried uploading a file and getting this error, 

`Error: Invalid Upload Token. Check your browser, cookies must be enabled for this domain.`

Also, in the fast analysis logs, it is still showing 

`{"log":{"token_hash":"5edf1d0716cf0","context":{"ip":"127.0.1.1","class":"Analysis\\Workers\\FastAnalysis","function":"main","line":139},"time":1591690474,"date":"2020-06-09T10:14:34+02:00","content":"SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'matecat.j.id_tms' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by - Error again. Try to reconnect in next cycle."}} `

**Comment by Ostico** [comment]
@harsh-oodles mysql must start with those SQL_MODES:
```
#my.cnf
sql-mode="NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
```

**Comment by harsh-oodles** [comment]
Hi Ostico, 

I am getting this error. I didn't change anything. On loading page, it says this in apache error log 

`PHP Catchable fatal error:  Argument 1 passed to FeatureSet::loadForProject() must be an instance of Projects_ProjectStruct, boolean given, called in /var/www/html/php/Transleqo-Language-Translation/lib/Controller/catController.php on line 133 and defined in /var/www/html/php/Transleqo-Language-Translation/lib/Model/FeatureSet.php on line 42`

**Comment by Ostico** [comment]
Hi @harsh-oodles which version of matecat are you using? this line do not contains any reference to your error:
https://github.com/matecat/MateCat/blob/develop/lib/Controller/catController.php#L133

**Comment by Ostico** [comment]
Old. Closed for inactivity.
