### ISSUE TITLE
The analysis seems not to be running. Contact the owner of this Matecat instance.

### ISSUE THREAD

**Issue by Akashporia7** [matecat/MateCat#1753]
Hi Team

I have setup the matecat codebase on my system. I am able to upload the docx file but when I press the analyze button. I go to the next screen where I get this message "The analysis seems not to be running. Contact the owner of this matecat instance".

Do we need to setup Google Oauth to use Analysis functionality?

Please look into the issue as soon as possible and let me know if you need anything.

**Comment by Ostico** [comment]
Hi @Akashporia7 you should start background daemon processes.

Copy the file `inc/task_manager_config.ini.sample` to `inc/task_manager_config.ini`
and run `/bin/bash /home/matecat/cattool/daemons/restartAnalysis.sh`

**Comment by Akashporia7** [comment]
Hi @Ostico 

I have already copied the file inc/task_manager_config.ini.sample to inc/task_manager_config.ini.

On running the below command, I am getting this.

![image](https://user-images.githubusercontent.com/62101069/85131493-8b29f080-b254-11ea-9324-98e462c6d33c.png)

**Comment by Ostico** [comment]
Maybe your daemons folder is not a symbolic link but an hard link or a real directory.
It should be a symlink to `lib/Utils/Analysis/`
https://github.com/matecat/MateCat/blob/master/daemons

**Comment by Akashporia7** [comment]
Can you please share the steps to get it done.

**Comment by meenakshi074** [comment]
![Screenshot from 2020-06-20 14-02-39](https://user-images.githubusercontent.com/60773852/85199186-3301f580-b30b-11ea-946d-7802074a0662.png)

File is not translated showing this popup "refresh the page and clear the cache". Any solution?

**Comment by Ostico** [comment]
You should see in your logs to get more info.

**Comment by Ostico** [comment]
Old. Closed for inactivity.
