### ISSUE TITLE
bug in fixFileName function?

### ISSUE THREAD

**Issue by cericoda** [matecat/MateCat#1755]
in develop branch,

./lib/Utils/API/Upload.php

I got an error with an install when I tried to "import TMX" from settings and upload a file.

/home/matecat/cattool/storage/log_archive/php_errors.txt

[19-Jun-2020 18:34:43 Europe/Rome] PHP Deprecated:  Non-static method Upload::fixFileName() should not be called statically in /home/matecat/cattool/l
ib/Controller/loadTMXController.php on line 150
[19-Jun-2020 18:34:43 Europe/Rome] PHP Fatal error:  Uncaught Error: Using $this when not in object context in /home/matecat/cattool/lib/Utils/API/Upl
oad.php:277
Stack trace:
#0 /home/matecat/cattool/lib/Controller/loadTMXController.php(150): Upload::fixFileName('Obfunet - EN-D...')
#1 /home/matecat/cattool/index.php(12): loadTMXController->doAction()
#2 {main}
  thrown in /home/matecat/cattool/lib/Utils/API/Upload.php on line 277

It works fine when uploading from the main "home" page..

**Comment by Ostico** [comment]
Thank you, which version of PHP are you using?

**Comment by cericoda** [comment]
Hi, I used the Bionic system provided php 7.2.

**Comment by Ostico** [comment]
Php 7.2 is more strict about using static calls on public call methods. This works on php 5.6.x

**Comment by cericoda** [comment]
OK but 5.6 is long EOL, and also this issue was introduced recently as a previous version of this file actually worked for PHP 7.0 as I have an install with no complaints.

While I have you here, is there a recommended source for PHP 5.6 as I didn't find one, everyone seems to have moved on..

**Comment by Ostico** [comment]
In Ubuntu you can use:
```
add-apt-repository ppa:ondrej/php
add-apt-repository ppa:ondrej/apache2
apt-get update
apt-get -y --fix-missing install apache2 apache2-dev libapache2-mod-php5.6 \
    php5.6 php5.6-json php5.6-curl php5.6-xdebug php5.6-mysql php5.6-xml php5.6-mbstring php5.6-dev php5.6-mcrypt php5.6-redis \
    php5.6-zip mysql-client libzip-dev
```
