### ISSUE TITLE
Payable words count for new language is not reduced.

### ISSUE THREAD

**Issue by meenakshi074** [matecat/MateCat#1763]
Hi Team,

I have selected the new language for translation but for the first time it does not translate anything. So i have translated by my own and save it. So basically translations should by saved in my memory Api. On another time translation that should be saved in my memory Api should reduced the word count for payable but in my case it does not reduced the payable word count.

Also we don't want to use private TM.

Please look into the issue as soon as possible and let me know if you need anything.

**Comment by Ostico** [comment]
Hi @meenakshi074 , for this kind of issues please contact support@matecat.com
