### ISSUE TITLE
Need to know How file uploading works.

### ISSUE THREAD

**Issue by ravioodles** [matecat/MateCat#1764]
Hi, I am a developer and had a project set up on my local system with your June 2017 code. And it is supporting, uploading, and translating the docx and doc file formates only and I have to add pdf file formate to it so please can you guide me in code from where I can change and able to get pdf file uploading working.

Thanks and regards

**Comment by ravioodles** [comment]
Currently when i am adding pdf file it shows 

Received status code 400

**Comment by Ostico** [comment]
Sorry, it is not possible to convert pdf files unless you pay for
matecat-filters through rapidapi

Il lun 29 giu 2020, 10:18 ravioodles <notifications@github.com> ha scritto:

**Comment by ravioodles** [comment]
Ok how much we have to pay for all filters to support all file formats like (pdf, png, etc) in our existing project? And after adding these paid filters does the pdf file uploading, analysis, and translation all functionality works properly? And does we also get support from your side on how to add those filters and know how they work?

**Comment by Ostico** [comment]
Please contact support@matecat.com
