### ISSUE TITLE
translations stopped working

### ISSUE THREAD

**Issue by cericoda** [matecat/MateCat#1781]
Hi the system has been working but last week stopped working when clicking 'translate' - just get a spinning wheel. I thought this may have been caused by running out of disk space which happened shortly afterwards but having restored to an earlier system snapshot it seems to be the same problem.

I had a look at translated.net and it appears that the endpoints have changed, e.g. old call:

https://api.mymemory.translated.net/glossary/get

new

https://api.mymemory.translated.net/get

And the old format doesn't seem to work. But that doesn't seem right.. I'm not sure where to go.

I am running on PHP7 but I don't see how that could have caused this issue to just appear last week.

Any tips could be handy, thanks!

**Comment by cericoda** [comment]
Hi, So I raised an enquiry for enterprise support at the same time as I raised this, but have no reply from them yet. I have reverted to 5.6, updated to latest and the problem persists.

Could really use some help here...!

sample entry in /home/matecat/cattool/storage/log_archive/log.txt:

date":"2020-08-07T12:14:47+02:00",
"content":
{"timing":
{"Total Time":0.074787,
"Connect Time":0.020756,
"Pre-Transfer Time":0.020868,
"Start Transfer Time":0.02087,
"Transfer Time":"53917\u03bcs"},
"resource_hash":"5f2d2997dca952.25545756",
"url":"http:\/\/api.mymemory.translated.net\/glossary\/get",
"options":{"
post_parameters":
{"q":"Der Hersteller muss die folgende Anforderung beachten:",
"langpair":"de-DE|en-GB",
"de":"demo@matecat.com",
"mt":"",
"numres":"100",
"k
ey":"458edf9cfa1110cc96b8"}},
"response":{
"responseData":
{"translatedText":null,
"match":null},
"quotaFinished":false,
"mtLangSupported":false,
"responseDetai
ls":"",
"responseStatus":200,
"responderId":"91",
"exception_code":null,
"matches":[]
}}}}

**Comment by Ostico** [comment]
Hi @cericoda ,
The api https://api.mymemory.translated.net/glossary/get is still working, so I think this is not the cause of your issue.
The empty response I think is dued by the fact that you have no glossary entries in your MyMemory api key.

**Comment by cericoda** [comment]
Hi 

Thank you. 

The issue turned out to have been caused by SSE_BASE_URL in ./inc/config.ini

It had been working but just suddenly stopped working. replacing the localhost reference got it going again. Strangely this is still unchanged in the still-working non-public-facing version running an older version over http.

by the way, I also never did get a reply from my enterprise query.
