### ISSUE TITLE
Suggestion: a bulk approve function during revision

### ISSUE THREAD

**Issue by felixvd** [matecat/MateCat#18]
Opening segments during revision takes a non-negligible amount of time, especially on older machines. There are sections that would be very quick to scan and review, but opening each segment and waiting for the auto-scroll to finish makes those take a disproportionately long time in Matecat.

Options to "Approve the next X segments" and "Approve segments from X to Y" would be extremely helpful, and the next best thing outside of a proper selection mechanism. A "Yes, auto-propagate all those approvals" checkmark would be good, too. 

I would be glad to see somehing like this - it would at the very least save me a few hours.

**Comment by antoniofarina** [comment]
I think this could be dangerous for the accuracy and the quality of the revision.
To make sure that the translator explicitly access each segment and approve it is a guarantee for the customer.

**Comment by felixvd** [comment]
While I understand your concern, I think you are putting the horse before the cart. Let me try to be short:

1) Slowing down your reviewers is not a way to assure quality. It only serves to make your program less useful. Remember that your translators' job is to assure a good translation, not to approve segments inside a program. Matecat should provide the tools they need to do that job.

2) Older computers are effectively locked out of Matecat for big jobs, even if translators want to use it. This makes your reviews worse and more error-prone, as your translators cannot benefit from its powerful features.

3) This is not a hypothetical problem. I have had to ask project managers to accept jobs that are not approved 100% within Matecat because my computers are too slow to approve the massive amount of segments in a reasonable time frame. Another review job that I had to re-review had only about 25% of it approved when I received it - most likely for the same reason.

Before you judge this feature, I would kindly suggest that you ask around if this is an issue for other reviewers, and include that in your decision-making.

Finally, if you still think that it is too risky from a QA standpoint, consider disabling the function in the project settings, so that it can be used where it is needed. I would be glad to discuss a pertinent example via email.

**Comment by felixvd** [comment]
I get the impression that you underestimate how much the interface affects review speed. I recorded a screencast to give you a better impression: https://www.youtube.com/watch?v=yiQl2pvmcak

In it, I am doing the actual revision of the segments from 0:00 to 0:36. Afterwards, I spend 2 full minutes approving the segments I have just read. Note that approving the segments one by one causes lagging and scrolling, during which I cannot read the text.

As a reviewer, I need to be fast, and this is a serious problem. It is not the responsibility of the CAT tool to ensure that I do my job, it's mine. Please do not ignore a useful feature because of this misconception.

**Comment by felixvd** [comment]
I could go on about why I believe the decision not to implement this feature is fundamentally misguided (users lose focus when they are forced to wait on UI, it is not quality assurance to restrict usage of a productivity tool etc.), but you can discuss this internally.

All I want to add is that my last job contained a stretch of over **1500** segments that were almost exclusively model numbers and measurements. 1437 of the segments' translations were unchanged from the source, and 1150 were unique entries. Manually approving these would have easily taken 1-2 hours, while checking them by eye took less than 10 minutes. I do not have that kind of time to waste. 

In case anyone else is in a similar situation and finds this issue unfixed, I'm posting [this bulk-approving script][1] I had to use to preserve my sanity and actually get my work done.

[1]:https://github.com/hsperr/mercat_bulk_approve/

**Comment by alessandrocattelan** [comment]
Hi Felix,

I've watched your screencast, very useful, thanks.

I agree with you that we need to allow bulk approval for:

   - identical segments (we could use autopropagation so to also propagate
   any marked errors);
   - segments containing only figures or untranslatables;
   - segments very similar (say over a 98% match).

We are currently working on a new review interface which may replace the
one that we are using now in a couple of months. We will take into
consideration your suggestions and try to make it easier for reviewers to
do their job.

Let me know if you have any further suggestions on this.

You can also write directly to me.

-- 
Alessandro Cattelan
MateCat Product Manager
alessandro@translated.net




-- 
Alessandro Cattelan
Vice President Operations
http://www.translated.net
Direct: (+39) 06 90 254 223
Mobile: (+39) 338 18 23 554
Main:  (+39) 06 90 254 001
