### ISSUE TITLE
Error loading Matecat

### ISSUE THREAD

**Issue by gaurav214** [matecat/MateCat#1834]
I did a fresh install of Matecat on ubuntu 18.04. Followed the instructions of installation guide.

Getting below error:
![Screenshot 2020-10-22 104901](https://user-images.githubusercontent.com/13104153/97895212-67f76d80-1d2b-11eb-9039-bde0e5c097ee.png)

Any suggestion as to what might be causing this issue?

**Comment by Ostico** [comment]
This is an issue on regarding CORS. Your browser refuse to load data from TildeMT servers because they do not show to accept requests that comes from your MateCat.

This should not be a problem and can not cause malfunctionings.
