### ISSUE TITLE
How to connect MateCat Filter

### ISSUE THREAD

**Issue by BhavyaShukla** [matecat/MateCat#1855]
I bought the subscription for MateCat Filter API on rapidapi.com.

Is there any guide on how to connect to this API, I have installed MateCat on AWS instance using the installation guide. Everything is working fine, but can't seem to upload file formats which are not xliff.

I want to test other formats too but I am getting an internal error 500, after connecting to matecat filter api.

**Comment by Ostico** [comment]
Hi @BhavyaShukla ,

you have to configure MateCat ( on the file config.ini ) to use RapidAPI.

Those variables in the configuration file must be set.

``` 
FILTERS_ADDRESS       = "https://translated-matecat-filters-v1.p.rapidapi.com/AutomationService/xliff2original";
FILTERS_MASHAPE_KEY   = "XXXXXXX-RapidAPI-Key-XXXXXXXX";
```

Sorry for the misleading name of the variable but mashape was acquired by RapidApi.

**Comment by BhavyaShukla** [comment]
Thanks @Ostico
