### ISSUE TITLE
Not Getting TM results

### ISSUE THREAD

**Issue by gaurav214** [matecat/MateCat#1857]
I am able to upload files and translate them. But I am not seeing the TM matches. It just keeps loading. 

![image](https://user-images.githubusercontent.com/13104153/100378728-90f9de00-300b-11eb-95d2-dd880016ab25.png)

Everything was working fine before. But once I enabled the login option following #1842, the login worked but i started getting this issue. Please let me know if you need any log files. Below is the file persmissions:

![image](https://user-images.githubusercontent.com/13104153/100378857-d3231f80-300b-11eb-874c-b26937483640.png)

**Comment by Ostico** [comment]
Hi @gaurav214 ,
Check that your nodejs server is running.

**Comment by BhavyaShukla** [comment]
Thanks @Ostico

**Comment by gaurav214** [comment]
Thanks @Ostico
