### ISSUE TITLE
Not getting Email notification for translation

### ISSUE THREAD

**Issue by BhavyaShukla** [matecat/MateCat#1862]
Hello @Ostico 

Everything is working fine in my Matecat installation, but I am not getting any email notifications. 
For example, when I assign a project to my another email_id for translation. I can't see that project in my another account.

**Comment by mitulverma14** [comment]
I also have the same issue. I can assign projects to team, but assigning translation with email is not working.

**Comment by Ostico** [comment]
Hi all,
are you sure you configured the right smtp server in config.ini?

**Comment by mitulverma14** [comment]
Yes, everytime I assign a job to translator(my another account), I am not getting any notification(job url).

I am using Amazon SES service, and using the ServerName as SMTP_HOST and SMTP_HOSTNAME. 
I tested sending email from SES service, which is working. But not able send any from matecat.

**Comment by Ostico** [comment]
Check the logs of your email queue

**Comment by Ostico** [comment]
MateCat has a log for the emails

**Comment by mitulverma14** [comment]
I used the url in the log file for now. Although, I still can't get the mailing work. Will update you if I find some workaround for this.
