### ISSUE TITLE
Not able to upload TMX file

### ISSUE THREAD

**Issue by mitulverma14** [matecat/MateCat#1863]
Hey @Ostico 

I am getting below issue while uploading a TMX file in my local instance.
![image](https://user-images.githubusercontent.com/57497470/100890444-2ab00800-34b0-11eb-9b7a-af23b3749498.png)

I tried uploading the same file in official Matecat too, but there I got the below error:
Upload::_uploadFile -> File Dimensions Not Allowed.

How do I resolve the TM key issue?

**Comment by Ostico** [comment]
Hi @mitulverma14 
you have 2 solutions, the first one is to divide your tmx in smaller parts, the second one is to contact matecat support. They can help you, provide them a MyMemory key ( a TM Key ) and the TMX file you want upload.

**Comment by mitulverma14** [comment]
Thanks for response @Ostico 

So only way I can upload this TMX in my local instance is by breaking it into multiple parts?
