### ISSUE TITLE
How can I connect to Matecat TM?

### ISSUE THREAD

**Issue by mitulverma14** [matecat/MateCat#1875]
Hello @Ostico 

Whenever we upload a translation memory, where does it store in the database? Can i access it on my local instance? I checked Mymemory.php, but it only has segment matching code.

**Comment by Ostico** [comment]
Hi @mitulverma14 
your memories are uploaded to MyMemory TM Engine.
You can download your TMXs from the MateCat UI.

Alternatively you can download directly via API from MyMemory.
https://api.mymemory.translated.net/tmx/export/create?key=_your_mymemory_tm_key&user_email=_your_email_&user_name=_your_name_
