### ISSUE TITLE
Smooth scroll upon opening a segment recenters view at the end, even if user scrolled away during it

### ISSUE THREAD

**Issue by felixvd** [matecat/MateCat#19]
This is not only annoying during revision when you approve a segment, try to scroll down, and have your view ripped away, but it also seems to stack when you hammer Cmd+Enter 10-20 times to approve the next section of text, and you are unable to scroll for a while.

**Comment by felixvd** [comment]
Recorded a demonstration: https://www.youtube.com/watch?v=Icp71u6vSZk

The lag at the start shows pretty well how resource-heavy opening each segment is. Another reason to consider issue #18.

**Comment by riccio82** [comment]
Fixed
