### ISSUE TITLE
Matecat does not understand russian plurals

### ISSUE THREAD

**Issue by last-partizan** [matecat/MateCat#1925]
Hi, we're trying to use matecat for translation, but it fails to upload our po-file with following error:

```
[1.3.1] - net.sf.okapi.common.exceptions.OkapiIllegalFilterOperationException: Line 21: Possible extra or invalid plural form of msgstr. ; [1.2.5] - Line 21: Possible extra or invalid plural form of msgstr.
```

Minimal file for repruducing a bug:
```
msgid ""
msgstr ""
"Project-Id-Version: test-1.0\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-02-17 15:58+0200\n"
"PO-Revision-Date: 2021-02-17 15:55+0200\n"
"Last-Translator: Serg <serg.partizan@gmail.com>\n"
"Language-Team: Russian <ru@example.org>\n"
"Language: ru\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n"
"%100<10 || n%100>=20) ? 1 : 2;\n"
"X-Generator: Poedit 2.4.1\n"

msgid "day"
msgid_plural "days"
msgstr[0] "день"
msgstr[1] "дня"
msgstr[2] "дней"
```

**Comment by Ostico** [comment]
Hi @last-partizan ,
we investigated in your issue and we found the problem.

Seems to be a too loose implementation of the PO file format regarding the pluralization.

In the current implementation, to allow pluralization, the line describing the rules must be one line only:

This is the correct syntax:

`"Plural-Forms: nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2;\n"`

In the next releases we will make this more strict to the specs.

Specs:
> It’s logically one line; recall that the PO file formatting is allowed to break long lines so that each physical line fits in 80 monospaced columns.

**Comment by last-partizan** [comment]
@Ostico thank you, it worked!
