### ISSUE TITLE
A few issues with my installation.

### ISSUE THREAD

**Issue by burakoslu24** [matecat/MateCat#1927]
Hello,

First issue is about machine translation. It doesn't work in translation process and enters a loop when trying to bring machine translation result, even though I enter the api key and activate cloud translation api in google cloud console.

The second is about QR. When I try to check the quality report, it opens the page but again enters a loop.

Third is not an issue, could you tell me how to change the header color? (the main blue one with the menu in it)

Thanks.

**Comment by burakoslu24** [comment]
I used the automatic translation script located in support scripts folder during the installation.

**Comment by burakoslu24** [comment]
Update: I tried to run node server and stuck at this: debug: Listening on http://localhost:7788/. 
It just says this and nothing further happens.

**Comment by Ostico** [comment]
Hi @burakoslu24, do you enabled the php processes by configuring them in `./inc/task_manager_config.ini` ? Which MT engine are you using?

**Comment by burakoslu24** [comment]
> Hi @burakoslu24, do you enabled the php processes by configuring them in `./inc/task_manager_config.ini` ? Which MT engine are you using?

Hello again, just for the records, I solved the TM and MT issue by running screen code in the installation guide. The problem was the server.js's not being activated.

But QR still doesn't work and I still couldn't figure out how to change the header color.
Any solutions? @Ostico

**Comment by Ostico** [comment]
Hi @burakoslu24 , regarding the QR, i need more info, can you check chrome network results in the developer tools and the MateCat logs? I think you should check for `fatal_errors.txt` log in `storage/log_archive/` directory of your matecat installation. It is strange that the QR page do not displays, never happened on our side.

**Comment by burakoslu24** [comment]
> Hi @burakoslu24 , regarding the QR, i need more info, can you check chrome network results in the developer tools and the MateCat logs? I think you should check for `fatal_errors.txt` log in `storage/log_archive/` directory of your matecat installation. It is strange that the QR page do not displays, never happened on our side.

Thanks a lot for the heads up @Ostico , I'll check it out and write down the solution here if I find something. Again, where's the file that control the color of the header color?

**Comment by Ostico** [comment]
Hi @BrandonGillis , this is the file:
`public/css/sass/quality-report.scss`

**Comment by burakoslu24** [comment]
> Hi @burakoslu24 , this is the file:
> `public/css/sass/quality-report.scss`

Does each page have seperate css file? I think this one is for the quality report screen, so what's the main upload screen's css file?

**Comment by Ostico** [comment]
Should be this one:
`public/css/sass/style.scss`

**Comment by burakoslu24** [comment]
> Should be this one:
> `public/css/sass/style.scss`

Still couldn't change the color. I changed something similar to it but the color is still the same. Flushed cache multiple times. Any other suggestiongs? @Ostico

**Comment by riccio82** [comment]
You need to change this:
https://github.com/matecat/MateCat/blob/0a19c3f7f02dc97be8dc33363e5ce29e774d597d/public/css/sass/quality-report.scss#L28
