### ISSUE TITLE
matecat.sql Incomplete Cannot complete database initialization according to the document

### ISSUE THREAD

**Issue by ar414-com** [matecat/MateCat#1938]

**Comment by ar414-com** [comment]
At present, the code of the installation document and the project do not match at all, and it cannot be successfully deployed according to the document

**Comment by Ostico** [comment]
Hi @ar414-com 

the sql schema is now fixed in master branch and in 2.17.14 tag.

**Comment by ar414-com** [comment]
Thank you for your contribution to open source. According to the documentation, I finally got to this point. I can’t know which step went wrong.
![image](https://user-images.githubusercontent.com/58111015/111676636-54235280-8859-11eb-8e15-304952fa8fa6.png)
