### ISSUE TITLE
Thank you for your contribution to open source. According to the documentation, I finally got to this point. I can’t know which step went wrong.

### ISSUE THREAD

**Issue by ar414-com** [matecat/MateCat#1940]
Thank you for your contribution to open source. According to the documentation, I finally got to this point. I can’t know which step went wrong.
![image](https://user-images.githubusercontent.com/58111015/111676636-54235280-8859-11eb-8e15-304952fa8fa6.png)

_Originally posted by @ar414-com in https://github.com/matecat/MateCat/issues/1938#issuecomment-802180428_

**Comment by Ostico** [comment]
Hi @ar414-com 
you should try to check in your logs to see if something went wrong.

Let me know, unfortunately I need more info about that.
