### ISSUE TITLE
Google sign

### ISSUE THREAD

**Issue by Alf71** [matecat/MateCat#2]
Is sign in in Google the only way to manage when using a own server or virtual box?
And are the TMs and files saved into my Google account?

**Comment by matecat** [comment]
Hi, yes Google SignIn it is the only way to authenticate in MateCAT.
But don't warry: it is ONLY an authentication step.
*Nothing is sent to Google when you using MateCAT*: no TM, no segments, no
files, no glossaries.

Do not hesitate to ask for every doubt.

Antonio

2015-01-14 10:12 GMT+01:00 Alf71 <notifications@github.com>:
