### ISSUE TITLE
Find & Replace does not save changes reliably, seems to lose connection to server

### ISSUE THREAD

**Issue by felixvd** [matecat/MateCat#20]
It is unclear when Find & Replace results in a lasting change to a segment. If I progress through the matches and replace manually, I often end up running in circles, as entries I have already changed come up again as matches. 

I have not tested and reproduced this reliably. It happens about half the time for me. This issue is especially treacherous because it is silent and easy to overlook that the changes have been lost. I have (embarrassingly) submitted work with mistakes that I am absolutely certain I had fixed via Find & Replace.

Intuitively, I'd guess that the changes might be discarded when a new view / new segments are loaded from the server. When are changes written to a segment / uploaded to a server? Maybe information is lost at that point?

edit: I should add that I have been using the Revise mode, if that changes anything.

**Comment by felixvd** [comment]
Often after using Find & Replace, submitted segments (as well as find&replaced text) stop being transferred to the server without any warning. Only a reload fixes this, and it causes work to be lost every time, which is very unpleasant.

I get the impression that my connection breaks more often if Find & Replace has to jump to a different parts of the project. If I Find & Replace in just one local view, it works more often than not.

Is there something in the messaging that could go wrong when the client simultaneously sends updates and requests a set of segments? It feels like some part of the server/client communication fails and causes an unacceptably long wait, and does not restart. Is there a debug menu or anything that displays more information on the server communication to investigate this further?

**Comment by felixvd** [comment]
I repeat that it is currently impossible to Find&Replace through a big job to fix common errors, because at some point the connection will be lost, and there is no notification for it, causing work to be lost. 

The only way I have found to check that changes are still being transferred is to submit a segment and wait for it to turn green.

**Comment by felixvd** [comment]
I really want to add that this bug happens to me regularly, multiple times per hour, and it's a serious usability issue that drains a considerable amount of my time and concentration.

It goes without saying that redoing the same work multiple times because the interface keeps losing it is a sub-optimal user experience as well.

**Comment by Ostico** [comment]
Hi @felixvd ,
Surely you discovered a bug and/or a bad behaviour. 
Can you provide more info to replicate this? If you can, send to support@matecat.com ( or through snap-engage ) the link to you translate page. Thank you in advance.

**Comment by felixvd** [comment]
This is as much as I've got for the moment. I haven't found a way to replicate the issue reliably. Since connection information is hidden from the user unless an issue is detected (although obviously there are some that are not), it's hard to see when something went wrong. If there was a way to see a networking log or something similar, I might get a better idea of what's going on. Is there a debug interface maybe?

All I know for now is that the issue seems very likely to be related to the Find & Replace function and that it seems to happen more often if many fields are changed.

**Comment by felixvd** [comment]
I currently have a large review job open where I want to Find & Replace a simple reoccurring error. There are about 40 instances of it at different parts of the document, and I have to go through it manually. 

I went through the file with Find & Replace until I got back to where I started, then tried approving a nearby segment and waited a few minutes to check if it turns green.

Result: I did this about 5 times because the segment never turned green. After those 5 passes, of the 40 initial instances of the error, 22 are still left in the document. That means that on average, the function broke down after barely 5 corrected segments.

With that kind of result, I am confident that you can replicate this within any big job (make the distance between the search results large enough so that Matecat turns the screen grey and skips to a new area of the document), but I will send you the link to the project via snap-engage.

To reiterate, my intuition is that this is a server communication issue, and the request for new segments/a new document view disturbs the transfer of changed segments somehow.

**Comment by felixvd** [comment]
I don't know what's going on in that commit, but it sounds like that fixes the issue alright. I also got the impression it has to do with getting new segments.

As circumstantial evidence and maybe a test to confirm this is fixed: I just had it happen on a row of segments that appeared nowhere else in the job. I clicked replace for all the segments, and no segments were changed after getSegments was called. You can see 2 of 5 segments changed and no further changes occurring in this screenshot:

http://imgur.com/GxPZCAu

**Comment by felixvd** [comment]
Whichever version is live on matecat.com still has this bug, and makes the function rather useless for large jobs.

**Comment by riccio82** [comment]
Fixed
