### ISSUE TITLE
Mymemory Rapidapi not compatible with Matecat /analyze endpoint

### ISSUE THREAD

**Issue by korxz** [matecat/MateCat#2037]
I bought Mymemory API key over Rapidapi and replaced the engine  endpoint in DB from http://api.mymemory.translated.net/ to https://translated-mymemory---translation-memory.p.rapidapi.com/api  and added the x-rapidapi-key in header in code.

Now the files never seem to finish analysis and i get this error in FastAnalysis log file: 

message":"Endpoint\/api\/analyze does not exist

`{"log":{"token_hash":"60acc6b96b5ce","context":{"ip":"172.20.0.5","class":"Engines_AbstractEngine","function":"call","line":221},"time":1621936862,"date":"2021-05-25T12:01:02+02:00","content":{"timing":{"Total Time":0.046282,"Connect Time":0.008505,"Pre-Transfer Time":0.035944,"Start Transfer Time":0.035947,"Transfer Time":"10335\u03bcs"},"resource_hash":"60accadeccb701.81514380","url":"https:\/\/translated-mymemory---translation-memory.p.rapidapi.com\/api\/analyze","options":{"post_parameters":{"fast":"1","df":"matecat_array","segs":"[{\"jsid\":\"35-8:1bad4f859b56\",\"segment\":\"NULS\",\"segment_hash\":\"1bc4ab44e33c5fad979afe9931966757\",\"source\":\"en-US\"},{\"jsid\":\"36-8:1bad4f859b56\",\"segment\":\"ONT\",\"segment_hash\":\"81a634c8428d49490d850ac61dcd055b\",\"source\":\"en-US\"},{\"jsid\":\"37-8:1bad4f859b56\",\"segment\":\"XRP\",\"segment_hash\":\"b963e1952393b6f6899c6978de03a6f6\",\"source\":\"en-US\"},{\"jsid\":\"38-8:1bad4f859b56\",\"segment\":\"KMD\",\"segment_hash\":\"0cccf5bbd8462dbbe600777c5489798e\",\"source\":\"en-US\"},{\"jsid\":\"39-8:1bad4f859b56\",\"segment\":\"WAN\",\"segment_hash\":\"e4c50e7a3518208e18c827187578acdf\",\"source\":\"en-US\"}]"}},"error":{"http_code":404,"error":"","errno":0},"error_body":"{\"message\":\"Endpoint\\\/api\\\/analyze does not exist\"}","response":null}}}
{"log":{"token_hash":"60acc6b96b5ce","context":{"ip":"172.20.0.5","class":"Analysis\\Workers\\FastAnalysis","function":"main","line":192},"time":1621936862,"date":"2021-05-25T12:01:02+02:00","content":"MyMemory Fast Analysis Failed. Pid: 9"}}
{"log":{"token_hash":"60acc6b96b5ce","context":{"ip":"172.20.0.5","class":"Analysis\\Workers\\FastAnalysis","function":"_updateProject","line":383},"time":1621936862,"date":"2021-05-25T12:01:02+02:00","content":"*** Project 9: Changing status..."}}
{"log":{"token_hash":"60acc6b96b5ce","context":{"ip":"172.20.0.5","class":"Analysis\\Workers\\FastAnalysis","function":"_updateProject","line":385},"time":1621936862,"date":"2021-05-25T12:01:02+02:00","content":"*** Project 9: NEW"}}`

**Comment by Ostico** [comment]
Hi @korxz ,

thank you for the report, this is a really important issue for us.

Will be marked as bug and we will work to solve the issue. 
Unfortunately it seems to be a complex task, so I can't give an ETA now.

**Comment by korxz** [comment]
Hello @Ostico ,
thank you for your reply. Is there any way existing license (for rapidapi) could be used for mymemory api (http://api.mymemory.translated.net/) without having api limitations?

**Comment by Ostico** [comment]
Hi @korxz ,
we are discussing internally your issue.
By definition RapiAPI were not designed to be used in any MateCat installations, but MyMemory has some plans that can be used with matecat.
