### ISSUE TITLE
PHP version is Out of date, some package is abandoned. 

### ISSUE THREAD

**Issue by kokoye2007** [matecat/MateCat#2049]
Package phpoffice/phpexcel is abandoned, you should avoid using it. Use phpoffice/phpspreadsheet instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.

**Comment by vasyugan** [comment]
Is the open source version of Matecat still being maintained? I would assume that whatever is running on matecat.com is not that outdated.

**Comment by kokoye2007** [comment]
they split out.
open source version is not update.

**Comment by Ostico** [comment]
Hi, the open source version of MateCat is fully supported and updated.

The package listed by @kokoye2007  are not under security risk and are fully functional, at the moment there is no need to update them.

**Comment by vasyugan** [comment]
> Hi, the open source version of MateCat is fully supported and updated.
 
Hi, great to hear that that the project is not abandoned!

However, it seems to depend on legacy PHP versions that have had their EOL years ago. Or is it being ported to a newer base? 

I tried to install it on Ubuntu 18.04, as this is the platform recommended by the install instructions, and I hit the same issues as the submitter of issue #2048 (grunt related issue, I have to admit, I don't even know what grunt is). Following the instructions, there was no way for me to complete the test install.

**Comment by Ostico** [comment]
We are planning to update the guide.
