### ISSUE TITLE
question about backend

### ISSUE THREAD

**Issue by tibetmadman** [matecat/MateCat#2136]
hey,guys,we installed the matecat follow this 
installation guide here:
http://site.matecat.com/installation-guide/
now it's worked.  but I can't find the way into the  backend,
so,please help me. just tell me how can I get the  way into the backend  as a Administrato ?
what's the website port of the management backgroud ?
thanks a lot

**Comment by Ostico** [comment]
Hi @tibetmadman 
MateCat has no administration panel.

**Comment by tibetmadman** [comment]
> Hi @tibetmadman
> MateCat has no administration panel.

thinks a lot

**Comment by tibetmadman** [comment]
> Hi @tibetmadman
> MateCat has no administration panel.

> 
![微信图片_20210802094714](https://user-images.githubusercontent.com/74006573/127793939-aebf198e-d501-47f0-8527-2e1cbfecd3df.png)

two question ,such as the photo obave, the Chinese translate into Tibetan that MT or the Chinese translate into English
that MT is you develop by yourselves?

and 
![image](https://user-images.githubusercontent.com/74006573/127798926-300871e3-87e6-49e1-83ee-e92bb2d36ce1.png)

upload the file and  show this error:

Curl error 6: Could not resolve host: xxx
