### ISSUE TITLE
Revise screen Add issues button

### ISSUE THREAD

**Issue by hamihaa** [matecat/MateCat#2173]
Hello, i have a problem with a cloned develop/master branch project:

On revise screen, there are console errors on page load:
1. Cannot read property 'is_pass' of undefined
2. Syntax error, unrecognized expression: $segment-[object Object]

And when clicking on the red Add issue button, the following error occurs:
UI.openIssuesPanel is not a function

screenshot from local build:

![matecat-ui-panel](https://user-images.githubusercontent.com/23343814/130043771-2e0e9a63-394f-403b-b217-d0eb64dcf517.png)

expected behavior should be as this screenshot from matecat.com:
![matecat-ui-panel-expected](https://user-images.githubusercontent.com/23343814/130043841-49c55c49-2d3e-4302-b66f-0e491f69e708.PNG)

Can you please provide any useful information, why does this frontend bug happen only on revision screen, everything else is working normally?

**Comment by Ostico** [comment]
Hi @hamihaa 

this is the old deprecated default configuration. We are removing this behaviour from matecat but it is under development.

For now I suggest you to enable the new functionality bi configuration.

Go in `inc` folder and add to the `config.ini`  this line:

`MANDATORY_PLUGINS[2] = "review_extended"`

**Comment by hamihaa** [comment]
Great, that solved the issue, thanks! 

I have another problem though: TM suggestions for segments are always returning empty on latest develop or master build, no network or console errors. I have a docker build of cat.

I was previously running fork from 07 december 2020 (commit HotFix - v2.16.22) which is returning tm suggestions normally.

Thanks for help.

**Comment by Ostico** [comment]
Can you check if your browser console is showing errors?

**Comment by hamihaa** [comment]
No console errors besides the /sse, which shouldn't be the one responsible for TM suggestions.
![tm_sugg](https://user-images.githubusercontent.com/23343814/130606675-e77dc0c5-448e-4272-9513-9c59fc4a398d.png)

and another screenshot of network tab:

![239961581_4156246507790394_5766356685177540973_n](https://user-images.githubusercontent.com/23343814/130606858-29b8f3ec-00c0-41be-9272-02e3e71789df.png)

**Comment by Ostico** [comment]
Hi @hamihaa 
Yes, it is exactly your problem. Your client can not connect with you nodejs instance. 
It is responsible to dispatch the messages to the UI. 

Check that your node instance is running.

**Comment by hamihaa** [comment]
Indeed, my old docker node_config was missing the new cors rules

```
[cors]
allowedOrigins[] = https://localhost
allowedOrigins[] = http://localhost
```

thanks for the quick help!
