### ISSUE TITLE
How we can handle tags for translation from english to Other languages(Marshallese) 

### ISSUE THREAD

**Issue by ravioodles** [matecat/MateCat#2178]
Hi, Team hope you are doing well.

We have set up the Matecat tool on localhost. Then we try to translate the file from English to Marshallese and in my source file, there are the styling tags(<g> <x>)  that are showing to UI in the source segment. And when it comes to target segment we also have a tag in it and they come to a point we are also able to see them in the inspecting window but they are not reflecting in the target text area, So please can you guide us that which function or which code is removing tags and block them to show in the target text area.
I am also sharing a screenshot with you please have a look. In these we have target segment without tags is populated and in inspect window, we clearly able to saw that the <g> are there.
![Screenshot from 2021-08-24 17-23-50](https://user-images.githubusercontent.com/46445899/130737429-f9e7c874-3f06-4675-84e9-41819d60af8a.png)
![image](https://user-images.githubusercontent.com/46445899/130737858-72df156a-0e6f-4e70-9ee5-565ce464314a.png)
![image](https://user-images.githubusercontent.com/46445899/130737933-3576ba20-fcc7-447b-ab58-041505f53226.png)

.

**Comment by Ostico** [comment]
Hi @ravioodles 
in such target language there is no MT available and not memories. So, there is no way to have tags in target. You must add ( report ) them manually.

**Comment by ravioodles** [comment]
Ok, Thx for the reply.

Is there any way we can remove tags from the source language segments after uploading the file?

Thanks and Regards

**Comment by Ostico** [comment]
Yes you can manually remove the tags from source directly from database by modifying the segments row by row. In this way you will not have tags in source, and you can translate the source without inserting tags.

BTW, i do not recommend that because at the end of work, you will have a target without tags, and you can not convert back to the power point file .

**Comment by ravioodles** [comment]
> Hi @ravioodles
> in such target language there is no MT available and not memories. So, there is no way to have tags in target. You must add ( report ) them manually.

Thanks for the suggestion and quick response again.

Yes i have added it manually but it is not saving the tags for in that translated segment for future whenever we refresh the page the tags get removed automatically and the text without tags is shown in the target text box.

Source segment :- <g id="1">Know </g><g id="2">your  </g>team<g id="3"> </g><g id="4">member  </g><g id="5">rights.</g>

We made target segment like this manually:- <g id="1">update </g><g id="2">your  </g>team<g id="3"> </g><g id="4">member  </g><g id="5">rights.</g>

But after refreshing the page we got :- update your team member rights.

and also on revise page we got segment like this :- update your team member rights.

Why tags automatically get removed from target text box as source also have the tags. can we stop it by removing the tags?

Thanks and regards.

**Comment by Ostico** [comment]
Can i close?
