### ISSUE TITLE
ICE matches

### ISSUE THREAD

**Issue by gaurav214** [matecat/MateCat#2181]
How does Matecat handles ICE matches, does it use crc number? I exported tmx files, but there was no crc number in it. 
Also, does Mymemory returns the status of segments (like whether it is 100% match or ICE match).

Thanks for any response.

**Comment by Ostico** [comment]
Hi @gaurav214 
regarding the context, MateCat, in the default open source implementation, handles ICEs by context. So, the context is provided by the previous and next segment.

You are talking abour SPICEs:

> The segment preferred in-context exact (SPICE) match is similar to the basic ICE mechanism. The SPICE match process supports another leverage level that is superior to the basic exact match supported by traditional TM systems. Instead of inferring context information from the surrounding segments and the containing document, the SPICE mechanism derives context explicitly from a segment identifier.
