### ISSUE TITLE
Quality-of-life suggestion for words and files limit

### ISSUE THREAD

**Issue by Adam-Saeed** [matecat/MateCat#2182]
This is more like a request rather than an issue,
I've been trying to create a project and it refuses due to the file being over 250k words
I tried splitting it into multiple files but MetaCat isn't satisfied.

I wish if MetaCat can do that by itself, splitting the file, I don't mind if it used my CPU power to do that.
That may apply to the 100 file limit per project too, and if the projects can be grouped in a folder so they don't clutter the team's projects page.

**Comment by Ostico** [comment]
Hi @Adam-Saeed 

regarding the file limit and the automatic split of the file, unfortunately this is not possible, supported files format are really different and the concept of project grouping do not exists in MateCat.
