### ISSUE TITLE
Pdf upload winconverter failure

### ISSUE THREAD

**Issue by korxz** [matecat/MateCat#2190]
Hello,
when uploading pdf I get following error from backend:

`[1.3.6] - java.lang.RuntimeException: WinConverter failure caused by com.matecat.converter.core.winconverter.WinConverterException: WinConverter error 5: internal errorconversion from pdf to docx is not supportedunknown error code ; [1.2.5] - com.matecat.converter.core.winconverter.WinConverterClient$WinConverterException: WinConverter error 5: internal error`

Txt, docx, xls and other filetypes are processed normally

**Comment by Ostico** [comment]
Hi @korxz 

this is a temporary issue.
