### ISSUE TITLE
Open brackets, tags in search term cause faulty behavior

### ISSUE THREAD

**Issue by felixvd** [matecat/MateCat#22]
If you search for a term like "PA (Nylon", clicking on "Find" does not give a result. If a previous search has displayed a result, the display will be updated to say "Searching..." but never finish, or otherwise not pop up at all. The function seems to crash before that point.

This issue is especially relevant when tags are inside brackets, because those also seem to cause problems during search and it's not clear how to deal with them. I am trying to find a segment that reads "<cf> PA (Nylon</cf><cf> ) </cf>" according to the QA report tool, but that term does not seem to be searched correctly either.

**Comment by antoniofarina** [comment]
I opened a task for the UI engineer.

**Comment by Ostico** [comment]
Fixed
