### ISSUE TITLE
Excel file segmentation 

### ISSUE THREAD

**Issue by enejravbar** [matecat/MateCat#2243]
Hello,

today I was testing Matecat. I uploaded the Excel file, but I encountered an issue. 

I cannot get the Matecat to segment the Excel file on cell-level. Segmentation is always done on sentance-level. So the Excel cell with multiple sentences manifest as multiple segments.

I tested all of available segmentation rules (General, Patent and Paragraph) but none of them produced expected results.

I hope you can add this option to **Segmentation rules**. Is this possible?

**Comment by AlexFalappa** [comment]
Hi @enejravbar segmentation rules are there exactly for that purpose, break text at sentence level. By default the Matecat Filters perform a sentence level segmentation based on ICU sentence rules.

In your own matecat instance you could set-up an SRX file to _undo_ the above default sentence segmentation.
