### ISSUE TITLE
Table 'matecat.files_parts' doesn't exist

### ISSUE THREAD

**Issue by ismail197** [matecat/MateCat#2247]
Table 'matecat.files_parts' doesn't exist

![Capture](https://user-images.githubusercontent.com/76798811/142857626-adf18c9a-22d3-4662-acb5-fb79c42a0fcb.PNG)

**Comment by Ostico** [comment]
Thank you, it lacks on the schema. We will update the schema.

**Comment by mauretto78** [comment]
@ismail197 we update the schema files, now it should work. Take care of update your local DB schema

**Comment by ismail197** [comment]
@Ostico  & @mauretto78  Thank You very much !
