### ISSUE TITLE
Dont get result , page in infinite loop

### ISSUE THREAD

**Issue by ismail197** [matecat/MateCat#2252]
**this is the scenarion , i upload my xlif and TM files , after that i click on analyze , i get this page :**
![k](https://user-images.githubusercontent.com/76798811/143287377-d0fcc42f-dfcc-480d-be7e-26086c6b86cb.png)

**when i click on Translate i get an infinite page load :** 
![F](https://user-images.githubusercontent.com/76798811/143287459-62bf6c9e-fd7a-4e82-aea7-5e9bcfb1b45b.png)

![G](https://user-images.githubusercontent.com/76798811/143287485-d9a3766a-6353-45df-bda3-3f41a36c7097.png)

**could you please help me**

**Comment by ismail197** [comment]
@Ostico @mauretto78  Help!

**Comment by Ostico** [comment]
Hi @ismail197 ,
please check in your server logs, we need more info in order to help you.

Check the fatal_errors log first.

**Comment by ismail197** [comment]
[Wed Dec 01 11:01:13.923253 2021] [ssl:warn] [pid 31608] AH01906: 0.ajax.dev.matecat.com:443:0 server certificateis a CA certificate (BasicConstraints: CA == TRUE !?)
[Wed Dec 01 11:01:13.923275 2021] [ssl:warn] [pid 31608] AH01909: 0.ajax.dev.matecat.com:443:0 server certificatedoes NOT include an ID which matches the server name
[Wed Dec 01 11:01:13.923654 2021] [ssl:warn] [pid 31608] AH01906: dev.matecat.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Wed Dec 01 11:01:13.923667 2021] [ssl:warn] [pid 31608] AH01909: dev.matecat.com:443:0 server certificate does NOT include an ID which matches the server name

**Comment by Ostico** [comment]
Hi @ismail197 

please check the matecat logs for fatal errors:
`<your_matecat_root>/storage/log_archive/fatal_errors.log`

**Comment by ismail197** [comment]
fatal_errors.log show
"error":"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'matecat.segment_metadata' doesn't exist"
@Ostico  @mauretto78
