### ISSUE TITLE
Show MT and track changes in revise mode

### ISSUE THREAD

**Issue by taurviz** [matecat/MateCat#2267]
Hello developers of Matecat,

I would like to ask is there a way to show MT and track changes in revise mode, sometimes MT produces more precise translations than manual translations. However, when the MT is edited by the translator in translate mode. It no longer shows in revise mode. 
Also, track changes are only visible in the quality report, how to make it visible in revise mode?

Thank you very much for the assistance.

**Comment by Ostico** [comment]
Hi @taurviz 
unfortunately this is not possible at moment.
