### ISSUE TITLE
CORS blocking API requests

### ISSUE THREAD

**Issue by Shooshte** [matecat/MateCat#2277]
Preflight request (when doing a POST) to `https://www.matecat.com/api/v1/new` is blocked by the server. I see the following error in the browser console:
> Access to XMLHttpRequest at 'https://www.matecat.com/api/v1/new' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
The status code I can see in Firefox is 400.

Since this is a public API I would expect it to be available from outside the Matecat domain.

This happens inside latest Chrome. With Postman the request goes trough normally, but returns 400 Missing language when both source_lang and target_lang are defined.

**Comment by Ostico** [comment]
Sorry @Shooshte but this API is not designed to be called from a browser.

**Comment by Shooshte** [comment]
Hi @Ostico. Until the recent update calling this API from a web browser worked without issues for us for more than a year. Is this something that was changed intentionally?

**Comment by Ostico** [comment]
We didn't changed anything, chrome changed his security policies.

**Comment by Shooshte** [comment]
This also happens in Firefox, Edge and Safari, and it worked in all those browsers yesterday. I really don't know what could be the cause of this. Could you at least try to investigate the issue?

**Comment by Shooshte** [comment]
Don't see why not. This is the function that calls the Matecat API. It works on a deployed instance of a previous fork of your repo, but does not work on the currently deployed Matecat API. It also worked with Matecat yesterday.

I'm sorry I can't really show you more since the project is big, but this should show you how we make the API call.

`export const postNewMatecatProject = async (
  {
    baseUrl,
    category,
    files,
    projectName,
    sourceLanguage,
    targetLanguage,
    private_tm_key,
    get_public_matches,
  },
  onUploadCallback,
) => {
  try {
    const formData = new FormData();
    formData.append('project_name', projectName);
    formData.append('source_lang', sourceLanguage);
    formData.append('target_lang', targetLanguage);
    formData.append('subject', category);
    formData.append('private_tm_key', private_tm_key);
    formData.append('get_public_matches', get_public_matches);

    for (let i = 0; i < files.length; i++) {
      formData.append('files[]', files[i]);
    }

    const { data } = await axios.post(`${baseUrl}/api/v1/new`, formData, {
      onUploadProgress: (e) => {
        if (onUploadCallback) {
          const completionPercentage = Math.round((e.loaded * 100) / e.total);
          onUploadCallback(completionPercentage);
        }
      },
    });
    return data;
  } catch (e) {
    throw e;
  }
};`

**Comment by Ostico** [comment]
@Shooshte sorry but it works:

https://jsfiddle.net/Ostico/ut5z0kw8/5/

when I use it in an async function it doesn't, so this do not depends on our code.

https://jsfiddle.net/Ostico/ut5z0kw8/8/

**Comment by Ostico** [comment]
By revieweing the commit history, i found the issue.
We fixed a bug in the API.
The response code of this API was always `200 OK` even in case of error. 
This bad behaviour allowed the preflight ( they are just an `OPTION` call with no parameters ) to suceed. 
Now the preflight options get `400 BAD REQUEST` and your code do not works anymore.

**Comment by Shooshte** [comment]
Hi Ostico,

Thank you for your feedback and the reply. The preflight request is a request done automatically by the browser for every POST request and is not controlled by our code.

In the working JSFiddle you provided the server response has the header of `Access-Control-Allow-Origin: https://fiddle.jshell.net`. This is why the network request does not get blocked.

To make your API publicly accessible app the API endpoints should have the [Access-Control-Allow-Origin ](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin) header set to *. It seems that this is not the case from the error I am getting in the console, and in your JSFiddle that is not working:

> Access to XMLHttpRequest at 'http://www.matecat.com/api/v1/new' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Thank you for your help

**Comment by Ostico** [comment]
@Shooshte sorry but I showed you that the prefilght is the issue. 
The browser send a prefilght request for every post request coming from an async function.

The API is not meant to be used from browsers.

As explained, OPTIONS requests are no more accepted since the endpoint API respond with `400 Bad Request` to a request with no parameters. The option preflight request is issued without parameters, so it will be not accepted.

Your suggestion (  Access-Control-Allow-Origin header set to *. )  is not suitable because it will not solve the issue.

Our web servers alredy accept OPTIONS and allow .* domains:
```
SetEnvIfNoCase Origin "https?://.*?$" CORS=$0
Header set Access-Control-Allow-Origin %{CORS}e env=CORS
Header set Access-Control-Allow-Credentials "true"
Header set Access-Control-Allow-Methods "POST,PUT,OPTIONS,DELETE"
```

To fix the issue you have to make the request sync and avoid preflight.

**Comment by Shooshte** [comment]
Hey,

> Our web servers alredy accept OPTIONS and allow .* domains:
> To fix the issue you have to make the request sync and avoid preflight.

Preflight and OPTIONS requests are the same thing. I am confused about what you mean here. We tried testing the same logic using postman, and this happened:

![unknown](https://user-images.githubusercontent.com/11058850/146180636-33187a54-291b-4060-866e-4ce44dcd4887.png)

This is a screenshot from a Postman request that used to work a couple of days ago. Now it returns bad request.

**Comment by Shooshte** [comment]
After debugging this a bit more it seems that `onUploadProgress` was causing the issues with the preflight request.

**Comment by Ostico** [comment]
> Hey,
> 
> > Our web servers alredy accept OPTIONS and allow .* domains:
> > To fix the issue you have to make the request sync and avoid preflight.
> 
> Preflight and OPTIONS requests are the same thing. I am confused about what you mean here. We tried testing the same logic using postman, and this happened:
> 
> ![unknown](https://user-images.githubusercontent.com/11058850/146180636-33187a54-291b-4060-866e-4ce44dcd4887.png)
> 
> This is a screenshot from a Postman request that used to work a couple of days ago. Now it returns bad request.

Please use `www.matecat.com` in the url.

**Comment by Shooshte** [comment]
I managed to get everything working after `onUploadProgress` was removed from the `axios` call. It seems this is no longer allowed by the API.

The postman request also started working after switching the URL to www.matecat.com.

Thanks a lot for the help.

**Comment by Ostico** [comment]
Welcome
