### ISSUE TITLE
Matecat Aligner Doesnt exist

### ISSUE THREAD

**Issue by ismail197** [matecat/MateCat#2279]
Matecat Aligner Doesnt exist

**Comment by Ostico** [comment]
It is a not distributed matecat plugin.

**Comment by ismail197** [comment]
is it paid ??

**Comment by Ostico** [comment]
No, it can be used for free bun only in the hosted version on www.matecat.com

**Comment by ismail197** [comment]
Can I purchase it for local use ?

**Comment by Ostico** [comment]
At moment, i guess, we have no plan to sell it. 
But i've to check.
