### ISSUE TITLE
Find and Replace includes segments not assigned to you, allows replacing texts in them

### ISSUE THREAD

**Issue by felixvd** [matecat/MateCat#23]
As described in title, Find & Replace not only includes segments that are not assigned to you, but it also shows no error message when you replace text in them.

It doesn't look like changes done this way are saved on the server, but it's unintuitive and not very helpful. This is related to #20 in that the Find & Replace function feels unresponsive.

**Comment by antoniofarina** [comment]
assigned to engineer for verification and fix

**Comment by Lyonard** [comment]
I've made some tests and it seems now fixed. 
I have created a new job, split it into many parts and tried to replace parts the text a segment. 
It's working now. 
Task closed

**Comment by antoniofarina** [comment]
Fixed.
