### ISSUE TITLE
Problem in Google + auth 

### ISSUE THREAD

**Issue by ismail197** [matecat/MateCat#2301]
Hello ,
i obtained OAUTH_CLIENT_ID & OAUTH_CLIENT_SECRET and i changed permissions as explained in advanced-manual-setup but i m not able to login , could you please help me
thank you in advance

**Comment by ismail197** [comment]
![image](https://user-images.githubusercontent.com/76798811/148041762-7fdcdda0-7299-4728-ad70-73d15ddbf30f.png)

**Comment by Ostico** [comment]
Please provide more info on how you configured oauth config file.
