### ISSUE TITLE
[Question] Access my Matecat account via API

### ISSUE THREAD

**Issue by enejravbar** [matecat/MateCat#2303]
Hello team,

I was reading the Matecat API manual. I'm interested in accessing my MT engine list and also creating new project.

![image](https://user-images.githubusercontent.com/17450719/148087281-fc0c5007-a265-4e57-b419-06c18888a6d6.png)
 
I also created new API key. How I can authenticate with my API key and successfully execute API call? Can you provide me an example?

Best regards,
Enej Ravbar

**Comment by Ostico** [comment]
Hi @enejravbar this is the cURL call:

`curl -X GET "https://www.matecat.com/api/v2/engines/list" -H "x-matecat-key:xxxxxxxxxxx-YYYYYYYYYYYY"`

**Comment by enejravbar** [comment]
Thank you @Ostico! I tested it with the Postman and it works. I got the successful JSON response.
[
    {
        "id": 4377,
        "name": "Google Cloud Translation",
        "type": "MT",
        "description": "Google Translate"
    }
]

I tried to create new project using **/api/v1/new** endpoint instructions. I also added -H "x-matecat-key:xxxxxxxxxxx-YYYYYYYYYYYY", but I always got an error. 

![image](https://user-images.githubusercontent.com/17450719/148108483-1577b6a4-1810-4903-a6b5-b38f2b4ea5fb.png)

Would you be so kind to provide also an example for this API call?

Additional question:
I guess if I set mt_engine = 4377, I will get MT suggestions from my custom MT (Google Cloud Translation)? Is this correct?

Best regards,
Enej Ravbar

**Comment by enejravbar** [comment]
Thank you @Ostico!
