### ISSUE TITLE
Help in Enabling Google+ login

### ISSUE THREAD

**Issue by ismail197** [matecat/MateCat#2336]
Could you pleaaase elaborate a document with screenshot for how to enable Google+ login as authentication to facilate for us the setting up of this option , i tried to enable this option but i failed .
Thank you in advance
Best regards

**Comment by ismail197** [comment]
or we can make a quick screen share  and i will create the documentation for you

**Comment by riccio82** [comment]
You need to create access credentials in the google [console](https://developers.google.com/workspace/guides/create-credentials).
