### ISSUE TITLE
HTTPS 500 ERROR

### ISSUE THREAD

**Issue by xYuGeeN** [matecat/MateCat#2357]
Good morning @Ostico 
Thank you for your reply. I'm going crazy trying to do it. Tell me exactly what you need to solve the problem and I'll be happy to. If you want we can talk through another platform. As you prefer.
The steps I did are on your website. I did each and every one of them. The sites that can be backed up in apache are correct as they were duplicated in enabled. 

Thank you very much.
Regards,
Manu

**Comment by Ostico** [comment]
Hi @xYuGeeN i close because it's dupliacted: https://github.com/matecat/MateCat/issues/2345
