### ISSUE TITLE
Question: Is it possible to import a document in XLIFF format to MateCat?

### ISSUE THREAD

**Issue by rbatllet** [matecat/MateCat#2399]
My idea is to translate the document in XLIFF format outside the Matecat application. 

Is there any way to be able to import the document in XLIFF format back into the MateCat application via API?

I don't know if it is possible to do that, is it ?

**Comment by riccio82** [comment]
What do you mean by import?
With Matecat you can upload xliff files and translate them and export.
If you need more information about supported files you can write to support@matecat.com.

**Comment by rbatllet** [comment]
Is it possible to upload the XLIFF file into the MateCat system through the API? I have not found a way to do it.
