### ISSUE TITLE
When Revise Pane is folded in, approving a changed segment fails silently, shows no error

### ISSUE THREAD

**Issue by felixvd** [matecat/MateCat#24]
Normally, trying to approve a segment after changing it will highlight the "Select the type of issue" field in red, but this is invisible when the pane is not expanded. In that case, the button will simply not react and it will look like a bug or connection error is at fault.

A solution would be to expand the field automatically upon clicking the button if further action is necessary.

**Comment by antoniofarina** [comment]
fixed in production.
now it works

**Comment by felixvd** [comment]
Alright, sweet, thanks.
