### ISSUE TITLE
How can I find app.js?

### ISSUE THREAD

**Issue by burakoslu24** [matecat/MateCat#2410]
A connection error occured with my server while I was editing app.js and now it's fully empty. I can't find it on the development branch of Matecat either. Where can I find it?

@Ostico

**Comment by rbatllet** [comment]
The app.js file can be found here -> /matecat/public/js/build/app.js

**Comment by burakoslu24** [comment]
I know the location in the installation in my machine. I just accidentally deleted it, now the translation segments won’t show up. I need the file itself for replacement now.

**Comment by rbatllet** [comment]
I think you can regenerate it again with:
* yarn install
* grunt deploy

in ~/matecat/nodejs as root

**Comment by burakoslu24** [comment]
That worked. Thanks a lot!
Aside from the subject, any suggestion for screens which keep shutting down? I created a cron job for checkscreens.sh every 1 minute but unfortunately it seems not working on a crontab. The script itself works with the command ./checkscreens.sh though.

**Comment by burakoslu24** [comment]
That worked. Thanks a lot!

Aside from the subject, any suggestion for screens which keep shutting down? I created a cron job for checkscreens.sh every 1 minute but unfortunately it seems not working on a crontab. The script itself works with the command ./checkscreens.sh though.
