### ISSUE TITLE
Feature request: Hotkeys for Revise pane

### ISSUE THREAD

**Issue by felixvd** [matecat/MateCat#25]
Every time a segment is edited during revision, submitting it requires moving your hand from the keyboard to the mouse (since you just typed), clicking one or more buttons in the "Select the type of issue" field, and moving your hand back. This feels unnecessarily cumbersome and uncomfortable.

It would be great if hotkeys like this existed:

Ctrl/Cmd+1: Move the "Tag issues" radio button selection one to the right (or back to the far left if at max)
Ctrl/Cmd+2-5: The same for the other 4 error types.

These are used for tab selection in the browser, but since Ctrl+F is already overloaded, they might as well be. If changing the radio button status steals focus from the text editing field, this hotkey would be useful as well:

Ctrl/Cmd+E: Move the cursor to the editing field of the selected segment

I believe this will not inconvenience normal users, and increase usability and revision speed.

**Comment by felixvd** [comment]
A friend of mine made a Greasemonkey script to implement this because he took pity on my wrists. Feel free to copy and implement properly: https://gist.github.com/hsperr/81a5fda8bcea7dcce69a

**Comment by marcotrombetti** [comment]
Thanks!!!

**Comment by marcotrombetti** [comment]
@antoniofarina please decide if to add it to roadmap or skip it. Then close the issue.
