### ISSUE TITLE
Request for the addition of Santali language (isocode: sat; rfc3066code: sat-IN)

### ISSUE THREAD

**Issue by Prasanta-Hembram** [matecat/MateCat#2525]
Hi, I use OmegaT for Translation and get suggestions from MyMemo TM, when I came around MatCat then Santali language was missing from the list of languages. Santali language suggestions can be fetched using this [MyMemo api (Which gives suggestions for Santali language)](https://api.mymemory.translated.net/get?q=January&langpair=en|sat). I request for adding Santali language to the list so that I can use Santali language in MateCat.

**Comment by Prasanta-Hembram** [comment]
Opened a PR #2526 (Added Santali language)

**Comment by Prasanta-Hembram** [comment]
@freegenie @LuigiClaudio @edgareler @vincy when it will be merged ?? please add it as soon possible so that I can upload start work with this language.

**Comment by riccio82** [comment]
Merged
