### ISSUE TITLE
[Feature request] Add support for Firefox

### ISSUE THREAD

**Issue by rbatllet** [matecat/MateCat#2534]
It makes no sense not to support the Firefox browser when it is fully compatible with Safari or Chrome. It would cost nothing to provide support for it.

**Comment by silopolis** [comment]
I'd surely have put it more gently... But YES ! Please 🙏 
I had to install another browser just to try MateCAT, and discover how good it was :)
Another day, another mood, another user... Missed gem.

Such a work deserves to be made available on all browsers.

Thanks a ton for making it and choosing Open Source

**Comment by riccio82** [comment]
I'm sorry, but support for Opera is not currently on the roadmap.
