### ISSUE TITLE
Analysis Page is causing the issue Not getting the standerd waited words waited words.

### ISSUE THREAD

**Issue by ravioodles** [matecat/MateCat#2584]
Hi Team

I have uploaded a file and than click on analysis button but after that it don't calculating the words and only the loading bar is keep on running. Also the translation page is empty.
I am also run the deamons 

Please tell me what is wrong as it running good for many months and this issue occurs suddenly from no where.

Thanks and Regards

![image](https://user-images.githubusercontent.com/46445899/205590663-16848b93-b08c-4772-8d0a-afa94e7655ab.png)
![image](https://user-images.githubusercontent.com/46445899/205591073-9f183920-0d6e-41a7-8a38-536c9e4143e0.png)
![image](https://user-images.githubusercontent.com/46445899/205591419-c3f8dfc7-e034-4f1a-852c-d3c5ae638fbc.png)
![image](https://user-images.githubusercontent.com/46445899/205591664-6a9b6e7f-aec1-4485-b710-239c5bf03ca9.png)

**Comment by Ostico** [comment]
Hi @ravioodles , MyMemory now works on HTTPS.

Your matecat is configured to call MyMemory over simple HTTP, so you get a HTTP 301 redirect.

Go in your database and in the `engines` table at row 1 set it as https.

Restart services and it willl work.

**Comment by ravioodles** [comment]
Hi @Ostico Thanks for the quick and straight reply. Yes now its work. 
Thankyou really appriciated.

**Comment by ravioodles** [comment]
Hi @Ostico Hope you are well.

**Comment by ravioodles** [comment]
Hi Team any Updates?
Thanks and Regards.

**Comment by ravioodles** [comment]
Hi Team again facing the same issue word count is not working can you please update what is going on and what is the issue we are foacing in this.
Thanks and Regards

**Comment by ravioodles** [comment]
Hi @Ostico team please guide and help.

**Comment by ravioodles** [comment]
Hi Team any updates?

Thanks and Regards

**Comment by ravioodles** [comment]
![image](https://user-images.githubusercontent.com/46445899/225509787-c04b014a-5103-40d5-ac64-5b6a7b388522.png)

**Comment by ravioodles** [comment]
Hi Team i am just getting the jid=undefined error in all requests and i am note made any change in the code the issue is come suddenly from nowhere. Please help me to resolve this ASAP.

![image](https://user-images.githubusercontent.com/46445899/225818760-8f1d027a-1774-4bd0-afc4-562464017c25.png)


Thanks and Regards.

**Comment by ravioodles** [comment]
Hi team any update please let s know its urgent

Thanks and Regards
