### ISSUE TITLE
Feature Request: "Approve and do not go to next unapproved segment" button in Revise view

### ISSUE THREAD

**Issue by felixvd** [matecat/MateCat#26]
There are situations when one has to change a handful segments that are already approved, but approving them always jumps to the next unapproved field. This behavior is optional in translation mode, but enforced during revision mode. A separate button like in the other mode would be coherent and helpful.

**Comment by antoniofarina** [comment]
I agree.
We already have in the short roadmap to add the button T+>> even in the revision page

**Comment by riccio82** [comment]
The `A+>>` button is available.
