### ISSUE TITLE
Revision field sometimes contains text from previous segment, blocks progress

### ISSUE THREAD

**Issue by felixvd** [matecat/MateCat#27]
As seen in these screenshots: 
http://imgur.com/kwOt43g
http://imgur.com/tKnXgSJ

The text in the Revision field is not identical with the segment, so it cannot be approved. Moving away and going back to the segment usually does not fix the text, although sometimes it does. Most often, the page has to be reloaded or the segment skipped, which interrupts the workflow. When the issue is persistent, it forces me to skip 20-40% of segments, but only after having read and trying to approve them.

The text in the revision field is almost always the content of the segment before the one being displayed. In the first screenshot, the segment containing "Betriebsdruck" was autopropagated and skipped over. One other time though, I approved 5 segments quickly in a row, and the second segment's text appeared in the Revision field.

It feels like this has to do with approving segments faster than the editor pane opens/finishes loading. Approving segments slowly and waiting for the pane to load normally causes no issues. I currently have this issue a lot with ping results like this:

--- matecat.com ping statistics ---
171 packets transmitted, 170 packets received, 0.6% packet loss
round-trip min/avg/max/stddev = 269.694/320.451/460.120/39.874 ms

I'll see if those are any different when I don't notice it as much.

**Comment by antoniofarina** [comment]
I understood the scenario: I will forward to our engineer in order to reproduce and fix

**Comment by marcotrombetti** [comment]
@antoniofarina status?

**Comment by Ostico** [comment]
No more issues reported after development/fixes. I think this can be closed.
