### ISSUE TITLE
Analysis Page is causing the issue again Not getting the standerd weighted words weighted words

### ISSUE THREAD

**Issue by ravioodles** [matecat/MateCat#2703]
Hi Team Hi @Ostico hope you are well,  again facing the same issue word count is not working can you please update what is going on and what is the issue we are facing in this did we made any change in the requests again?
Thanks and Regards

![image](https://user-images.githubusercontent.com/46445899/224625263-b18f083f-7a1c-4aec-b30b-b363987c3b38.png)

![image](https://user-images.githubusercontent.com/46445899/224625884-2bfcc1e6-901b-4ef1-9065-327606284e7f.png)

![image](https://user-images.githubusercontent.com/46445899/224626539-0a24d745-ac4e-419c-9230-c9c5bab8542b.png)

**Comment by ravioodles** [comment]
http://localhost/?action=getVolumeAnalysis&time=1678711176893,jid=undefined

I am getting the jid=undefined what it the issue because it came suddenly without any change.

Can you please help to resolve the issue. 

![image](https://user-images.githubusercontent.com/46445899/224899634-85917466-1cc4-4877-8339-f92b80bb15c8.png)

**Comment by ravioodles** [comment]
Hi Team any updates? All i am getting is undefined after each api calls do we made any change again to endpoints?
?action=getVolumeAnalysis&time=1678856736760,jid=undefined	
?action=outsourceTo&time=1678856737037,jid=undefined

Thanks and Regards

**Comment by ravioodles** [comment]
Hi Matecat team any update? Please help if you have some solutions. Thanks

**Comment by ravioodles** [comment]
![image](https://user-images.githubusercontent.com/46445899/225509868-d76bea04-53b9-41e8-8912-a91b8d1b594b.png)

**Comment by ravioodles** [comment]
Hi Team any suggestion for aboe request.

**Comment by ravioodles** [comment]
Hi Team any suggestion for above request.

Thanks and Regards.

**Comment by ravioodles** [comment]
Hi team any update please let s know its urgent

**Comment by Ostico** [comment]
https://github.com/matecat/MateCat/issues/2708
