### ISSUE TITLE
Can't access installation guide

### ISSUE THREAD

**Issue by steven-watt** [matecat/MateCat#2707]
I get an XML error when trying to access the installation guide at http://site.matecat.com/installation-guide/

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>3EXBV4P6D55Z8KD8</RequestId>
<HostId>
3CwbWdR7mmBjRQlfeEQTSfAbeVbobYJ2s8JMOsTczWeNb4hR36S/R/1Kl8vGkJdU9zVGk3tpfb33+a0sG5W9Uw==
</HostId>
</Error>

**Comment by riccio82** [comment]
Thanks for the alert, we need to fix it.
In the meantime, you can go to [http://site.matecat.com/installation-guide](http://site.matecat.com/installation-guide)

**Comment by riccio82** [comment]
Fixed
