### ISSUE TITLE
The css is not applied to the web

### ISSUE THREAD

**Issue by Mikelpineiro2024** [matecat/MateCat#2729]
I have done the installation with a docker and when I do the docker-compose up I have an error with the grunt and the css does not load.
![error](https://user-images.githubusercontent.com/46561394/232413354-d19ae440-bcb9-44e6-b0c9-ff0f572eeaf3.png)

**Comment by riccio82** [comment]
Which branch are you running? Is it up to date?
Try entering the container and running the command: `yarn && grunt development`.

**Comment by Mikelpineiro2024** [comment]
i have entered the container but i cant execute that command.

ERROR: There are no scenarios; must have at least one.

**Comment by riccio82** [comment]
Looks like a yarn problem: https://github.com/yarnpkg/yarn/issues/2821

**Comment by Mikelpineiro2024** [comment]
It is already solved, after doing yarn && grunt deployment load css and all correctly. Thank you!
