### ISSUE TITLE
Error: Mime type Not Allowed

### ISSUE THREAD

**Issue by GitHubUserWang** [matecat/MateCat#2736]
why is that. I use the edge browser.
![image](https://user-images.githubusercontent.com/93277083/233762209-6433167c-22eb-48bf-9121-cffff3fccab1.png)

**Comment by leonardotaddeitranslated** [comment]
Hi @GitHubUserWang could you please let me know if is this happening on a local installation of Matecat or on Matecat.com?
Thanks!
