### ISSUE TITLE
Unable to load the file

### ISSUE THREAD

**Issue by ccamato** [matecat/MateCat#2775]
Hello, 

I wanted to bring up an issue that we have encountered from time to time regarding the file update process, as shown in the attached screenshot. We often face a situation where the file gets stuck in a loading state and fails to proceed further. I would like to inquire if this is a known bug within the system. Additionally, I am interested to know if there is any workaround or alternative approach to address this issue effectively.

![Screenshot 2023-05-17 at 16 16 40](https://github.com/matecat/MateCat/assets/133851076/7ee0eab4-6ed2-4074-9f6f-403187074f40)

**Comment by riccio82** [comment]
Hi @ccamato,

you can write to support (support@matecat.com) for this kind of problems.

Thanks
