### ISSUE TITLE
In Revise mode, auto-skipping to the next unapproved segment does not work if none are in memory

### ISSUE THREAD

**Issue by felixvd** [matecat/MateCat#28]
Normally, approving a segment skips to the next unapproved segment. This does not work if no unapproved segment is left in the current view. Instead, the segment below the last is opened. The workaround is to click on the progress bar manually (this sometimes takes a few clicks for some reason) until the next unapproved segment is selected.

This issue is especially inconvenient in large jobs where auto-propagate fills in many segments, and remaining segments may be strewn throughout the document, requiring many skips. It forces the user to do the skipping manually and also to keep an eye on the segments' current status, or they risk re-reviewing their work and wasting time.

A quick fix would be to simply call the same function as the progress bar if no unapproved segment is found in current memory.

**Comment by antoniofarina** [comment]
Investigating: assigned to the engineer

**Comment by Ostico** [comment]
Skip to next unapproved ( translated ) segment.

Fixed in the next release. 1.0.1
