### ISSUE TITLE
Matecat represents the U+2009 THIN SPACE character as a tag

### ISSUE THREAD

**Issue by RayCulp** [matecat/MateCat#2839]
We have a client who uses the U+2009 THIN SPACE character on either side of every forward slash (/) when the slash separates two options, i.e. "either / or", "this / that".

Matecat represents the U+2009 THIN SPACE character as a tag.

In some cases, it makes sense to replace the slash in the translated text with the word "and". In these cases, it also makes sense to replace the THIN SPACE characters with regular spaces.

However, since they are tags, it does not appear to be possible to simply omit them. It also not optimal to move them to the end of the segment where they will cause two THIN SPACES to be added at the end because this will have to be cleaned up after exporting the translation to the original file format.

**Comment by riccio82** [comment]
Hi @RayCulp,

can you write to support (support@matecat.com) sending a sample link of a job or a file to recreate the problem?

Thank you
