### ISSUE TITLE
Feature request: Option to hide approved segments in Review mode

### ISSUE THREAD

**Issue by felixvd** [matecat/MateCat#29]
Large jobs can involve enormous amounts of repetition. This is what CAT tools are theoretically most useful for, but reviewing large jobs in Matecat becomes tedious when unapproved segments become sparse. After approving a segment, the user often has to wait for a new view to load to access the next unapproved one, which adds up to a lot of waiting and clicking.

If only unapproved segments appeared in the segment queue, the wait between finding unapproved segments would be eliminated, which can speed up reviews in large jobs immensely(!).

In terms of implementation, the server could be asked to send only unapproved segments, and the client could assemble them into a temporary view.

**Comment by antoniofarina** [comment]
My solution is to add the button T+>> even in the revision page.
Such button, in the translate page, allow to jump to the next untranslated segment.
In the review page it will allow to jump to the next unreviewed segment.

**Comment by antoniofarina** [comment]
I deleted my previuos comment. I misunderstood.

Showing only unapproved segments will result in a loss of context this could reduce the quality of the review.

I forward the question to the product management.

**Comment by felixvd** [comment]
First off, I got your deleted comment in an email update, and I find it very relevant for issue #26. What you described in the deleted comment is actually the current intended behavior of the Approve button in review mode (it is just not working quite right because of #28). 

Regarding your newer comment, I agree that seeing the segment in context is usually useful. To be honest, this feature request was born of frustration with the interface's speed during review, and if progressing/skipping to the segments was *fast*, implementing something like it might not be worth the hassle. It just has to be *seriously fast*, and it seemed like this might be the easiest way to get to something *seriously fast*.

**Comment by marcotrombetti** [comment]
@alessandrocattelan I think this is in your hands.

Skip or Add to roadmap?

**Comment by alessandrocattelan** [comment]
We are already working on a filtering solution as part of the customisation tasks for one of MateCat's enterprise users. The feature will be added to a separate branch of MateCat and will probably also make it to the master branch.

**Comment by riccio82** [comment]
You can filter segments by status or other conditions to see only the ones you want.
