### ISSUE TITLE
Installation guide isn't updated

### ISSUE THREAD

**Issue by tyfnacici** [matecat/MateCat#2929]
When I try to install matecat with the guide with this [address](https://site.matecat.com/installation-guide) on my local server (Ubuntu 23.04) it gives error. Can you guys please update it?

**Comment by riccio82** [comment]
What kind of error?
If you give us more information, it is easier to help you.

**Comment by riccio82** [comment]
We migrated to webpack, there are commands to build in the package.json.

` "scripts": { "format": "prettier --write .", "lint": "eslint --ignore-path .gitignore .", "test": "jest --watchAll", "coverage": "jest --coverage", "prepare": "husky install support_scripts/husky", "watch": "webpack --mode development --watch", "build:dev": "webpack --mode development", "build:production": "webpack --mode production" },`
