### ISSUE TITLE
The interface slows down progressively.

### ISSUE THREAD

**Issue by felixvd** [matecat/MateCat#30]
This is because old segments, which all hold a copy of the editor class (why?), are kept on the page as new ones are loaded. This causes the memory footprint to grow and the interface to get progressively slower, until the user reloads. I posted a video showcasing the slow performance in issue #18 : https://www.youtube.com/watch?v=yiQl2pvmcak 

Keeping old segments in memory would not be an issue if it did not affect performance significantly, but currently it does. I suggest that old segments at the top of the page be discarded after a maximum number of segments has been loaded. The number can be a user-specific setting.

**Comment by antoniofarina** [comment]
The analysis is correct but the solution is not applicable.

We tried to do it in the first stages of the interface development but it didn't works.
What happens is that when you remove old segments from the top of the page, while you are scrolling down, cause the interface scroll in a uncontrollably way.

We are aware of the performance problem: there is a maximum number of segment that are loaded in the interface: after this amount the page is automatically reload.

We will review this process to check
- if it works as expected
- if the max number is overestimated

Could you report the characteristics of the PC you are using in order we can contextualize the benchmark?

**Comment by felixvd** [comment]
The computer I recorded the video on is a "late 2012 iMac" with 2.7 GHz Intel Core i5 and 8 GB 1600 MHz DDR3 RAM. I regularly notice slowdown after 5-20 minutes, depending on my speed and the amount of segments (sections with lots of autopropagated segments take less time to go through). It is not very fast to start with, though.

I had been using a 2013 Macbook Air with an i5 4 GB RAM before, but I had to switch to the desktop computer because it was too slow.

Really, neither of those machines should buckle under the load of a text-based browser application, but that's part of a more general issue.

**Comment by antoniofarina** [comment]
We will explore the issue of the wild scroll during the segment approval.

The scrolling caused the the removing of many segments from the top is much more "invasive" than this.
We are restoring the feature that automatically refresh the page when more than X segments are present in the page

**Comment by marcotrombetti** [comment]
@antoniofarina was this solved with the automatic refresh?

**Comment by Ostico** [comment]
Should be fixed in next release. ( v1.0.1 )
