### ISSUE TITLE
Matecat installation guide not updated

### ISSUE THREAD

**Issue by musaibahmedrazzaqui** [matecat/MateCat#3087]
Hi im unable to run the command of grunt deploy as mentioned in the installation guide. The error probably is that there is no currently gruntfile.js in the current repo. What is the possible solution for this? Any workaround tog et matecat up and running?
I even copied a Gruntfile.js from a previous commit on the repo, and it still fails. I'm trying to get it running on my Ubuntu 20.04 on localhost, which means my /home/matecat/matecat/inc/config.ini looks like this:
```
`ENV = "production"
CHECK_FS = no
[production]
CLI_HTTP_HOST = "https://localhost"
COOKIE_DOMAIN = "localhost"
ENABLE_MULTI_DOMAIN_API = no
DB_SERVER = "localhost"
DB_DATABASE = "matecat"
DB_USER = "matecat"
DB_PASS = "matecat01"
REDIS_SERVERS = "tcp://localhost:6379"
QUEUE_BROKER_ADDRESS = "tcp://localhost:61613"
QUEUE_DQF_ADDRESS = "tcp://localhost:61613"
QUEUE_JMX_ADDRESS = "http://localhost:8161"
QUEUE_CREDENTIALS = "admin:admin"
SSE_BASE_URL = "localhost/sse" 
STORAGE_DIR = "/home/matecat/matecat/storage" 
SMTP_HOST = 'localhost'
SMTP_PORT = '25'
SMTP_SENDER = 'no-reply@matecat.loc'
SMTP_HOSTNAME = 'localhost'
; Filters Configuration
FILTERS_ADDRESS = 'https://translated-matecat-filters-v1.p.rapidapi.com'
FILTERS_RAPIDAPI_KEY = "your RapidAPI Key"
; THIS SHOULD BE YOUR LEXIQA LICENSE, Request your license key at
; @see http://www.lexiqa.net
LXQ_LICENSE = false
LXQ_PARTNERID = false
FILE_STORAGE_METHOD = 'fs'
#TRACKING_CODES_VIEW_PATH = "internal_scripts/tracking_codes/"
````

I've also changed the your_domain.com to localhost in other config files. When i visit https://localhost on my browser, its showing this:

This page isn’t workinglocalhost is currently unable to handle this request.
HTTP ERROR 500

how to solve this? My server logs in the nodejs folder do not show any errors as well

**Comment by riccio82** [comment]
We migrated to webpack, there are commands to build in the package.json.

` 
"scripts": {
    "format": "prettier --write .",
    "lint": "eslint --ignore-path .gitignore .",
    "test": "jest --watchAll",
    "coverage": "jest --coverage",
    "prepare": "husky install support_scripts/husky",
    "watch": "webpack --mode development --watch",
    "build:dev": "webpack --mode development",
    "build:production": "webpack --mode production"
  },
`
