### ISSUE TITLE
The @ upload modifier should be replaced by CURLFile object above php 5.6.

### ISSUE THREAD

**Issue by yifanjiang** [matecat/MateCat#309]
It was aware that the curl option CURLOPT_SAFE_UPLOAD is set to true by default:

```
lib/Utils/Filters.php-41-            if ( PHP_MINOR_VERSION >= 5 ) {
lib/Utils/Filters.php-42-                /**
lib/Utils/Filters.php-43-                 * Added in PHP 5.5.0 with FALSE as the default value.
lib/Utils/Filters.php-44-                 * PHP 5.6.0 changes the default value to TRUE.
lib/Utils/Filters.php-45-                 */
lib/Utils/Filters.php:46:                $options[ CURLOPT_SAFE_UPLOAD ] = false;
lib/Utils/Filters.php-47-            }
```

However it doesn't really help much for a php5.6 environment. e.g. trying to upload a file from the upload page (front page) will lead to a file uploaded with unexpected file content, in which only the file path prefixed by an '@' instead the real file content resides.

So I guess something like this will be more usable:

```
- lib/Utils/Filters.php:            'documentContent' => "@$filePath",
+ lib/Utils/Filters.php:           if ( PHP_MINOR_VERSION >= 6 ) {
+ lib/Utils/Filters.php:                'documentContent' => new \CURLFile($filePath),
...

```

**Comment by Ostico** [comment]
@yifanjiang tnx, we will update with this patch

**Comment by SimZal** [comment]
@yifanjiang Can you confirm that the fix works for you?

**Comment by yifanjiang** [comment]
@SimZal Thanks for the fixing :-) It looks great! I could hardly manage a environment to do it last week, but I'll try to verify the fix very soon!

**Comment by yifanjiang** [comment]
Verified by cherry-pick to 1.0.5. Thank you!
