### ISSUE TITLE
Bug? | Anyone can modify a project with the URI

### ISSUE THREAD

**Issue by isanfeliu** [matecat/MateCat#3211]
Hello,

We have observed that anyone with the link of the translation page of one project can modify it regardless of whether it has been added to the team or not, and also can translate it without being logged in.

We doubt if this feature is intended or not, but as teams exist in matecat, for security reasons we believe, this issue makes them irrelevant, as people doesn't need to be invited or even logged to modify the data of the projects, as they only need the link which can be easily spread, by mistake for example.

We have already changed the passwords (URI) of the projects but testing, the link can be accessed from unwanted users.

I attach the history, as you can see, some anonymous users have logged in the project (we keep them hidden as we know they have not came with bad intentions)

![History](https://github.com/matecat/MateCat/assets/32137776/226120d8-b5be-4e29-bec2-59a914e48eab)

Steps to reproduce the issue:

1- Upload a project (It can be stored on a team or in personal workspace)
2- Paste the link on one incognito window which has no session logged in 
or
2- Paste the link in another browser with another user account which has not been invited to the team.
3- User can modify and translate at pleasure

This is how it looks when you reproduce this issue:
-In incognito tab:
![Incognito Tab](https://github.com/matecat/MateCat/assets/32137776/04564672-90f0-414e-825b-c725db3de215)

-From another logged account view:
![Another account](https://github.com/matecat/MateCat/assets/32137776/dfbf79a4-fae0-499a-b791-8225103abb9c)

**Comment by isanfeliu** [comment]
it seems that is intended, i'll close the issue

**Comment by riccio82** [comment]
Yes, It was intentionally done this way.

**Comment by leonardotaddeitranslated** [comment]
Hi @isanfeliu Matecat links can be opened by anyone they have been shared with.
This choice has been made to make collaborating on Matecat links as easy as possible.
If a project is in a team you're a member of, though, you can see it listed in your "My projects" page and have access to advanced settings such as changing job password, archiving/cancelling projects etc.
Let me know if you still have any questions about this, please.
Thanks!
