### ISSUE TITLE
Outdated Installation Guide

### ISSUE THREAD

**Issue by Uniii** [matecat/MateCat#3246]
Is there an updated installation guide that can be used for Ubuntu 22+ with MySQL 8+?

There are numerous steps that are not compatible with MySQL 8.

**Comment by rbm2023** [comment]
During the installation you will encounter numerous problems that you will have to troubleshoot. The mysql version 5.7.36 in the guide is deprecated so you install, in my case, by default v 8.0.36, you have to fix syntax problems in the matecat.sql file in the INSTALL folder. There are syntax problems when creating users, but also when granting permissions. Do a little research and you will get it out. 

What php, nodejs version have you installed?

**Comment by simoesv** [comment]
@rbm2023 
I'm also having some issues upon installation. Do you know if there is some kind of compilation/list of the fixes that are required for most recent software versions?

In my case I installed:
- PHP 7.4.33
- mysql  Ver 14.14 Distrib 5.7.42, for Linux (x86_64)
- nodejs v8.10.0
- Redis server v=7.2.4
- Ubuntu 20.04.4 LTS

**Comment by riccio82** [comment]
Updated: [https://site.matecat.com/installation-guide](https://site.matecat.com/installation-guide)
