### ISSUE TITLE
MateCat: I can't analyze files  "engine is no longer active"

### ISSUE THREAD

**Issue by Elisa694** [matecat/MateCat#3253]
I created a project, added ModernMT, created a new TM, added files, but tryin' to "analyze" it says "engine is no longer active".

**Comment by Ostico** [comment]
Hi @Elisa694,

We've identified the issue and are actively working to resolve it.

For this type of report or for support requests not directly related to the code, please reach out to us at support@matecat.com or use the support chat on [www.matecat.com](http://www.matecat.com/).

Thank you!

**Comment by Elisa694** [comment]
Thank you so much!

**Comment by Ostico** [comment]
@Elisa694 

FYI, the issue is fixed!!
