### ISSUE TITLE
Connection to server gets lost randomly (Review mode)

### ISSUE THREAD

**Issue by felixvd** [matecat/MateCat#33]
This has happened to me at least 10 times today and 3 times in the last hour. Approved segments stop turning green, and waiting for 10-30 minutes does not change their status. There is no warning or alert for this, and there seems to be no fix except reloading the page. After the reload, approving segments works fine, but the segments that were not yet transmitted are lost.

It should go without saying that losing users' work is a severe bug, and that this behavior is severely frustrating.

I have a hunch that it is connected to #20, because it seems to happen most often when I am progressing fast through the segments. That might well just be confirmation bias, however. I could not reproduce this reliably yet, but then again there is no connection information displayed in the client that would help with doing so.

While the underlying issue is being fixed, a temporary hotfix that shows an alert when more than X segments are queued for the server would be much appreciated.

**Comment by felixvd** [comment]
Don't want to be flippant, but I just lost another half hour worth of corrections because I forgot to check constantly if my segments turn green. Why is there no warning?

**Comment by marcotrombetti** [comment]
Closing.

Please re-open is the problem persist.
