### ISSUE TITLE
Oauth fails on blank dialog

### ISSUE THREAD

**Issue by mirko33** [matecat/MateCat#331]
Installed Matecat  1.5.0h on Ubuntu 14.04. Everything seems to be working as expected except for Google authentication. Followed the instructions and am pretty sure everything is correct in terms of Google API Console and oauth_config.ini, but am unable to log on. When clicking Sign In Using Google, I get the usual Google dialog (which in my case lets me choose among the couple of Google accounts I own), once I choose an account, I get the approval prompt (Deny/Allow), and once I hit Allow, an empty window opens with the following URL: http://translate.translatorswithoutborders.org/oauth/response?code=4/XXXXXXXXXXXXXXXXXXXX (where XXXXXXX replaces the key). This window stays open and the authentication does not complete. 
Seen as the oath code was modified recently, I wondered if there is something broken in the code rather than in my configuration.

**Comment by FrancescoE** [comment]
Hi Mirko,
type following commands from terminal:
-cd ~pathYourMatecat
-php composer.phar install (this will update the project dependencies and install everything that is missing)

**Comment by mirko33** [comment]
I first went into the matecat/cattool folder, then ran php composer,phar install and got a runtime exception ([RuntimeException] /home/matecat/cattool/vendor/phpdocumentor/reflection-docblock does not exist and could not be created). So I ran git pull origin master, followed by php -r "readfile('https://getcomposer.org/installer');" | php (logged in as Matecat). Then I ran again php composer,phar install but got the same runtime exception as above. So ran it again as root which worked though with the warning ("Do not run Composer as root/super user!").
But the Google authentication still doesn't work :-(

**Comment by Ostico** [comment]
Hi @mirko33 ,
can you confirm that you followed this guide to enable GDrive?

http://www.matecat.com/advanced-manual-setup/#egl

**Comment by mirko33** [comment]
Yes, those are the instructions I followed.

**Comment by mirko33** [comment]
Updated to 1.0.6b, still the same.

**Comment by Ostico** [comment]
Hi @mirko33 ,

please check inside the application log to give us more debug info.

If you not changed the default, logs should be here:
<matecat_path>/storage/log_archive/

**Comment by mirko33** [comment]
In php_errors.txt I found the following:
>>
[09-Aug-2016 09:16:44 Europe/Rome] PHP Notice:  Undefined index: gdriveFileList in /home/matecat/cattool/lib/Controller/GDriveController.php on line 242
[09-Aug-2016 09:16:44 Europe/Rome] PHP Warning:  Invalid argument supplied for foreach() in /home/matecat/cattool/lib/Controller/GDriveController.php on line 244
[09-Aug-2016 09:33:54 Europe/Rome] PHP Warning:  fopen(/home/matecat/cattool/inc/oauth-token-key.txt): failed to open stream: Permission denied in /home/matecat/cattool/lib/Utils/DefuseEncryption.php on line 55
[09-Aug-2016 09:33:54 Europe/Rome] PHP Fatal error:  Uncaught exception 'Exception' with message 'Failed to open the file.' in /home/matecat/cattool/lib/Utils/DefuseEncryption.php:58
Stack trace:
#0 /home/matecat/cattool/lib/Utils/DefuseEncryption.php(21): DefuseEncryption->createEncryptionKey()
#1 /home/matecat/cattool/lib/Utils/OauthTokenEncryption.php(19): DefuseEncryption->__construct('/home/matecat/c...')
#2 /home/matecat/cattool/lib/Controller/oauthResponseHandlerController.php(27): OauthTokenEncryption::getInstance()
#3 /home/matecat/cattool/lib/Controller/AbstractControllers/controller.php(54): oauthResponseHandlerController->__construct()
#4 /home/matecat/cattool/index.php(7): controller::getInstance()
#5 {main}
  thrown in /home/matecat/cattool/lib/Utils/DefuseEncryption.php on line 58
<<
So could this a problem of using sudo and matecat during the installation process?

**Comment by Ostico** [comment]
Hi @mirko33 ,
i agree, this could be a wrong permission on the ./inc directory.

```
PHP Warning: fopen(/home/matecat/cattool/inc/oauth-token-key.txt): failed to open stream: 
Permission denied in /home/matecat/cattool/lib/Utils/DefuseEncryption.php on line 55
```

You should check that the user under which your webserver runs has the write permission on the directory ./inc

**Comment by mirko33** [comment]
Thanks, yes, changing write permission on that folder fixed it. What would be the right configuration though? Should this folder be owned by matecat or www-data? And if by matecat, does it have to be writable by any user?

**Comment by Ostico** [comment]
In our servers the web server runs as ```www-data```.

The permissions on the directories are set as:
```
drwxr-xr-x  8 www-data www-data    4096 lug 14 13:15 storage
```
the permissions on the **configuration** files are set as:
```
-rw-r-----  1 www-data www-data  4666 ago  3 20:12 config.ini
-rw-r-----  1 www-data www-data   136 ago  1 18:36 oauth-token-key.txt
```
and the permissions on the regular php files are set as:
```
-r--r----- 1 www-data root     32771 lug 25 18:10 setTranslationController.php
```
so, basically only ```www-data``` and ```root``` can write on disk.
