### ISSUE TITLE
Can't install Node 14 from Installation guide

### ISSUE THREAD

**Issue by NumBerNanA** [matecat/MateCat#3324]
i do Installation guide step by step and in Install Node 14
https://site.matecat.com/installation-guide#inj
```
Node.js is necessary to have a real-time chat within Matecat. Install it with:

    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash

```
and i got this error
![ภาพ](https://github.com/matecat/MateCat/assets/9784404/3b58a698-2c35-4661-b1f8-862b288491c3)

can i do to fix it?

**Comment by riccio82** [comment]
We need to update the documentation, the command is old, the updated one is :

`curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash`

You can install node 18 or 20.

Thanks for the report

**Comment by NumBerNanA** [comment]
thx but i try this command but is same respond

![ภาพ](https://github.com/matecat/MateCat/assets/9784404/9ec23ab4-d4e7-49c8-8966-306f4f500336)

i use lightsail aws
![ภาพ](https://github.com/matecat/MateCat/assets/9784404/5c5cc59d-4139-4a93-b39d-2810a8fe1af0)

and add HTTPS to firewall
![ภาพ](https://github.com/matecat/MateCat/assets/9784404/bb371030-8204-4a95-8783-e9de588d26cc)

but have this error
