### ISSUE TITLE
Splitting not working

### ISSUE THREAD

**Issue by mirko33** [matecat/MateCat#340]
Clean install of 1.0.5h on Ubuntu 14.04. Upload a file to start new project. Try to split into any number of parts, Split Job Into X Parts dialog keeps proposing numbers that don't add up (either "remaining" or "exceeding") and whichever manual changes are made to the per-part numbers, falls back to the same remaining or exceeding numbers, or in any case never lets the user "confirm". Note that the same files uploaded to matecat.com split just fine.

**Comment by mirko33** [comment]
Updated to 1.0.6b, still the same.

**Comment by Ostico** [comment]
Hi @mirko33 , 
we need more debug info on that. Can you send some screenshot and/or privately the link to your project?

**Comment by mirko33** [comment]
Thanks @Ostico, I'll send the link to the project to the Matecat support alias then.

**Comment by Ostico** [comment]
@mirko33 i seen you removed the "Payable" column in the table of analysis. This field is needed to perform the split, because the client takes the initial word value from this field.

I suggest, instead of removing it to hide if you do not need it.

**Comment by Ostico** [comment]
Hi @mirko33 , can i close this?

**Comment by mirko33** [comment]
Sorry, only saw your comment today. I didn't actually remove that column -- its presence or not depends on the value of ENABLE_OUTSOURCE in in INIT.php. I've enabled outsource now, but the problem persists.

**Comment by mirko33** [comment]
Hm. Now it IS working -- it didn't when I accessed the server through it's IP address. But using the proper URL, it is now working, after enabling outsourcing, that is.

**Comment by mirko33** [comment]
I don't understand the pattern. It's somehow related to both the ENABLE_OUTSOURCE but apparently also whether or I'm logged on. I'm closing for now, and will open a new one when I see clearer.
