### ISSUE TITLE
Split error "first chunk too large" for small numbers

### ISSUE THREAD

**Issue by mirko33** [matecat/MateCat#341]
As I didn't get splitting to work with a proper file, I tried splitting a small text file, first one containing 12 words, then one with 144 words. Both times I tried to split into two parts, and both times I got the error "The requested number of words for the first chunk is too large. I cannot create 2 chunks.", although the numbers proposed (6/6 and 72/72) seemed correct.

**Comment by Ostico** [comment]
Hi @mirko33 ,

the split function is supposed to work with large files, with these little files, instead, you should let the application decide on the words number for the splits.
