### ISSUE TITLE
MateCat installation

### ISSUE THREAD

**Issue by safiaa1** [matecat/MateCat#343]
Hi,
Please we need your help about Matecat installation.
We followed the manual "Advanced manual setup to install Matecat" (http://www.matecat.com/advanced-manual-setup/),all mandatory dependencies for MateCat are successfully installed,
But we have a problem when we try to access to matecat by localhost address, it shows nothing and if we check the matecat.error.log (/var/log/apache2/matecat.error.log)
it shows the error bellow:
*********************************
[Wed Aug 10 15:16:54.610318 2016] [:error] [pid 8175] [client ::1:41874] PHP Warning: array_merge(): Argument #2 is not an array in /home/matecat/cattool/lib/Utils/Utils.php on line 133
**********************************
Any help would be greatly appreciated, 
Thank you!

**Comment by safiaa1** [comment]
Hi @Ostico,
thank you
among these files which one I send you?
activity_log.log , fatal_errors.txt ,  php_errors.txt , TaskManager.log, tm_analysis_P3.log
err_mail.log ,log.txt ,qa_checks.log ,tm_analysis_P1.log ,fastAnalysis.log , mail_queue.log    set_contribution.log,  tm_analysis_P2.log

**Comment by safiaa1** [comment]
[log_archive.tar.gz](https://github.com/matecat/MateCat/files/411643/log_archive.tar.gz)

**Comment by Ostico** [comment]
Hi @safiaa1 can i close this?

**Comment by unasettimana** [comment]
Hi @safiaa1 , I think I'm facing the same problem as you were...can you help me to understand how did you resolve this? So many thanks!

**Comment by SynergiumEU** [comment]
we had a similar issue once we changed the bind in /etc/apache2/sites-available/matecat-vhost.conf
to anything els but what it's resolvable by dns

**Comment by meenakshi074** [comment]
![Screenshot from 2020-06-22 12-08-56](https://user-images.githubusercontent.com/60773852/85257154-01ac3580-b483-11ea-8e54-62efafe2fbdb.png)

Hi @safiaa1 , I think i am also facing the same issue. Can you please help me how did you resolve this issue? Thanks!

**Comment by meenakshi074** [comment]
![Screenshot from 2020-06-22 12-08-56](https://user-images.githubusercontent.com/60773852/85259316-79c82a80-b486-11ea-9785-381026642dc7.png)

Hi @Ostico ,
