### ISSUE TITLE
MateCAt installation. PHP Fatal error:  Class 'Google_Client' not found

### ISSUE THREAD

**Issue by safiaa1** [matecat/MateCat#344]
Hi,
I'm trying to install MateCat on my server (http://www.matecat.com/advanced-manual-setup/) but I have an error when trying to access to MateCat (http://localhost/), the browser not showing anything. The logs show me the error bellow:
""""""""""""""""""""
$ tail -f /home/matecat/cattool/storage/log_archive/php_errors.txt 

PHP Fatal error:  Class 'Google_Client' not found in /home/matecat/cattool/lib/Utils/OauthClient.php on line 23.
"""""""""""""""""""""""""

I'm not enabling Google+ login!!

Please how can I sole this issue?

Any help please.

Thanks.

**Comment by Ostico** [comment]
Hi @safiaa1 ,

you should install and update composer in order to manage the PHP dependencies.

Please in the matecat root try to run these commands:
```bash
php -r "readfile('https://getcomposer.org/installer');" | php
php composer.phar install
```

**Comment by safiaa1** [comment]
Hi @Ostico  ,
Thank you for your reply,

The first command has executed well and it downloaded composer.phar , but the second command shows me this:

""""""""""""""""""""
Composer could not find a composer.json file in ~/folder
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
"""""""""""""""""""""

As I read in  getcomposer documentaion, the composer.json  file should describes the dependencies of my project!

Please how can I fix this or where can I find this composer.json file?

**Comment by Ostico** [comment]
It is in the root of matecat codebase, you have not to create it, it is already present.
https://github.com/matecat/MateCat/blob/develop/composer.json

**Comment by safiaa1** [comment]
It is done, but the error remains the same:
"""""""""""""""""
$ tail -f /home/matecat/cattool/storage/log_archive/php_errors.txt

PHP Fatal error: Class 'Google_Client' not found in /home/matecat/cattool/lib/Utils/OauthClient.php on line 23.
"""""""""""""""""""

**Comment by safiaa1** [comment]
I was installed dependencies in /home/matecat but that not worked.
The issue is fixed by installing dependencies in /home/matecat/cattools.

Thanks @Ostico
