### ISSUE TITLE
API key in Moses machine translation

### ISSUE THREAD

**Issue by safiaa1** [matecat/MateCat#348]
Hi,
we need your help about using our own Moses machine translation with matecat tool :
we want to add our own MT engine (Moses),  there are three Required fields  which are :
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
*Engine name:
*URL:
*API key:
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

Our question is where we can obtain the API key?

Any help would be greatly appreciated, 
Thank you!

**Comment by Ostico** [comment]
Hi @safiaa1 , the api key is thought to be used as access control layer on the custom moses instances, if you have not such kind of implementation over your moses server you can fil it with any value you want. It should work.

**Comment by safiaa1** [comment]
Hi @Ostico ,
Thank you for your reply,
we faced an other problem with Adaptive MT server http://www.mt4cat.org/software/adaptive-mt-server when we tried this test(http://localhost/translate
?q="the Contracting Parties" &source=en&target=it&key=keyone) on a browser it didn't give us the translation, 
can you tell us also where we can find the log of Moses and MT server?

**Comment by safiaa1** [comment]
Thank you for your reply,
we faced an other problem with Adaptive MT server http://www.mt4cat.org/software/adaptive-mt-server when we tried this request : 
http://localhost/translate?q="the Contracting Parties" &source=en&target=it&key=keyone
normally it should give this:

{"data":
{ "translations":[{"translatedText": ”le Parti contraenti.”,
"phraseAlignment": [[[0],[0]],[[1,2],[1,2]],[[3],[3]]],
"sentence_confidence": "88.6097", ...

But it shows a response like:
{"data": {"translations": [{"systemName": "system_baseline", "segmentID": "0000"}]}}

Can you tell us also where we can find the log files of Moses and MT server?

**Comment by alessandrocattelan** [comment]
Hello @safiaa1 . The project you are referring too is not directly connected to the MateCat tool and I am afraid we cannot help you on this. However, if you send us your email address at support@matecat.com, we will put you in contact with the people who developed the adaptive MT server you are using.

**Comment by Ostico** [comment]
I close
