### ISSUE TITLE
Fail connection wiht Google Accounts 

### ISSUE THREAD

**Issue by FarenRavirar** [matecat/MateCat#3647]
When connecting my Google Gmail account, it displays the error: 503 Service Unavailable.
Oops! An error occurred... I have already cleared the cookies and tested in other browsers and in incognito window.

![image](https://github.com/user-attachments/assets/50aa21bb-6d6d-4340-95a1-3551f758ec7f)

Edit: I tried on other emails and even on another computer, and it also failed.

**Comment by jjacobhalbe** [comment]
Been facing the same issue all day. It seems that it's their issue, and there's nothing we can do about it. I've tried clearing up the cookies, been connecting from different networks and devices. Nothing seems to work.

**Comment by A7med205** [comment]
I didn't backup my projects elsewhere and now I can't access them... any help is appreciated.
