### ISSUE TITLE
Wonʻt get past Word Count Analysis

### ISSUE THREAD

**Issue by HURIMOZ** [matecat/MateCat#3677]
Matecat.com is not going past the word count analysis. the cursor is turning round and round and nothing happens.

**Comment by HURIMOZ** [comment]
Problem is gone now.

**Comment by riccio82** [comment]
If there are problems on the site, please contact the support from the chat that appears on all pages. The Issues here on github are for things that concern the open source code. 
If you write here about problems on the site you will not receive any answer.
Thank you

**Comment by HURIMOZ** [comment]
Is there any way I can delete this issue?

**Comment by riccio82** [comment]
No problem, I closed it.
Thank you
