### ISSUE TITLE
Why can only process XLIFF file?

### ISSUE THREAD

**Issue by neversion** [matecat/MateCat#37]
I deploy MateCat in my own server with the install.txt in github.
But in the homepage, I saw "Translate an XLIFF file", but not "Translate your files". And I can only upload XLIFF file.
Is there any more config for the application? 
And another question is pages such as opensource/faq  in https://www.matecat.com/  return with 502 error? So that I can't get any documents of the project.

**Comment by antoniofarina** [comment]
Hi, the opensource version only allow the translation of xliff files: the filters infrastructure is not included.
We are working to release them as a separate product. I think we will release them in the next 2 weeks.

**Comment by antoniofarina** [comment]
Regarding the second problem, please try to empty the cache and the cookies from your browser (or try with a different browser)

**Comment by neversion** [comment]
Got it. I also find the answer of first question in source code. 
And today, finally, I can visit those pages.

**Comment by marcotrombetti** [comment]
@neversion we release the open source filters here:
https://github.com/matecat/MateCat-Filters

They are beta, but we also have an hosted solutions. If you need support please contact giuseppe.silvano@translated.net

Closing.
