### ISSUE TITLE
API v2 returns "This project does not exist"

### ISSUE THREAD

**Issue by mirko33** [matecat/MateCat#370]
Our MateCat install responds as expected to the v1 API calls, not however v2. project-completion-status returns "This project does not exist" when called with something like http://<hostname>/api/v2/project-completion-status/10
Are there some additional steps needed to configure that API?

**Comment by mirko33** [comment]
OK, I suppose it's simply the lack of an API key. If there was some even very brief explanation somewhere how to configure the validation, that would be very useful.

**Comment by freegenie** [comment]
Hi Mirko, project-completion-status API should be used in conjunction with the project_completion feature that you can enable per user in MateCat. There are some utilities in `support_script/tasks` folder that help in the setup: 

1. generate_api_keys.php 
1. owner_features.php 

which you may already be discovered by your own. 

Steps are the following: 

1. create a user record by logging in with Google
1. add API keys to that user 
1. enable `project_completion` feature on that user
1. create projects taking care to let MateCat know who are you (by uploading files in the UI or by making an API call with your API keys in the header ).

Let me know if you need further help.

**Comment by mirko33** [comment]
Thank you, that's very helpful!
