### ISSUE TITLE
chmod: cannot access ‘www-data:www-data’: No such file or directory

### ISSUE THREAD

**Issue by Alf71** [matecat/MateCat#4]
Hi,

I managed to install MateCat in Ubuntu Server 14
Quite at the end, I'm finding some difficulties when entering:

chmod 400 www-data:www-data ~/cattool/inc/oauth_config.ini

I receive the message:

root@server:~/cattool# chmod 400 www-data:www-data ~/cattool/inc/oauth_config.ini
chmod: cannot access ‘www-data:www-data’: No such file or directory

Do you know the reason for this?

**Comment by matecat** [comment]
Hi.
They are two different commands to run

chown www-data:www-data ~/cattool/inc/oauth_config.ini
chmod 400  ~/cattool/inc/oauth_config.ini

Antonio


*Antonio Farina Head of Engineering*
http://www.translated.net Direct: (+39) 06 90 254 213 Main: (+39) 06 90 254
001 Fax: (+39) 06 233 200 102

2015-01-20 22:12 GMT+01:00 Alf71 <notifications@github.com>:

**Comment by Alf71** [comment]
Thanks. This time it worked.
I installed MateCat in a server where ISPconfig3 was already running.
Perhaps this is the reason I am not getting access when calling IP "192.168.0.120" (the server localhost)...
I will try again with a clean installation of ubuntu 14.04
