### ISSUE TITLE
T+>> fails if the next segment is identical to the current one

### ISSUE THREAD

**Issue by felixvd** [matecat/MateCat#40]
In the example arrangement below, translating segment 1 and pressing the T+>> button will jump to segment 3. However, since the translation auto-propagates from segment 1 to segment 3, T+>> opens an already translated segment.

...
Segment 1 / Content A
Segment 2 / Content B (already translated)
Segment 3 / Content A
...

Obviously this behavior is not intended and causes unnecessary button presses for the user. A solution would be to compare the content of the next segment to the last submitted one locally, and continue the search for an untranslated segment if it is identical.

A similar problem exists in Revise mode, see issue #17.

**Comment by marcotrombetti** [comment]
Good point.

We will add this to the todo.

Marco

**Comment by marcotrombetti** [comment]
Added to the roadmap.
