### ISSUE TITLE
Error when testing in virtual machine

### ISSUE THREAD

**Issue by neversion** [matecat/MateCat#41]
I download the VirtualBox 5.0 version, and import to my machine. Everything going well.
But when start to test for translation, I got 2 strange error.
1. "Fast word counting.." never stop, and the Split button never turn enable.
![2015-12-11 6 03 26](https://cloud.githubusercontent.com/assets/3972614/11741068/89717e50-a031-11e5-8aa5-d0a332d36c19.png)

2. click the translate, open the translator page. Nothing in the page but the top bar and bottom bar with "calculating word count..."
![2015-12-11 6 04 35](https://cloud.githubusercontent.com/assets/3972614/11741194/381d20a8-a032-11e5-8b55-2d230be7f06e.png)

**Comment by Ostico** [comment]
Hi @neversion neversion,

it looks like the the analysis daemons are not started.

Open a shell inside your virtual machine and run:
```bash
killall -9 screen
killall -p php
```

after that follow this guide to restart daemons:
http://www.matecat.com/advanced-manual-setup/#totad

**Comment by neversion** [comment]
It didn't work for me, even after systen reboot. Below are some responsed message:
sudo killall -9 screen 
screen: no process found
sudo killall -p php 
php:no process found

/bin/bash /home/matecat/cattool/daemons/restartAnalysis.sh
fast was not running
tm was not running
No demons found to kill!
spawning daemons

After what I have done before: 
ps aux |grep php
lot of AnalysisThreadChild.php thread

ps aux |grep fast
SCREEN -d -m -S fast php fastAnalysis.php

**Comment by marcotrombetti** [comment]
Lorenzo Dolfi is working on an updated Virtual Machine.

@Lyonard @antoniofarina please coordinate with Lorenzo for this.
