### ISSUE TITLE
Where I can get OAUTH_BROWSER_API_KEY?

### ISSUE THREAD

**Issue by eclavelr** [matecat/MateCat#413]
@Ostico 

See this line
https://github.com/matecat/MateCat/blob/master/inc/INIT.php#L231

In Advanced manual setup http://www.matecat.com/advanced-manual-setup/#egl  and https://github.com/ProZcom/matecat-proz/blob/master/INSTALL/INSTALL.txt#L104
Is never mentioned where I can get OAUTH_BROWSER_API_KEY.
In these documents only talk about OAUTH_CLIENT_ID, OAUTH_CLIENT_SECRET and OAUTH_CLIENT_APP_NAME.

**Comment by Ostico** [comment]
You can generate key in the same panel of the OAUTH_CLIENT_ID

See the screenshot attached.

We will update the documentation as soon as possible.

![credentials_-_matecat-development](https://cloud.githubusercontent.com/assets/8008416/18680420/f104ce16-7f63-11e6-8f22-ff7e43fac908.png)
