### ISSUE TITLE
Please, provide an updated virtual machine. http://www.matecat.com/installation-guide/#getstart

### ISSUE THREAD

**Issue by eclavelr** [matecat/MateCat#415]
@Ostico 

Please, provide an updated virtual machine. http://www.matecat.com/installation-guide/#getstart
The provided version of this virtual machine is very old (0.5.9c). The actual version is [1.0.7b](https://github.com/matecat/MateCat/blob/develop/inc/version.ini). 
"http://www.matecat.com/advanced-manual-setup/" has some issues, i did exactly the same said in Advanced manual setup http://www.matecat.com/advanced-manual-setup/ and still can not started to use. 

For example, once i have uploaded a file and click in button "analyze" this error is shown.
![github](https://cloud.githubusercontent.com/assets/18006411/18687133/bd5d0126-7f4c-11e6-9c79-947828f367c2.png)

Also, I have all the time this php error
``
[20-Sep-2016 22:30:58 Europe/Rome] PHP Notice:  Undefined index: en-us in /home/matecat/cattool/lib/Utils/Langs/Languages.php on line 110
[20-Sep-2016 22:30:58 Europe/Rome] PHP Notice:  Undefined index: uid in /home/matecat/cattool/lib/Controller/newProjectController.php on line 340
[20-Sep-2016 22:30:58 Europe/Rome] PHP Notice:  Undefined index: gdriveFileList in /home/matecat/cattool/lib/Controller/GDriveController.php on line 242
[20-Sep-2016 22:30:58 Europe/Rome] PHP Warning:  Invalid argument supplied for foreach() in /home/matecat/cattool/lib/Controller/GDriveController.php on line 244
``

I would like commit contributions, but first I need install MateCat or get something functional following the manual.

**Comment by Ostico** [comment]
@eclavelr this is the latest virtual machine we produced, http://www.matecat.com/vm/matecat_latest-VBox-5.1.ova

MateCat version 1.0.7

Anyway, the exception trace you pasted is not related with your error, it is related to a MySQL issue when segments are inserted in the database, maybe there is some misconfiguration. 

Which version of MySQL you are using?

**Comment by eclavelr** [comment]
@Ostico I'm using mysql  Version 14.14 Distrib 5.7.15, for Linux (x86_64)

I can see now you are providing an updated virtual machine version at http://www.matecat.com/installation-guide/#downloadvm
Would be usefull if you write right there what version is in that virtual machine.

**Comment by Ostico** [comment]
@eclavelr check you mysql, version 5.7 must be started in a custom configuration in order to work with matecat.

Disable the strict mode by changing the configuration file of MySQL ( my.cnf ) and reboot the mysql.

```
#force connection utf8 for the clients
init_connect='SET NAMES utf8'
skip-character-set-client-handshake

# Disable the MySQL 5.7 default strict mode
sql-mode="NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
explicit_defaults_for_timestamp=true
```

Let me know if this is enough and the issue is solved.

**Comment by Ostico** [comment]
Close
