### ISSUE TITLE
There are a problem if my mysql is using GMT and in INIT.php is usign 'Europe/Rome'

### ISSUE THREAD

**Issue by eclavelr** [matecat/MateCat#416]
@Ostico 

There are a problem if my mysql is using GMT and in INIT.php is using 'Europe/Rome'
`public static $TIME_ZONE = 'Europe/Rome';` 
See
https://github.com/matecat/MateCat/blob/master/inc/INIT.php#L102

Should be the equals?

**Comment by Ostico** [comment]
@eclavelr , there is no problem on such configuration, we have the same configuration too.
