### ISSUE TITLE
Why .xlf tags are not locked in develop branch and how to lock them as in matecat.com

### ISSUE THREAD

**Issue by wsuphappyhour** [matecat/MateCat#420]
Hi, 

We want to know why tags are presented differently between matecat.com and develop branch.
In develop branch they aren't locked.

Sample:
Matecat.com
![image](https://cloud.githubusercontent.com/assets/20355306/18710000/95df2d58-800b-11e6-8cda-afbd06af6ddc.png)

Develop branch
![image](https://cloud.githubusercontent.com/assets/20355306/18710013/abc430a0-800b-11e6-95f6-a1a9c500db12.png)

As suggested we did not deployed Matecat-filters and are using API instead

Sample .xlf file attached.
[tags sample.zip](https://github.com/matecat/MateCat/files/484920/tags.sample.zip)

If you have any questions please do ask
Thank you for your help!

**Comment by Ostico** [comment]
Hi @wsuphappyhour , matecat can handle by yourself the xlf files without sending them to the conversion filters ( you are using Mashape key i guess ).

To force the xlf files to be converted and to remove these tags by MateCat-Filters you should add this key in configuration file **"./inc/config.ini"** :
```
FORCE_XLIFF_CONVERSION = yes
```

Let me know if this solves your issue.

**Comment by wsuphappyhour** [comment]
Hi, sorry for late replay, but the problem still persists.

I have edited "./inc/config.ini"
as follows:
![image](https://cloud.githubusercontent.com/assets/20355306/18791013/baf318ca-81b9-11e6-992f-6154b1fb62d7.png)

and restarted apache
apache2ctl restart

Did I miss something?

Thanks!

**Comment by wsuphappyhour** [comment]
Update:

It seems your fix works but only if Source language is English(en-gb) if it is English(en-us) tags are not locked:

file's languages:
![image](https://cloud.githubusercontent.com/assets/20355306/18814578/4e2b8fb6-8320-11e6-825c-027cbe41deb4.png)

en-gb -> et-ee
![image](https://cloud.githubusercontent.com/assets/20355306/18814587/830fb90a-8320-11e6-904a-3939f8eee3f9.png)

en-us -> et-ee
![image](https://cloud.githubusercontent.com/assets/20355306/18814591/979e1394-8320-11e6-89ae-03b8b7f73c22.png)

For now we will use only en-gb.

Thanks again for your help!

**Comment by Ostico** [comment]
You have to clean the conversion cache, it is based on file checksum and target language. So to invalid it you can delete it, change source language or modify the file ( addind a space for example will change the checksum )

**Comment by Ostico** [comment]
You have to clean the conversion cache, it is based on file checksum and target language. So to invalid it you can delete it, change source language or modify the file ( adding a space for example will change the checksum )
