### ISSUE TITLE
Hi we want to disable two features by default each time project is created.

### ISSUE THREAD

**Issue by wsuphappyhour** [matecat/MateCat#431]
Hi, 
We want to disable two features by default each time project is created.

**First one** is  that by default MT won't be applied(unchecked):

![image](https://cloud.githubusercontent.com/assets/20355306/18809386/6b107504-8282-11e6-947c-e80a447c3c37.png)

input tal:condition="php: page == 'home'" type="checkbox" checked="**checked**"
If i delete **checked** it still applies MT

**Second one** we would like to disable suggestions from **Public TM.**
Thanks!

**Comment by Ostico** [comment]
Hi @wsuphappyhour ,

to respond to your questions:

First question:
Is not enough to disable the checked flag, you have to remove the css class "activemt" from the corrisponding TR tag `<tr class="activemt" data-id="1">`


Second question: 
sorry but is not possible to remove TM server by default without some customizations.
