### ISSUE TITLE
Approving segments in a completed review fails

### ISSUE THREAD

**Issue by felixvd** [matecat/MateCat#44]
When all segments in a review are completed and you try to approve a segment, the selection jumps to the start of the page. This makes it almost impossible to correct a review after the fact. See [here](https://youtu.be/fzQGJ3jbpPQ) for a video.

Solution: Split the "Approve" and "Go to next unapproved segment" functions into two buttons, like it is done for the Translate view.

As a side note regarding performance, this was done on a top of the line PC.

**Comment by antoniofarina** [comment]
Hi Felix, than you for reporting.

I think the best solution for this situation could be: if there are not other unrevised segments, the click on APPROVE simply jump to the next segment.

I put it in roadmap

**Comment by Ostico** [comment]
Fixed.

Close.
