### ISSUE TITLE
Hi, is it possible to show full file in the editor with CM, Source=Target, locked segments

### ISSUE THREAD

**Issue by wsuphappyhour** [matecat/MateCat#442]
Hi, 

Is it possible to show full file in the editor with CM, Source=Target, locked segments etc. Because now by default MateCat loads only untranslated segments and fuzzy matches segments so for translator some of a context is missing.

Thanks!

**Comment by Ostico** [comment]
Hi @wsuphappyhour ,

can you clarify your question please?

**Comment by wsuphappyhour** [comment]
For example .sdlxliff file has 1000 segments of which 500 segments have 100% Context match segments and 500 segments are untranslated or fuzzies. when we upload to Matecat only 500 segments are displayed for translation not 1000. For editors and translators it would be good to see full file to get idea on the context.  Is this more clear?
I know it's more scroling but they can use shortcuts to skip to the next untranslated segment.

Thanks!
