### ISSUE TITLE
Hi, we get error while trying to download imported tmx memories.

### ISSUE THREAD

**Issue by wsuphappyhour** [matecat/MateCat#455]
Hi, we get error while trying to download imported tmx memories.

Another question if  we upload 2 TMX files with language combination en-GB-de-DE and en-US-de-DE will en-GB segments be used in en-US project?

What is storage limit for  TMX as I understand they are not stored locally 

Thanks!

**Comment by wsuphappyhour** [comment]
We also get errors while importing. Can it be server issues? Is there possibility to store them locally to avoid it?
What are the policies for uploaded content will it be re-used in **any** way without our consent?

Thanks!

**Comment by Ostico** [comment]
Hi @wsuphappyhour ,
no is not possible to store tmx locally. 

For the download errors you got, i think it was a temporary issue, import/export TMX is an heavy task, we are planning to improve it.

Uploaded content is tied to your Private Key ( yes it is visible in your screenshot and i deleted it ). So pay attention on secure your Private Keys. Only you can benefit from your memories.

Your content is used by us ONLY for statistical and big data analysis. Your private data are not shared in any way.

There is no limit on TMX dimensions we worked with TMX of 80GB.

For your first question: 
> Another question if we upload 2 TMX files with language combination en-GB-de-DE and en-US-de-DE will en-GB segments be used in en-US project?

Language dialects should ensure that no en-US memories will be used for en-GB projects, if you find some issues on that please write us.

**Comment by wsuphappyhour** [comment]
Hi,

We still get these errors randomly:
"Upload::_uploadFile -> File Dimensions Not Allowed" (while files are less then <300mb)
"Can't upload right now. Try again"
Most frequent: "Can't find TMX files to check for status"
When adding key: "False"

Also we are unable to download any of a imported TMX files error: "Contact support"

Enchanment: System should allow compressed .tmx files it will save upload time as .tmx can be compressed up to 10x its original size

Thanks.

**Comment by wsuphappyhour** [comment]
Hi, 
I would like to reopen this issue. We have upgraded Matecat to 1.0.9, but all the issues remain the same.
Errors which we get:
"Upload::_uploadFile -> File Dimensions Not Allowed" (while files are less then <300mb)
"Can't load TMX files right now, try later"
Most frequent: "Can't find TMX files to check for status"
When adding key: "False"
When trying to download tmx: "Contact support"
