### ISSUE TITLE
Hi, we noticed that Matecat alters .ttx file's header. Is it possible to prevent that?

### ISSUE THREAD

**Issue by wsuphappyhour** [matecat/MateCat#461]
Hi, we noticed that Matecat alters .ttx file's header. Is it possible to prevent that? 

Original on the left side.
![image](https://cloud.githubusercontent.com/assets/20355306/19232992/7d419fda-8eeb-11e6-8b02-905b14db6d3d.png)
[Changes.zip](https://github.com/ModernMT/MMT/files/519276/Changes.zip)

Thanks!

**Comment by Ostico** [comment]
Hi @wsuphappyhour ,
this is an issue related to the MateCat-Filters repository.
Please submit the issue to this repository:
https://github.com/matecat/MateCat-Filters
