### ISSUE TITLE
Translation Memory (Server) Integration

### ISSUE THREAD

**Issue by mehmedes** [matecat/MateCat#465]
If I install MateCat from scratch, is it possible to store TMs on the MateCat server and have MateCat use those TMs as presets?

Or is it possible to have MateCat access a TM server such as AmaGama https://github.com/translate/amagama ?

**Comment by Ostico** [comment]
Hello @mehmedes ,

MateCat uses MyMemory as default TM Server, it do not store locally translation memories and there is no plan to add different memory servers.

Anyway, we are working to release MyMemory as open source ( hopefully in the first quarter of the next year ) so anyone can use it's own private version of MyMemory with their MateCat custom installations.

**Comment by mehmedes** [comment]
Thanks for your quick reply. Looking forward to the open source version of MyMemory.

**Comment by tienhuynh17** [comment]
@Ostico, Looks like there's no good news about MyMemory open source, right? I can't find that.

Thank you!
