### ISSUE TITLE
Alternative login instead of Google ?

### ISSUE THREAD

**Issue by mehmedes** [matecat/MateCat#468]
Does MateCat offer an alternative login instead of Google?

**Comment by eclavelr** [comment]
@mehmedes +1 I have the same question

**Comment by eclavelr** [comment]
http://www.proz.com/api-docs
like https://smartcat.ai/sign-in

**Comment by mirko33** [comment]
+1

**Comment by Ostico** [comment]
Added in version [1.1.2d](https://github.com/matecat/MateCat/releases/tag/v1.1.2d)

Closing.
