### ISSUE TITLE
BUG: API GET /v2/project-completion-status/{id_project} -  is not working. Project completion status

### ISSUE THREAD

**Issue by eclavelr** [matecat/MateCat#478]
BUG: API GET /v2/project-completion-status/{id_project} Project completion status
https://www.matecat.com/api/docs#!/Project/get_v2_project_completion_status_id_project

API GET /v2/project-completion-status/{id_project} is not working.
When I set id_project always return { "error": "This project does not exist" } 

@Ostico

**Comment by Ostico** [comment]
Hi @eclavelr ,

we removed this api from list, it is not ready.
