### ISSUE TITLE
Caret position jumps to the beginning or the end of the segment after uppercasing/lowercasing/capitilizing.

### ISSUE THREAD

**Issue by yifanjiang** [matecat/MateCat#504]
It's about a feature that allows people to well format selection by
uppercasing/lowercasing/capitilizing it. After clicking the formatting button,
it will however bring the caret to either the beginning or the end of the
segment. This may annoy some since most of us may want to the caret stays
around the selection even after the formatting.

Reviewed the certain amount of code snippet in ui.core and ui.event, I found
the original behavior is probably not done on purpose. I have a hacky patch to
leverage the rangy generated "undocursorplaceholder" recovering the caret, it
could mitigate the issue.

Thanks for taking a look, a tidy fix could be even more appreciated.
```
From ccab454b7865cd3768e3c7930437a9b47e4af391 Mon Sep 17 00:00:00 2001
From: Yifan J <yifanj2007@gmail.com>
Date: Sun, 6 Nov 2016 17:51:51 +0800
Subject: [PATCH] ui: keep caret position after uppercase, lowercase,
 capitilize

 public/js/cat_source/ui.core.js | 15 +++++++++++++++
 1 file changed, 15 insertions(+)

diff --git a/public/js/cat_source/ui.core.js b/public/js/cat_source/ui.core.js
index 6a26205..43c4bcf 100644
--- a/public/js/cat_source/ui.core.js
+++ b/public/js/cat_source/ui.core.js
@@ -1904,6 +1904,21 @@ UI = {
 		$('.editor .editarea .formatSelection-placeholder').after($('.editor .editarea .rangySelectionBoundary'));
 		$('.editor .editarea .formatSelection-placeholder').remove();
         $('.editor .editarea').trigger('afterFormatSelection');
+
+        // Recover the caret position to the end of the last replaced character
+        setTimeout((function() {
+            return function() {
+                var el = document.getElementsByClassName("undoCursorPlaceholder")[0];
+                if (el) {
+                    range = document.createRange();
+                    selec = window.getSelection();
+                    range.selectNodeContents(el);
+                    range.collapse(false);
+                    selec.removeAllRanges();
+                    selec.addRange(range);
+                }
+            }
+        })(this), 0);
 	},
 
     /**
-- 
2.9.0

```

**Comment by riccio82** [comment]
Hi @yifanjiang ,

thanks for reporting this bug and thanks for your solution.
I fixed by adding a call to a function that does pretty much the same thing as you suggested.
Now it should work correctly.
The fix will be online soon.

**Comment by yifanjiang** [comment]
Thank you @riccio82! Fix verified in dev branch.
