### ISSUE TITLE
 restartAnalysis.sh problem

### ISSUE THREAD

**Issue by czester13** [matecat/MateCat#510]
Dear Support,
I have own MateCAT but after reinstallation I have strange problem. I cannot start FastAnalysis.php and TMAnalysisWorker.php daemons after running  restartAnalysis.sh script. I examined all logs in log_archive and /var/log/* and found nothing. I also run:
php FastAnalysis.php ../../../inc/task_manager_config.ini
php TmAnalysis.php ../../../inc/task_manager_config.ini
from the command line and the result is the same: no error thrown or written in log files.
I checked all system requirements and all installation steps required by manulal installation and I think that everything is OK. 

Would you suggest me something what may be wrong with my installation?

**Comment by czester13** [comment]
Hi, 
I found where was an error. I had to change memory_limit:

form: memory_limit = 1024M
to: memory_limit = -1

There is also mistake in manual installation:

there is: 
sed -i 's/Context createConnector='false'/Context createConnector='true'/g' /etc/default/activemq/conf/activemq.xml

should be:
sed -i 's/Context createConnector="false"/Context createConnector="true"/g' /etc/default/activemq/conf/activemq.xml

Regards

**Comment by Lyonard** [comment]
Thanks czester for reporting this. 
We will change the guide accordingly. 
Bests
