### ISSUE TITLE
Suggested feature for SDLXLIFF: segment status (75% fuzzy, 100% match, Locked)

### ISSUE THREAD

**Issue by mindaugasDEV** [matecat/MateCat#52]
Hello, Developers,

We would like to work on SDLXLIFF files, pretranslated in Studio 2014, then imported to MateCAT.

CONTEXT: we upload SDLXLIFF file (e.g. English-German), pre-translated in SDL Trados 2014. There are NoMatch segments, some segments are LOCKED, some FUZZY matches (but NOT from MyMemory), some 100% matches, some PerfectMatches. 

PROBLEM: in MateCat all segments statuses are lost and translator does not know whether to Skip 100% matches or not, and which segments are FuzzyMatches. She needs to read every segment :(. 

QUESTION: when do you plan to implement showing segment status in MateCat for XLIFF or SDLXLIFF format?

Thanks, 
Mindaugas

**Comment by alessandrocattelan** [comment]
Hello Mindaugas,

I understand your need and appreciate how important this feature is for you. At the moment, however, it is not high on our priority list.

I will try to schedule this for the next two quarters.

Alessandro

**Comment by mindaugasDEV** [comment]
OK, thanks, I understand.
