### ISSUE TITLE
Missing buttons when tag projection is turned on, also no tags are projected.

### ISSUE THREAD

**Issue by wsuphappyhour** [matecat/MateCat#526]
Hi, I have noticed strange behavior of matecat when tag projection is on, printscreens below
Matecat version is 1.0.9a
When turned off
![image](https://cloud.githubusercontent.com/assets/20355306/20568721/08e5c4e4-b1a6-11e6-8a6e-e1b625f03f28.png)
![image](https://cloud.githubusercontent.com/assets/20355306/20568619/c03931ea-b1a5-11e6-8797-ef49bc8585de.png)

When turned on
![image](https://cloud.githubusercontent.com/assets/20355306/20568697/f90eda06-b1a5-11e6-97b9-b5100d52a4e4.png)
![image](https://cloud.githubusercontent.com/assets/20355306/20568742/1ef31cdc-b1a6-11e6-8be0-29893218bfb5.png)

No tags are projected
![image](https://cloud.githubusercontent.com/assets/20355306/20568894/a764075c-b1a6-11e6-8e72-5abf1a05e976.png)
![image](https://cloud.githubusercontent.com/assets/20355306/20568933/d86950dc-b1a6-11e6-9073-b5509716efa6.png)

**Comment by wsuphappyhour** [comment]
Hi,
Is there a way do disable tag projection by default?
Thanks

**Comment by riccio82** [comment]
Hi @wsuphappyhour ,

​w​hat do you mean​ for strange behavior​? 
It is normal that you can not see the buttons under the editArea when the guess tags is active.
To know why the tag projection failed in the segment you show we need the logs file or the project link to be able to recreate the problem.

There is a config variable to turn off guess tags by default when a project is created: 
https://github.com/matecat/MateCat/blob/develop/lib/View/upload.html#L64

For now there is no way to hide the guess tags.

Bye!
