### ISSUE TITLE
Feature request: Option in Editor view to show all formatting characters

### ISSUE THREAD

**Issue by wsuphappyhour** [matecat/MateCat#528]
Hi,
Would it be possible to add feature which would show all the formatting characters (White spaces, tabs, line breaks, etc.)
Thanks

**Comment by wsuphappyhour** [comment]
I see that there is markup for non-breaking space ,  tab, and line break, but is it possible to add markup for simple white space?

**Comment by krishnevsky** [comment]
We would also like to see this feature.
