### ISSUE TITLE
What dependencies can we update till newest versions for MateCAT 1.0?

### ISSUE THREAD

**Issue by mindaugasDEV** [matecat/MateCat#53]
Hello,

GOAL:  I would like to upgrade all or most components so that there were no security vulnerabilities (e.g. PHP 5.0 is not supported anymore) and performance was improved (PHP 7.0 give performance boost for PHP projects).

I will upgrade MateCAT often, therefore I better stick to the versions you use and test yourselfs.

PROBLEM: after installing the below components from scratch and following the Advanced Installation Guide, the MateCAT 0.6.8 was showing empty screen (I did not try 1.0 yet) and only worked when I installed the versions from MateCAT installation guide):
•	Ubuntu  16.04 LTS
•	Apache 2.4.2
•	PHP 7.0.5
•	MySQL 5.7
•	git  2.8.1
•	ActiveMQ 5.13.2 (tested, it works)
•	Redis 3 .0.7
•	Node.js 4.4.3
•	Java 8

QUESTION: tell me which LATEST versions for the above dependencies are OK to use with MateCAT 1.0 e.g.:
•	Ubuntu  14.04 LTS
•	Apache 2.4.2
•	PHP 5.0
<....>

Thanks,
Mindaugas

**Comment by Ostico** [comment]
HI @mindaugasDEV ,

Php 7.0 is not tested on our side and we suggest a php version > 5.4

All other softwares/Operating systems should work, remember to put these services behind firewall and open access only to LAN IPs.

For MySQL we suggest to change the strict mode to 

```
sql-mode="NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
```

Moreover, i suggest you tu update Node.js to version >= v5.7.0 ( your version is vulnerable https://nodejs.org/en/blog/vulnerability/february-2016-security-releases/ )
