### ISSUE TITLE
After installing build 1.0 from scratch, localhost in browser shows empty screen

### ISSUE THREAD

**Issue by mindaugasDEV** [matecat/MateCat#54]
Hello,

My environment: Ubuntu 14.04.1 LTS (as 14.04 LTS is no longer supported) and ActiveMQ 5.13.2 (as the version 5.11.3 from your manual is no longer available).

CONTEXT: after upgrading working Matecat 0.6.8 installation to 1.0 the browser showed only empty screen with favicon in the browser tab. No error message. Restarting Apache or Ubuntu does not help.

I HAVE TRIED ALTERNATIVE: I also installed Matecat 1.0 on clean Ubuntu, hoping that clean install will work. No, it does not. Even after restarting Apache or Ubuntu.

PROBLEM: neither upgrading from 0.6.8 to 1.0 nor clean install of 1.0 works, the browser shows the empty screen (only Matecat favicon).

Please help to troubleshoot the cause of the empty screen.

Thanks,
Mindaugas

**Comment by Ostico** [comment]
Hi @mindaugasDEV 
unfortunately, the installation guide must be updated.

Now, you must install some php dependencies by composer package manager.
If you do not have the composer.phar you must download it.
Go in the MateCat project root and perform these commands:

```bash
php -r "readfile('https://getcomposer.org/installer');" | php
```

This will install the  composer.phar  package manager.

```bash
php composer.phar --no-dev install
```

This will install the new php libraries. 

After that you should update your config.ini file taking the changes from new config.ini.sample in the ./inc folder.

Go into support_scripts/grunt and perform this command:
```bash
npm install
```

Now you can do a 
```bash
grunt deploy
```

**Comment by mindaugasDEV** [comment]
Thanks, I will try. Can you also answer ticket #53 about what new versions if packages I can use?  Can I use PHP 7.0?

**Comment by Ostico** [comment]
Already done
