### ISSUE TITLE
Disabling outsource option causes splitting to fail

### ISSUE THREAD

**Issue by mirko33** [matecat/MateCat#551]
When setting the ENABLE_OUTSOURCE switch in INIT.php to false, splitting won't work, ie. the dialog opens and proposes splits but when you hit Check, it doesn't add up and one cannot confirm.

**Comment by Ostico** [comment]
Hi @mirko33 ,

yes we introduced a bug on that because we are changing the outsource modal. We will fix this bad behaviour in the next releases.

**Comment by Ostico** [comment]
Solved
