### ISSUE TITLE
Hi, tmx memory upload fails

### ISSUE THREAD

**Issue by wsuphappyhour** [matecat/MateCat#576]
Hi, there's problem uploading TMX files.

There's no error thrown, while upload is stuck. 
![image](https://cloud.githubusercontent.com/assets/20355306/21590656/84612b66-d106-11e6-9f8a-1352b2ae720f.png)
All read/write privileges are correct.
![image](https://cloud.githubusercontent.com/assets/20355306/21590537/830a18b4-d105-11e6-948d-1985248b5806.png)

 http://api.mymemory.translated.net/tmx/status?key=355d18ad845807339619&name=Bard_MasterTM_en-GB_ru-RU.tmx

{"responseData":{"tm":[{"id":"588083","source_lang":"","target_lang":"","creation_date":"2017-01-02 14:52:49","num_seg_tot":null,"temp_seg_ins":0,"temp_seg_not_ins":0,"file_name":"Bard_MasterTM_en-GB_ru-RU.tmx","description":"Bard_MasterTM_en-GB_ru-RU.tmx","status":"0","log":null}]},"responseStatus":200}

[log.txt](https://github.com/matecat/MateCat/files/680860/log.txt)

Do you have any ideas how to fix this?
Thanks

**Comment by wsuphappyhour** [comment]
Hi, it seems that www.matecat.com is experiencing same issue.
![image](https://cloud.githubusercontent.com/assets/20355306/21591263/44d301cc-d10b-11e6-8fd0-8a930934e383.png)
Thanks.

**Comment by Ostico** [comment]
Hi @wsuphappyhour ,
this is not an issue that can be fixed. We are working to make more resilient the TMX service.
Anyway, this was a temporary issue, the service was very slow or was not able to load the memories.
Closing.
