### ISSUE TITLE
SQL and filestore tiering, mutiple frontends

### ISSUE THREAD

**Issue by SynergiumAdmin** [matecat/MateCat#604]
Hi, we are currently planing to implement tiering, keep files on an SMB share with automount and SQL in another server, all seems to be working fine
what if we install an additional apache with matecat and specify the same SQL server and the same filestore
this will not brake the database? introduce any anomaly's? as the info I found specifies that is shuld run via replication

For handling more than 200M words per year you will need to add a load balancer in front of the web servers and databases. Databases will need a master-master replica schema. This will require an experienced LAMP and scalability engineer.

**Comment by Ostico** [comment]
I suggest you use NFS instead SMB, SMB protocol is too slow and not good for the concurrency needed by multiple Apache/PHP-FPM forks. Mount your storage in the fstab on yoyr webservers.
I also suggest you to update your matecat installation to the master branch if you want to use a database proxy. 

Anyway, for your workload a master-slave replication with read/write separation is enough.

**Comment by SynergiumAdmin** [comment]
not a proxy we want to use just a single mysql server
https://res.cloudinary.com/atlanta-general/image/upload/v1462382609/WireandFrost/WP-Drawing-3T.png

**Comment by Ostico** [comment]
With a single database server you could experience some slownesses when approaching 200M w/yr, especially in the project creation phase.

Anyway, for your workload a single web server ( ex: 16core >32GB ram ) is enough ( obviously this is not valid if you need HA and server failure tolerance.

**Comment by SynergiumAdmin** [comment]
the 200m/y was an example form matecat documentation, we will have about 30m/y
I just wanted to know if 2 web servers writing to the same file store and db could create conflicts

**Comment by Ostico** [comment]
I can confirm that there are no problems about that.
The only limitation **at moment** is that the analysis daemons MUST be only running on one instance because it is not thought to be distributed among servers. But anyway  it is enough for your needs.

**Comment by SynergiumAdmin** [comment]
perfect, we did not know about the daemons, thanks!

**Comment by SynergiumAdmin** [comment]
but do I understand correctly, this way, only one web server can do the analysis, so we cant use load balancing, the web servers can only work in active passive?
because if we load balance it if the client hits the web server without the analysis daemon it will fail to analyse, and if the primary web server goes down, then it will fail over to the backup it will fail to analyse
thus losing the redundancy primary purpose

**Comment by SynergiumEU** [comment]
bump

**Comment by Ostico** [comment]
The second web server do not needs to have the analysis daemons to work. It take it's info from persistences.
Yes the analysis is a single point of failure in your architecture. 
Anyway, the analysis can be stopped, started or restarted in any moment. 
I suggest you to put the analysis, redis and ActiveMQ in a separated server.
Transform it to a service into init.d and monitor it's status with a service monitor.

**Comment by SynergiumEU** [comment]
nice, will try that, thank you once more
