### ISSUE TITLE
long query

### ISSUE THREAD

**Issue by SynergiumEU** [matecat/MateCat#628]
hi,
shuld this query take up ~50 sec?

-- State: Sending data
SELECT DISTINCT id_file, MIN( segments.id ) AS first_segment, filename AS file_name,
                    FORMAT(
                        SUM( IF( IFNULL( st.eq_word_count, -1 ) = -1, raw_word_count, st.eq_word_count) )
                        , 0
                    ) AS TOTAL_FORMATTED
                FROM files_job
                JOIN segments USING( id_file )
                JOIN files ON files.id = id_file
                JOIN jobs ON jobs.id = files_job.id_job
                LEFT JOIN segment_translations AS st ON segments.id = st.id_segment AND st.id_job = jobs.id
                WHERE files_job.id_job = 79
                AND segments.show_in_cattool = 1
                GROUP BY id_file, jobs.id, jobs.password /* statement may be truncated */

**Comment by Ostico** [comment]
HJi @SynergiumEU ,

of course not :)

Can you paste the result of this query?:

```sql
EXPLAIN
SELECT DISTINCT id_file, MIN( segments.id ) AS first_segment, filename AS file_name,
FORMAT(
SUM( IF( IFNULL( st.eq_word_count, -1 ) = -1, raw_word_count, st.eq_word_count) )
, 0
) AS TOTAL_FORMATTED
FROM files_job
JOIN segments USING( id_file )
JOIN files ON files.id = id_file
JOIN jobs ON jobs.id = files_job.id_job
LEFT JOIN segment_translations AS st ON segments.id = st.id_segment AND st.id_job = jobs.id
WHERE files_job.id_job = 79
AND segments.show_in_cattool = 1
GROUP BY id_file, jobs.id, jobs.password
```

**Comment by SynergiumEU** [comment]
1	SIMPLE	files_job		ref	PRIMARY,id_file	PRIMARY	4	const	1	100.00	Using index; Using temporary; Using filesort
1	SIMPLE	files		eq_ref	PRIMARY	PRIMARY	8	matecat2.files_job.id_file	1	100.00	Using where
1	SIMPLE	jobs		ref	primary_id_pass,id	id	8	const	190	100.00	Using index
1	SIMPLE	segments		ref	id_file,show_in_cat	id_file	8	matecat2.files_job.id_file	850	50.00	Using index condition; Using where
1	SIMPLE	st		eq_ref	PRIMARY,id_job,id_segment	PRIMARY	16	matecat2.segments.id,matecat2.jobs.id	1	100.00

**Comment by Ostico** [comment]
Hi,
the indexes and the query seems ok. The long time execution of this query must be tied to another issue.
