### ISSUE TITLE
1.1.3 build

### ISSUE THREAD

**Issue by SynergiumEU** [matecat/MateCat#633]
>> Matecat Version: 1.1.3

Running "handlebars:all" (handlebars) task
>> 1 file created.

Running "browserify:libs" (browserify) task
>> Bundle ../../public/js/build/react.js created.

Running "browserify:components" (browserify) task
>> Error: Cannot find module 'object-assign' from '/home/matecat/cattool/public/js/cat_source/es6/react/stores'
Warning: Error running grunt-browserify. Use --force to continue.

Aborted due to warnings.

**Comment by riccio82** [comment]
Hi @SynergiumEU,

maybe you not run the deploy command to compile javascript and css sources: 
https://www.matecat.com/advanced-manual-setup/#cjc

You need to launch the npm install command each time you deploy a new version.
