### ISSUE TITLE
Developer documentation for MateCat

### ISSUE THREAD

**Issue by Sebastian-U** [matecat/MateCat#641]
Hi everyone!

We are planning to set up a libre language learning platform for students at our university. They should learn by translating texts from their mother tongue to English. We also try to build an inspiring learning motivation. This should be achieved by providing peer review features and a score or badges for each user based on his activity.

While searching for suitable tools to build upon, we now had a closer look at MateCat. It's standalone version looks very promising because it's already very close to our goal. (Thank you for all the work you have put into it!!) 

To enable scores and badges it would be nice to have an _takenEffort_ property for each user. It could be based on the _manual post editing effort_ fields of the segments that the user edited. I would like to dive deeper into it, but there seems to be no developer documentation available. I have already tracked some entity relations by having a look at the sources of the Models, but it is really time consuming to look everything up.

I really don't want to annoy you with every individual question. 😸 

Are there any sources for API documentation or maybe an UMLs of the layout of the PHP application?

Thanks!
Sebastian

**Comment by Ostico** [comment]
Hi @Sebastian-U ,

the API docs are available here:
https://www.matecat.com/api/docs

Anyway you can see and download in CSV format the post-editing efforts of every job from it's editlog page.

Sorry but at moment there is no UML documentation.
