### ISSUE TITLE
Updating matecat

### ISSUE THREAD

**Issue by ArnoldMo** [matecat/MateCat#678]
Hi,
when updating tiered (WEB, SQL, Workers) servers
we need to pull the new git and compose only, we don't need to update the db? 
and in what order do we need to update them? 1. db, 2. web, 3. workers?

**Matecat Update**
Download the new Matecat version
su - matecat
cd ~/cattool
**Check current version**
git branch
nano inc/version.ini
**Upgrade**
git pull origin master
**PHP Composer**
cd ~/cattool; php -r "readfile('https://getcomposer.org/installer');" | php; php composer.phar --no-dev install

**Compile Javascript code (when updating only on web tier server)**
cd ~/cattool/support_scripts/grunt; npm -y install; grunt deploy

**Comment by ArnoldMo** [comment]
up

**Comment by Ostico** [comment]
Hi @ArnoldMo ,

in your database there should be a table named phinxlog. 
This table is tied to the migration files in the git repository. ``` ./matecat/migrations/ ```

I hope that this guide can help you:
https://docs.google.com/document/d/1A6ha3zTaYuVH8_fOEHhpdCSeOPQ6mHfk1rwNwEO-eLs/edit#
