### ISSUE TITLE
Translation progress stuck at 99%

### ISSUE THREAD

**Issue by mirko33** [matecat/MateCat#730]
We've got translations that remain at 99% completion with something like 7 words missing, but all segments are translated. Clicking on the progress bar or on T+>> doesn't take us to any segment.

Is this a known issue? Any hint as to how to fix or work around this?

We're on version 1.0.9d

I'll be happy to share offline the link to a project where we're seeing this.

**Comment by Ostico** [comment]
Hi @mirko33 
sometimes this happens to us also. 

Normally this is dued to an huge load on the database, some transaction locks are skipped and reverted as deadlocks.

Try to check the load of your database by tuning the running daemons for the analysis.
 In your MateCat version the creation for project and the analysis phase are really expensive tasks.

Maybe it would be useful raise increase the hardware of you database server.

**Comment by mirko33** [comment]
Thanks, good to know,
