### ISSUE TITLE
Matecat page not opening

### ISSUE THREAD

**Issue by SynergiumEU** [matecat/MateCat#779]
Hello, 
what could be the problem if matecat page doesn't open on Chrome on Windows 10 gets window with text:   
1 - Use the tool by visiting https://********.eu from your desktop
SynCAT works great with the following browsers Chrome.

**Comment by Ostico** [comment]
Hi @SynergiumEU ,
which version of chrome you used on Windows 10?

**Comment by SynergiumEU** [comment]
58.0.3029.110 (64-bit)
