### ISSUE TITLE
Unsafe scripts

### ISSUE THREAD

**Issue by SynergiumEU** [matecat/MateCat#784]
on the local matecat we get an error, there is no error on matecat.com

![1](https://cloud.githubusercontent.com/assets/22501289/26300234/386e99de-3ee6-11e7-8712-07c5731d7833.png)

![2](https://cloud.githubusercontent.com/assets/22501289/26300168/02091bb2-3ee6-11e7-9ee8-96a2bbe20e9e.png)

**Comment by Ostico** [comment]
Hi @SynergiumEU 

you have to put the reverse proxy for node js under SSL.
