### ISSUE TITLE
Revision function doesn't work

### ISSUE THREAD

**Issue by kevinvnloctra** [matecat/MateCat#8]
Hi there,

I am trying version 0.5.1 in VM. Everything goes well except the Revise function. After translation, we click Revise in the drop-down menu list in Manage section, then a 404 Not Found page appear.

Would you please check?

Thanks!
![2015-07-03 09_24_14-matecatubuntu running - oracle vm virtualbox](https://cloud.githubusercontent.com/assets/13159396/8491550/4bb1d3e4-2165-11e5-8006-008f82739483.png)

**Comment by antoniofarina** [comment]
Seems to be a bug. Thank you for reporting. We are checking

**Comment by kevinvnloctra** [comment]
It seems fixed, thansk a lot!
