### ISSUE TITLE
Cannot connect from http://127.0.0.1/

### ISSUE THREAD

**Issue by e99h2121** [matecat/MateCat#814]
Hello, 
I'm trying to install by following installation-guide below using "matecat_latest.ova" for VirtualBox.
https://www.matecat.com/installation-guide/

I succeeded to import *.ova, and now I can see the page I intended on http://localhost/ of matecat-VirturalBox.
But I'm facing the trouble. I cannot see Matecat page in case of http://127.0.0.1/.
(Or http://matecat-virtualbox/ ), but Apache2 default page.

![ipaddress_](https://user-images.githubusercontent.com/6320429/27362379-11d657e0-5669-11e7-8bda-c1bb10aebf9c.png)

Any suggestions?

**Comment by Ostico** [comment]
You have to change the virtual host configuration inside the OVA and restart apache

**Comment by e99h2121** [comment]
Thank you for the comment. In fact I changed vhost file but I'm not sure how it should be exactly.

If I want to connect to the virtual machine of VirtualBox by ipaddress from external cli

**Comment by e99h2121** [comment]
Sorry
~Clients, how conf file need to be?

**Comment by Ostico** [comment]
Hi @e99h2121 ,

if you remove the ServerName and ServerAlias directive from the virtualhost Apache will respond to every request on port 80:

https://github.com/matecat/MateCat/blob/develop/INSTALL/matecat-vhost.conf.sample#L2

**Comment by e99h2121** [comment]
Ostico,
Thank you very much! It helps!
