### ISSUE TITLE
Change case doesn't work for Cyrillics

### ISSUE THREAD

**Issue by kosivantsov** [matecat/MateCat#825]
Selecting Cyrillic characters in target field and pressing any of the three case changing buttons has no effect. It works for Latin characters even in the same target segment.

**Comment by riccio82** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Change case doesn't work for Cyrillics](https://trello.com/c/29OzZRJp/637-change-case-doesnt-work-for-cyrillics)

**Comment by riccio82** [comment]
Fixed https://github.com/matecat/MateCat/pull/861
