### ISSUE TITLE
Signing up and using Manage without having a Google account

### ISSUE THREAD

**Issue by mehmedes** [matecat/MateCat#846]
When setting up MateCat on bare iron, is it possible to use MateCat's ``sign up`` and ``manage`` function without having a Google account? The [manual](https://www.matecat.com/advanced-manual-setup/#top) describes how to set up MateCat in order to use Google authentification, could you also please provide some hints how to set up non-Google authentification, if possible?

**Comment by freegenie** [comment]
In version 1.1.2d MateCate introduced signup and login without Google. The process requires an email confirmation step so you'd need to have SMTP server for outgoing emails to be correctly setup. 
Thanks for this report, we will update the documentation soon.
