### ISSUE TITLE
Disable Mymemory 

### ISSUE THREAD

**Issue by mehmedes** [matecat/MateCat#849]
Is it possible to disable MyMemory on a private instance?
Or at least disable look up?

**Comment by Lilimopps** [comment]
It's really interesting for us too. Because we get 100% matches pre-translated from public MyMemory (it changed name to Public_Corpa in interface), but it's often not appropriate for us.

**Comment by Ostico** [comment]
MyMemory disabilitation at moment is not supported and not tested, it can lead to unexpected issues.

**Comment by Lilimopps** [comment]
I mean not total disabling - MyMemory is usefull and we can use it.
But it looks critical if you need to trust your TM while pre-translating 100% matches.

From this point of view for me it would be perfect if project settings look like on attached file - when you can manage each TM separately: https://yadi.sk/i/bzwVb6f13MBus5

**Comment by alessandrocattelan** [comment]
Hello, I confirm that you can now disable look up from the public TM. 

If you have a private TM, you can look up matches just in that one, ignoring the matches from the public TM. Please see attached screenshot.

![screen shot 2017-12-29 at 15 40 31](https://user-images.githubusercontent.com/13222990/34439491-a9ac61b4-ecae-11e7-92d1-5e3233362512.png)

**Comment by Lilimopps** [comment]
Thank you! Great news!

Will you implement 100% Approve checkbox?
ICE match works good, but this option could be useful too.

**Comment by mehmedes** [comment]
Thank you!
