### ISSUE TITLE
Matecat counts white spaces incorrectly when a source segment ends with a tag

### ISSUE THREAD

**Issue by robot-xliff-farmer** [matecat/MateCat#866]
Here is the example: https://www.matecat.com/translate/tag-space-check-test/ru-RU-en-US/839119-c605d4894957#509261790

If you delete the space before "for putting together the file", the warning goes away.

The warning appears when a source segment ends with a tag with no spaces after it but, in the target, the tag is moved to the middle of the sentence and have a space after it.

**Comment by riccio82** [comment]
Fixed
