### ISSUE TITLE
This job is too big.

### ISSUE THREAD

**Issue by HURIMOZ** [matecat/MateCat#868]
I can upload documents fine but Matecat will turn blank after pressing the Translate button after the Analyze step, where the system says "This job is too big." "The analysis was not performed."
Any help welcome...

**Comment by Ostico** [comment]
I suggest you to divide the documents in different projects, there is a limitation for projects bigger than 100.000 segments ( > ~500.000 words ).

**Comment by HURIMOZ** [comment]
Hi,
thank you for your reply.
No matter the size of the document or number of segments, it gets stuck with the same message.
I tried a very simple txt file with just a few words and i etill get the same message too.

**Comment by Ostico** [comment]
Hi @HURIMOZ ,
sorry for misunderstanding, i suggest you to contact the support providing them the info about the link of your analyze page so we can check your issue.

**Comment by HURIMOZ** [comment]
Check this file analysis for instance http://www.transleqo.com/analyze/NDEP_4step_Chuukese/123-23eca6d035d8

**Comment by Ostico** [comment]
Hi @HURIMOZ 

from what i see there is an issue with your FastAnalysis daemon, when it try to contact MyMemory to perform the preliminary analysis:
```
        if ( isset( $result->error->code ) && $result->error->code == -28 ) { //curl timed out
            throw new Exception( "MyMemory Fast Analysis Failed. {$result->error->message}", self::ERR_TOO_LARGE );
```
The wrong exception code is a known bug. 
Try to check the connectivity of your server toward MyMemory server.

Check into your logs: ```/<matecat_intallation_dir>/storage/log_archive/fastAnalysis.log``` to get more info.

**Comment by HURIMOZ** [comment]
Hi @Ostico, thanks for your reply.
Question: Are we doomed to have data transiting to MyMemory and Translated.net with the Open-source MateCat code or can we have the code run and function entirely on our own server?

**Comment by Ostico** [comment]
This is the only exception, but we are planning in the future to change this behaviour.

The data sent to MyMemory in this case, are taken in a temporary memory map to analyze repetition in the documents and after such phase they are discarded.

No data are stored in any way in this phase.
