### ISSUE TITLE
MateCat Instance Performance Optimisation

### ISSUE THREAD

**Issue by uhallac** [matecat/MateCat#876]
Is there a checklist to optimise a MateCat instance or a guide to help detecting any possible bottlenecks when multiple projects are being analysed simultaneously in a MateCat instance?

Thank you.

**Comment by Ostico** [comment]
Hi @uhallac ,

there are some queues that performs project creation and project analysis. 

You can access to your ActiveMQ panel http[s]://<your_instance_url>:8080
