### ISSUE TITLE
A new matecat_latest.ova is needed

### ISSUE THREAD

**Issue by SamuelLarkin** [matecat/MateCat#886]
Hi,
  I've been tasked with adding our Machine Translation Engine to MateCat.  I've started my work with matecat_latest.ova but now I need to update/upgrade because I need [engineController::execute()](https://github.com/matecat/MateCat/blob/develop/lib/Controller/engineController.php#L385) to be defined which is not the case in the default matecat_latest.ova image.

I followed the instructions [here](https://www.matecat.com/advanced-manual-setup/update-matecat-instance/#umc).

Unfortunately, I can't get my image to properly work.  There are errors in the update process.

Here's my modified steps I took.

Matecat’s version on the VM is:
2015-09-14 11:54
499965588cd89cd945e1270beb925b8bbf1cedb1

Starting from matecat_latest.ova with sha1sum == 861791d3f2370ec71de2324935e60f70a98427e9

`VBoxManage import matecat_latest.ova --vsys 0 --vmname MateCatUpgrading`
`VBoxManage modifyvm MateCatUpgrading --natpf1 "ssh,tcp,,4422,,22"`
`VBoxManage modifyvm MateCatUpgrading --natpf1 "MatecatUI1,tcp,,4480,,80"`
`VBoxManage startvm MateCatUpgrading --type headless`

### Add missing software
`sudo apt-get update`
`sudo apt-get -y install openssh-server tig vim aptitude`
`sudo apt-get -y remove --purge libreoffice*`
`sudo apt-get clean`
`sudo apt-get -y autoremove`
#`sudo apt-get upgrade`   # Not enough space on VM

Use aptitude to install mysql-server-5.6 and resolve conflicts by removing mysql-5.5.
Configure Git
`git config --global user.email "myemail"`
`git config --global user.name "myname"`

### Permissions
Looks like when using Google’s OAuth for the first time requires MateCat to be able to create ~/cattool/inc/oauth-token-key.txt thus the folder should at least be writable at that time.
`sudo chmod o+w ~/cattool/inc`

### Update Matecat
`mysql --version`   # should be 5.6 or later
#mysql -u root -p
`cd ~/cattool`
`git branch`
`git checkout -- support_scripts/grunt/package.json`   # The VM contains some modifications.
`git checkout master`   # aka 1d35e0a8fc04cf87216de835a784462ada647bb1
`git pull`
`php composer.phar install`
\# Apply patch to migration script because a table can’t be modified inplace because it was created with mysql prior to 5.6.
`./vendor/bin/phinx migrate -c inc/phinx.php `
`cd support_scripts/grunt/`
#sudo npm install -g npm  # completely brakes npm
`sudo npm cache clear`
`sudo rm -fr node_modules`
`sudo npm install`  # Generates errors but we can still proceed see npm install error
`sudo npm install object-assign immutable` # https://github.com/matecat/MateCat/issues/645
`sudo grunt deploy`

### Migration Script Patch
Some migration failed but could be fixed with the following patch.
```diff
--- a/migrations/20170518102926_add_completed_by_event_id_to_qa_chunk_reviews.php
+++ b/migrations/20170518102926_add_completed_by_event_id_to_qa_chunk_reviews.php
@@ -7,7 +7,7 @@ class AddCompletedByEventIdToQaChunkReviews extends AbstractMatecatMigration
     public $sql_up = "
         ALTER TABLE `qa_chunk_reviews` 
           ADD COLUMN `undo_data` TEXT DEFAULT NULL, 
-          ALGORITHM=INPLACE, LOCK=NONE;" ;
+          ALGORITHM=COPY, LOCK=SHARED;" ;
 
     public $sql_down = "ALTER TABLE `qa_chunk_reviews` DROP COLUMN `undo_data` ; ";
```

 
### npm install error
sudo npm install fails even if the dependencies look correct.  This might be caused by a version of npm/node that is too old.

```bash
npm WARN package.json matecat-tasks@1.0.0 No description
npm WARN package.json matecat-tasks@1.0.0 No repository field.
npm WARN package.json matecat-tasks@1.0.0 No README data
npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-addons-css-transition-group@15.6.0 wants react@^15.4.2
npm ERR! peerinvalid Peer react-dom@15.6.1 wants react@^15.6.1
npm ERR! peerinvalid Peer semantic-ui-react@0.64.8 wants react@>=0.14.0 <= 15
npm ERR! peerinvalid Peer enzyme@2.9.1 wants react@0.13.x || 0.14.x || ^15.0.0-0 || 15.x

npm ERR! System Linux 4.4.0-31-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/matecat/cattool/support_scripts/grunt
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! code EPEERINVALID
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/matecat/cattool/support_scripts/grunt/npm-debug.log
npm ERR! not ok code 0
```

Obviously, fixing sudo npm install with help me get my VM up-and-running.
Maybe, I missed a step. ;)

**Comment by emale999** [comment]
Have the same problem with a fresh install.
Followed the guide here https://www.matecat.com/advanced-manual-setup/#ctefs and now I'm stuck near completion with the same error as SamuelLarkin told.

**Comment by emale999** [comment]
Another try one year later with matecat_latest.ova (which doesn't seem to be really "latest" but from 2016) and the update guide...but only get errors when updating the matecat code https://www.matecat.com/advanced-manual-setup/update-matecat-instance/#uc

Merge conflict with git, some problems with composer not updating, only errors with npm...giving up.

**Comment by tsanev016** [comment]
Hi, Im searhing for working link to download.

MateCat Virtual Machine image

Can you help me?

This is official link from site but , file is not found.
https://www.matecat.com/vm/matecat_latest.ova

Thank you so much!

**Comment by riccio82** [comment]
New installation guide: https://site.matecat.com/installation-guide
No more Virtual Machine Image, I am sorry.
