### ISSUE TITLE
Analysis issue

### ISSUE THREAD

**Issue by kevinvnloctra** [matecat/MateCat#9]
Hi there,

Thanks for your fixing with Revise function.

I am checking the system again and it notifies me with a new bug.

It seems Analysis function didn't work in somewhere.

1/ In Volume Analysis page, it always display as Fast word counting... Also it doesn't breakdown to fuzzy match table.
2/ In Translate/Revise editor window, it always display as Calculating word count...

I attach here screenshot for your reference.

Thank you very much!

Kevin
![2015-07-09 10_54_53-revise - sample-04 - 8 - c c c c](https://cloud.githubusercontent.com/assets/13159396/8587650/233655f2-2629-11e5-8279-b05aac8e1302.png)
![2015-07-09 10_45_55-volume analysis - matecat - c c c c](https://cloud.githubusercontent.com/assets/13159396/8587651/23397aac-2629-11e5-8ba8-c3ab9f858f43.png)

**Comment by matecat** [comment]
HI @kevinvnloctra ,
it seems you not started the analysis daemons.

Please follow these instructions to properly install MateCat:
http://www.matecat.com/installation-guide/#advanced
