### ISSUE TITLE
Changing default MT engine & shared MT engines

### ISSUE THREAD

**Issue by mxposed** [matecat/MateCat#953]
Hi!

We have a standalone MateCat installation and right now it's not very convenient to start new projects, because we have to change settings and select our default MT engine every time. Also every person who creates projects needs to add their own MT engine.
I wonder if you have in plans 
1) a configuration option to change the default MT engine for new projects
2) shared MT engines for teams or global MT engines for the whole installation. I discovered the amt=true GET parameter, but that's not very convenient.

If you know how it should be done, I can implement it and send you a pull-request

**Comment by Ostico** [comment]
Hi @mxposed ,
sorry, but at moment there is no plan to develop these features.

We have in the roadmap to build a user preference panel, but i can't say when this feature will be implemented.

Anyway, tnx for the amt parameter you found, it was a security issue, we HotFixed in production and removed from all the branches.

https://github.com/matecat/MateCat/pull/965

**Comment by mxposed** [comment]
Thank you for your answer. If we decide to do it properly (and not by hacks), I'll send a pull request then

**Comment by JohnReinhold** [comment]
Today, six years later, I ran into the same issue. It would be so nice to set default TM/MT settings on users and/or teams.
