### ISSUE TITLE
Curl error 7: Failed to connect to localhost port 8732: Connection refused

### ISSUE THREAD

**Issue by laiviet** [matecat/MateCat#970]
I got this error durring upload a file to server.

> Curl error 7: Failed to connect to localhost port 8732: Connection refused

I also got some strange things on apache2 log

> [Sun Sep 17 02:42:42.345723 2017] [:error] [pid 29816] [client 43.249.176.96:52550] PHP Notice:  Undefined index: upload_session in /home/matecat/cattool/lib/Utils/fileupload/upload.class.php on line 40, 
> [Sun Sep 17 02:42:42.345904 2017] [:error] [pid 29816] [client 43.249.176.96:52550] PHP Warning:  sha1_file(/home/matecat/cattool/storage/upload//Le-mot-du-Maire-R.Principal-FINAL.docx): failed to open stream: No such file or directory in /home/matecat/cattool/lib/Utils/fileupload/upload.class.php on line 651, referer: 
> [Sun Sep 17 02:43:16.699478 2017] [:error] [pid 29953] [client 43.249.176.96:52553] PHP Notice:  Undefined index: upload_session in /home/matecat/cattool/lib/Utils/fileupload/upload.class.php on line 40,
> [Sun Sep 17 02:47:43.472508 2017] [:error] [pid 29844] [client 43.249.176.96:52633] PHP Warning:  sha1_file(/home/matecat/cattool/storage/upload/{E5C23F28-DA20-C3C7-D9E2-5E637A95096C}/Le-mot-du-Maire-R.Principal-FINAL.docx): failed to open stream: No such file or directory in /home/matecat/cattool/lib/Utils/fileupload/upload.class.php on line 651, 

Please help me.
Thanks,
Viet

**Comment by Ostico** [comment]
Hello @laiviet ,
you tried to connect to the document filters to convert a file ( localhost:8732 ), but it is down or not reachable.

**Comment by laiviet** [comment]
Thank you so much. I have start the Filter. Thanks.
