### ISSUE TITLE
SQL error when creating job: Data too long for column 'completed'

### ISSUE THREAD

**Issue by mirko33** [matecat/MateCat#974]
Fresh install of version 1.3.4g
The full error as displayed on the upload page upon my first attempt to create a job:
>>
Failed to create Job. ( SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'completed' at row 1 )
<<
Maybe a query that tries to write the wrong data type to the completed column of the jobs table?

**Comment by mirko33** [comment]
Is this not something anyone else has experienced, or is there something obvious I'm dong wrong?

**Comment by Ostico** [comment]
Hi @mirko33 ,
the completed field is in the jobs table and it is defined as bit(1). Which version of MySQL are you using and what configuration file?

**Comment by mirko33** [comment]
MySQL is version 5.7.19-0ubuntu0.16.04.1.
MySQL configuration file? The only file with settings I can see has this:

> socket = /var/run/mysqld/mysqld.sock
nice            = 0
[mysqld]
user            = mysql
pid-file        = /var/run/mysqld/mysqld.pid
socket          = /var/run/mysqld/mysqld.sock
port            = 3306
basedir         = /usr
datadir         = /var/lib/mysql
tmpdir          = /tmp
lc-messages-dir = /usr/share/mysql
skip-external-locking
bind-address            = 127.0.0.1
key_buffer_size         = 16M
max_allowed_packet      = 16M
thread_stack            = 192K
thread_cache_size       = 8
myisam-recover-options  = BACKUP
query_cache_limit       = 1M
query_cache_size        = 16M
log_error = /var/log/mysql/error.log
expire_logs_days        = 10
max_binlog_size   = 100M
                                                                   
The MateCat config is still as out of the box other than for db user password, but that's working

**Comment by mirko33** [comment]
The changes to my.cnf that were documented in a different thread, for a different mySQL problem fixed this for me. I added the following two lines at the end of /etc/mysql/my.cnf
>[mysqld]
sql-mode="NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
