### ISSUE TITLE
Notes duplication for multiple languages

### ISSUE THREAD

**Issue by hahn-kev** [matecat/MateCat#975]
I'm using Matecat to translate Angular applications and Angular includes some notes that can be included from the developer to the translator, I was wondering if support could be included to display these notes the to translator while using Matecat?

Here's an example of xlf file

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
  <file source-language="en" datatype="plaintext" original="ng2.template">
    <body>
      <trans-unit id="41aac9cecddc9f345c263d3742192e68e227e413" datatype="html">
        <source>Menu</source>
        <context-group purpose="location">
          <context context-type="sourcefile">app\app.component.ts</context>
          <context context-type="linenumber">4</context>
        </context-group>
        <note priority="1" from="description">menu button tooltip</note>
      </trans-unit>
    </body>
  </file>
</xliff>
```

**Comment by riccio82** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[BUG] - Le note dello xliff non vengono riportate nel tab Messages.](https://trello.com/c/ovkWOJ0O/770-bug-le-note-dello-xliff-non-vengono-riportate-nel-tab-messages)

**Comment by hahn-kev** [comment]
Thanks @riccio82, I quickly glanced at the source and it seems like [this function](https://github.com/matecat/MateCat/blob/develop/lib/Utils/xliff.parser.1.3.class.php#L355) is using the regex `<note>(.+?)</note>` which could be changed to: `<note.*>(.+?)</note>` and that would probably fix the issue.

**Comment by Ostico** [comment]
Accepted. Fixed in master branch.

**Comment by hahn-kev** [comment]
Awesome, thank you! About how long does it usually take for changes to get to the public site? And will I have to re-upload the translation files in order for it to recognize the notes?

**Comment by hahn-kev** [comment]
Hi @Ostico I'm using the new feature on the matecat website, and it's now showing my notes, however, it seems a bit broken as it's showing them multiple times, even when there's only a single note.
![image](https://user-images.githubusercontent.com/4575355/31633293-be79535a-b274-11e7-8133-ebae883b4d9e.png)

After doing a bit of digging this seems to only happen when creating a single project that translates into multiple languages. When I was only translating to 1 language I only saw the note once, however, when translating to 3 languages I saw the note 3 times.

**Comment by Ostico** [comment]
Tnx @hahn-kev , are you using the lastest MateCat version?

**Comment by hahn-kev** [comment]
@Ostico I'm using the matecat.com website

**Comment by Ostico** [comment]
Fixed 

https://github.com/matecat/MateCat/commit/49415e8bfa011d8b9bd45f01b26d651026e483e9
