### ISSUE TITLE
How to use MMT Engine client and plugin implementation (your hosted MMT and selfhosted)?

### ISSUE THREAD

**Issue by mindaugasDEV** [matecat/MateCat#992]
Hello,

Thanks for build 2.0. You wrote that it has “MMT Engine client and plugin implementation ( unstable )“
We have installed build and don`t find how can we use MMT in both scenarios:
1) your hosted MMT services (link to credit card payment HTML page exists in the code, but MMT engine is not shown in MT providers list in Settings->MT providers)
2) our own hosted MMT via RestAPI (we dont see the place in code where we could enter address to our local MMT installation))

I guess that you are waiting to make some bigger announcement about both options, but it would be good that we tried using them earlier, even if their are not stable, and reporting the bugs, this is the power of Open Source.

Thanks!

**Comment by Ostico** [comment]
Sorry, it is unstable, furthermore, we are changing the API. It is not available.

**Comment by Ostico** [comment]
This feature will be available ( only for our hosted MMT server because of the public MMT package release ) approximately at the end of October.

**Comment by Ostico** [comment]
Currently in test.
