### ISSUE TITLE
How to use ICE matches ( Powered by MyMemory service and selfhosted)

### ISSUE THREAD

**Issue by mindaugasDEV** [matecat/MateCat#993]
Hello,

Thanks for build 2.0. You wrote that it has “ICE matches ( Powered by MyMemory service )“

We have installed the build and don`t find how can we use ICE in both scenarios:
1) your hosted MyMemory services and ICE matches
2) our own hosted Matecat (if it works that way)

How it works in general? Can it be testes in your Matecat.com already?

I guess that you are waiting to make some bigger announcement about both options, but it would be good that we tried using them earlier, even if their are not stable, and reporting the bugs, this is the power of Open Source.

Thanks!

**Comment by Ostico** [comment]
Hi @mindaugasDEV ,
the ICES are already promoted to production and they works both on your local installation and on www.matecat.com. 

Of course it works only if MyMemory is enabled for the job.

ICES works in this manner:

- When a translation is performed MateCat sends the actual source and translation, the preceding source and the following one.
- When a a translation is request to the TM server, MateCat sends the request in the same manner, preceding source, actual source and the following one, if they all match an ICE score is returned.
- When a document is analyzed the same thing happens for each segment, and when MateCat gets an ICE score, the translation retrieved is marked as approved and "locked" in the UI. The word count is set to 0 and also the payable ( 100% discount ).

So, the order of the segments is also important to have ICE matches.

**Comment by mindaugasDEV** [comment]
Thanks :)
